// SPDX-License-Identifier: MIT

// Validates the §16.10 OpenSLO export against a JSON Schema
// transcription of the OpenSLO v1 specification (vendored at
// tests/testdata/openslo, see the README there for provenance),
// rather than against Lenny's own decoding of a handful of fields
// (pkg/alerting/rules/openslo_test.go). Neither the existing unit
// tests nor RenderOpenSLO's own validateForOpenSLO catch a document
// that satisfies Lenny's reading of the export but violates the
// OpenSLO v1 object model an external OpenSLO-conformant tool
// (Sloth, Nobl9, OpenSLO Reliably) enforces. This file closes that
// gap.
package tier0_static

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/santhosh-tekuri/jsonschema/v5"
	"gopkg.in/yaml.v3"
	k8syaml "sigs.k8s.io/yaml"

	"github.com/lennylabs/lenny/tests/testinfra/schematest"
)

// openSLOSchemaFile is the JSON Schema transcription of the OpenSLO v1
// object model (tests/testdata/openslo/README.md documents provenance).
const openSLOSchemaFile = "tests/testdata/openslo/schema/openslo-v1.schema.json"

// openSLOChartFragmentPath is the code-generated §16.10 chart fragment
// (see charts/lenny/files/openslo.yaml's own header: "Code generated by
// cmd/gen-alerting-rules ... DO NOT EDIT. Run `make generate` to
// refresh."), spliced into a ConfigMap by
// charts/lenny/templates/openslo-configmap.yaml when
// monitoring.openslo.enabled is set.
const openSLOChartFragmentPath = "charts/lenny/files/openslo.yaml"

// openSLOKind is the minimal envelope needed to route each document in
// the multi-document chart fragment to its per-kind subschema.
type openSLOKind struct {
	Kind string `yaml:"kind"`
}

// spec: §16.10 lines 742-746 ("the Helm chart renders the latency and
// availability SLOs from §16.5 as OpenSLO v1 YAML documents ... the
// chart emits a ConfigMap containing the OpenSLO SLO, SLI, AlertPolicy,
// and AlertNotificationTarget objects for the deployer's tooling to
// consume").
// diagnosis: a failure here means the generated §16.10 chart fragment
// (charts/lenny/files/openslo.yaml, regenerate with `make generate`
// after changing pkg/alerting/rules/openslo.go) contains a document
// that is well-formed per Lenny's own OpenSLO rendering but violates
// the OpenSLO v1 object model itself — a real OpenSLO-conformant tool
// consuming the rendered ConfigMap would reject or misinterpret the
// document even though RenderOpenSLO's own validateForOpenSLO and the
// package's unit tests report it as fine. Check the reported document
// index and kind against pkg/alerting/rules/openslo.go's RenderOpenSLO
// to find which part of the render produced the offending shape.
func TestOpenSLOChartFragmentMatchesSpecification(t *testing.T) {
	root := schematest.RepoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, openSLOChartFragmentPath))
	if err != nil {
		t.Fatalf("read %s: %v", openSLOChartFragmentPath, err)
	}

	schemasByKind := map[string]struct {
		compileFragment string
	}{
		"SLI":                     {compileFragment: "SLIDocument"},
		"SLO":                     {compileFragment: "SLODocument"},
		"AlertPolicy":             {compileFragment: "AlertPolicyDocument"},
		"AlertNotificationTarget": {compileFragment: "AlertNotificationTargetDocument"},
	}

	dec := yaml.NewDecoder(bytes.NewReader(raw))
	docCount := 0
	for {
		var node yaml.Node
		if err := dec.Decode(&node); err != nil {
			break
		}
		docCount++

		// Re-marshal the isolated document node to bytes, then convert
		// through sigs.k8s.io/yaml so the resulting instance uses
		// JSON-compatible types (string keys, float64/JSON-number
		// values) rather than gopkg.in/yaml.v3's native Go types.
		docYAML, err := yaml.Marshal(&node)
		if err != nil {
			t.Fatalf("re-marshal document %d: %v", docCount, err)
		}
		docJSON, err := k8syaml.YAMLToJSON(docYAML)
		if err != nil {
			t.Fatalf("convert document %d to JSON: %v", docCount, err)
		}

		var kindOnly openSLOKind
		if err := json.Unmarshal(docJSON, &kindOnly); err != nil {
			t.Fatalf("decode kind for document %d: %v", docCount, err)
		}
		kindInfo, ok := schemasByKind[kindOnly.Kind]
		if !ok {
			t.Errorf("document %d has kind %q, want one of SLI, SLO, AlertPolicy, AlertNotificationTarget", docCount, kindOnly.Kind)
			continue
		}

		var instance any
		if err := json.Unmarshal(docJSON, &instance); err != nil {
			t.Fatalf("decode document %d as JSON: %v", docCount, err)
		}

		sch := schematest.Compile(t, openSLOSchemaFile+"#/$defs/"+kindInfo.compileFragment)
		if err := sch.Validate(instance); err != nil {
			reportSchemaViolations(t, docCount, kindOnly.Kind, err)
		}
	}
	if docCount == 0 {
		t.Fatal("chart fragment contained no OpenSLO documents")
	}
}

// reportSchemaViolations walks every leaf cause of a jsonschema
// validation failure and reports each as a separate test error. The
// library's ValidationError.Error() string only follows the first
// cause at each level, so a document failing two independent
// constraints (for example both a missing required property and an
// oversized array) would otherwise surface only one of the two.
func reportSchemaViolations(t *testing.T, docIndex int, kind string, err error) {
	t.Helper()
	ve, ok := err.(*jsonschema.ValidationError)
	if !ok {
		t.Errorf("document %d (kind %s) does not validate against the OpenSLO v1 specification: %v", docIndex, kind, err)
		return
	}
	var walk func(*jsonschema.ValidationError)
	walk = func(e *jsonschema.ValidationError) {
		if len(e.Causes) == 0 {
			t.Errorf("document %d (kind %s) does not validate against the OpenSLO v1 specification: %s", docIndex, kind, e.Error())
			return
		}
		for _, c := range e.Causes {
			walk(c)
		}
	}
	walk(ve)
}
