// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"sync/atomic"
	"testing"
)

// TestHandleMessageStampsSchemaVersion_spec_15_4_1_1499 asserts the
// streaming-echo reference runtime stamps schemaVersion on every emitted
// OutputPart — both the text parts it generates and the input parts it
// echoes verbatim. outputpart.schema.json makes schemaVersion required,
// so a third-party author cloning this runtime inherits compliant output.
// spec: §15.4.1 line 1499-1501 / 15.4-MED-021.
func TestHandleMessageStampsSchemaVersion_spec_15_4_1_1499(t *testing.T) {
	var buf bytes.Buffer
	w := newWriter(&buf)
	var seq atomic.Uint64

	// A text part (generated by the runtime) and a non-text part (echoed
	// through the passthrough branch) — both must carry schemaVersion.
	in := []byte(`{"type":"message","id":"m1","input":[` +
		`{"type":"text","inline":"hi","id":"p1"},` +
		`{"type":"image","ref":"blob://x","id":"p2"}]}`)
	if err := handleMessage(context.Background(), w, in, &seq); err != nil {
		t.Fatalf("handleMessage: %v", err)
	}

	var resp struct {
		Type   string `json:"type"`
		Output []struct {
			SchemaVersion int    `json:"schemaVersion"`
			Type          string `json:"type"`
		} `json:"output"`
	}
	if err := json.Unmarshal(buf.Bytes(), &resp); err != nil {
		t.Fatalf("decode response: %v (raw=%s)", err, buf.String())
	}
	if resp.Type != "response" {
		t.Fatalf("response.type = %q, want response", resp.Type)
	}
	if len(resp.Output) != 2 {
		t.Fatalf("got %d output parts, want 2", len(resp.Output))
	}
	for i, p := range resp.Output {
		if p.SchemaVersion < 1 {
			t.Errorf("output[%d] (%s): schemaVersion = %d, want >= 1", i, p.Type, p.SchemaVersion)
		}
	}
}
