// SPDX-License-Identifier: MIT

// §4.3 / §12.2.4 Token Service gRPC contract. The gateway calls these
// RPCs over mTLS to materialize, rotate, and revoke credential leases.
// The Token Service runs as a separate Deployment with KMS access; the
// gateway has no KMS decrypt grants and cannot mint leases in-process
// once the credential boundary is fully enforced.
//
// The three RPCs intentionally share the AssignCredentials,
// RotateCredentials, and RevokeCredentials names with the gateway↔pod
// Adapter service (`lenny.adapter.v1.Adapter`); the layers differ:
// these RPCs flow gateway → Token Service and produce a freshly
// materialized lease set, while the Adapter RPCs flow gateway → pod
// and deliver an already-materialized lease set to the runtime.
//
// See spec/04_system-components.md §4.3 and §4.9.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lenny-tokenservice.proto

package tokenservicev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenService_AssignCredentials_FullMethodName = "/lenny.tokenservice.v1.TokenService/AssignCredentials"
	TokenService_RotateCredentials_FullMethodName = "/lenny.tokenservice.v1.TokenService/RotateCredentials"
	TokenService_RevokeCredentials_FullMethodName = "/lenny.tokenservice.v1.TokenService/RevokeCredentials"
)

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenService is the §4.3 credential-materialization service.
// The service is fully stateless: every replica can serve every
// request and durable state lives in Postgres (encrypted credential
// material) plus the KMS the Token Service has decrypt rights to.
type TokenServiceClient interface {
	// AssignCredentials materializes a credential lease per requested
	// pool for a session. The Token Service selects a credential from
	// each pool per the §4.9 assignment strategy, mints the lease,
	// records it in the credential-lease store, and returns the
	// materialized lease map keyed by provider id.
	AssignCredentials(ctx context.Context, in *AssignCredentialsRequest, opts ...grpc.CallOption) (*AssignCredentialsResponse, error)
	// RotateCredentials replaces a previously assigned lease with a
	// fresh one from the same pool (or, for a user-backed lease, the
	// same credential ref). The old lease is released; the new lease
	// is recorded and returned.
	RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error)
	// RevokeCredentials releases a lease and drops the credential's
	// session-slot accounting. The lease becomes invalid immediately.
	RevokeCredentials(ctx context.Context, in *RevokeCredentialsRequest, opts ...grpc.CallOption) (*RevokeCredentialsResponse, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) AssignCredentials(ctx context.Context, in *AssignCredentialsRequest, opts ...grpc.CallOption) (*AssignCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignCredentialsResponse)
	err := c.cc.Invoke(ctx, TokenService_AssignCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCredentialsResponse)
	err := c.cc.Invoke(ctx, TokenService_RotateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) RevokeCredentials(ctx context.Context, in *RevokeCredentialsRequest, opts ...grpc.CallOption) (*RevokeCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialsResponse)
	err := c.cc.Invoke(ctx, TokenService_RevokeCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServiceServer is the server API for TokenService service.
// All implementations should embed UnimplementedTokenServiceServer
// for forward compatibility.
//
// TokenService is the §4.3 credential-materialization service.
// The service is fully stateless: every replica can serve every
// request and durable state lives in Postgres (encrypted credential
// material) plus the KMS the Token Service has decrypt rights to.
type TokenServiceServer interface {
	// AssignCredentials materializes a credential lease per requested
	// pool for a session. The Token Service selects a credential from
	// each pool per the §4.9 assignment strategy, mints the lease,
	// records it in the credential-lease store, and returns the
	// materialized lease map keyed by provider id.
	AssignCredentials(context.Context, *AssignCredentialsRequest) (*AssignCredentialsResponse, error)
	// RotateCredentials replaces a previously assigned lease with a
	// fresh one from the same pool (or, for a user-backed lease, the
	// same credential ref). The old lease is released; the new lease
	// is recorded and returned.
	RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error)
	// RevokeCredentials releases a lease and drops the credential's
	// session-slot accounting. The lease becomes invalid immediately.
	RevokeCredentials(context.Context, *RevokeCredentialsRequest) (*RevokeCredentialsResponse, error)
}

// UnimplementedTokenServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenServiceServer struct{}

func (UnimplementedTokenServiceServer) AssignCredentials(context.Context, *AssignCredentialsRequest) (*AssignCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCredentials not implemented")
}
func (UnimplementedTokenServiceServer) RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCredentials not implemented")
}
func (UnimplementedTokenServiceServer) RevokeCredentials(context.Context, *RevokeCredentialsRequest) (*RevokeCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCredentials not implemented")
}
func (UnimplementedTokenServiceServer) testEmbeddedByValue() {}

// UnsafeTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServiceServer will
// result in compilation errors.
type UnsafeTokenServiceServer interface {
	mustEmbedUnimplementedTokenServiceServer()
}

func RegisterTokenServiceServer(s grpc.ServiceRegistrar, srv TokenServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenService_ServiceDesc, srv)
}

func _TokenService_AssignCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).AssignCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_AssignCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).AssignCredentials(ctx, req.(*AssignCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_RotateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).RotateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_RotateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).RotateCredentials(ctx, req.(*RotateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_RevokeCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).RevokeCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_RevokeCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).RevokeCredentials(ctx, req.(*RevokeCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenService_ServiceDesc is the grpc.ServiceDesc for TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lenny.tokenservice.v1.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignCredentials",
			Handler:    _TokenService_AssignCredentials_Handler,
		},
		{
			MethodName: "RotateCredentials",
			Handler:    _TokenService_RotateCredentials_Handler,
		},
		{
			MethodName: "RevokeCredentials",
			Handler:    _TokenService_RevokeCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lenny-tokenservice.proto",
}
