// SPDX-License-Identifier: MIT

// §4.3 / §12.2.4 Token Service gRPC contract. The gateway calls these
// RPCs over mTLS to materialize, rotate, and revoke credential leases.
// The Token Service runs as a separate Deployment with KMS access; the
// gateway has no KMS decrypt grants and cannot mint leases in-process
// once the credential boundary is fully enforced.
//
// The three RPCs intentionally share the AssignCredentials,
// RotateCredentials, and RevokeCredentials names with the gateway↔pod
// Adapter service (`lenny.adapter.v1.Adapter`); the layers differ:
// these RPCs flow gateway → Token Service and produce a freshly
// materialized lease set, while the Adapter RPCs flow gateway → pod
// and deliver an already-materialized lease set to the runtime.
//
// See spec/04_system-components.md §4.3 and §4.9.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lenny-tokenservice.proto

package tokenservicev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id is the §4.2 tenant that owns the session.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// session_id is the §4.6 session the lease is bound to.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// user_id is the end-user identifier (optional, for user-scoped pools).
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// pod_spiffe_uri is the issuing pod's SPIFFE URI used for proxy-mode
	// SPIFFE-binding (§4.9). Empty disables binding.
	PodSpiffeUri string `protobuf:"bytes,4,opt,name=pod_spiffe_uri,json=podSpiffeUri,proto3" json:"pod_spiffe_uri,omitempty"`
	// pool_ids names the §4.9 credential pools to materialize. The
	// response carries one entry per successfully materialized pool.
	PoolIds       []string `protobuf:"bytes,5,rep,name=pool_ids,json=poolIds,proto3" json:"pool_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCredentialsRequest) Reset() {
	*x = AssignCredentialsRequest{}
	mi := &file_lenny_tokenservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCredentialsRequest) ProtoMessage() {}

func (x *AssignCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCredentialsRequest.ProtoReflect.Descriptor instead.
func (*AssignCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{0}
}

func (x *AssignCredentialsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AssignCredentialsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AssignCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignCredentialsRequest) GetPodSpiffeUri() string {
	if x != nil {
		return x.PodSpiffeUri
	}
	return ""
}

func (x *AssignCredentialsRequest) GetPoolIds() []string {
	if x != nil {
		return x.PoolIds
	}
	return nil
}

type AssignCredentialsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// leases is the materialized lease set, keyed by provider id.
	Leases        map[string]*CredentialLease `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCredentialsResponse) Reset() {
	*x = AssignCredentialsResponse{}
	mi := &file_lenny_tokenservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCredentialsResponse) ProtoMessage() {}

func (x *AssignCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCredentialsResponse.ProtoReflect.Descriptor instead.
func (*AssignCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{1}
}

func (x *AssignCredentialsResponse) GetLeases() map[string]*CredentialLease {
	if x != nil {
		return x.Leases
	}
	return nil
}

type RotateCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id is the tenant that owns the lease.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// lease_id identifies the lease to rotate.
	LeaseId       string `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCredentialsRequest) Reset() {
	*x = RotateCredentialsRequest{}
	mi := &file_lenny_tokenservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCredentialsRequest) ProtoMessage() {}

func (x *RotateCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RotateCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{2}
}

func (x *RotateCredentialsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RotateCredentialsRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type RotateCredentialsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease is the freshly minted replacement.
	Lease         *CredentialLease `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCredentialsResponse) Reset() {
	*x = RotateCredentialsResponse{}
	mi := &file_lenny_tokenservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCredentialsResponse) ProtoMessage() {}

func (x *RotateCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RotateCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{3}
}

func (x *RotateCredentialsResponse) GetLease() *CredentialLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id is the tenant that owns the lease.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// lease_id identifies the lease to revoke.
	LeaseId string `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// reason is the operator-supplied revocation reason recorded on the
	// §4.9.2 credential audit event.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialsRequest) Reset() {
	*x = RevokeCredentialsRequest{}
	mi := &file_lenny_tokenservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialsRequest) ProtoMessage() {}

func (x *RevokeCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeCredentialsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeCredentialsRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RevokeCredentialsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialsResponse) Reset() {
	*x = RevokeCredentialsResponse{}
	mi := &file_lenny_tokenservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialsResponse) ProtoMessage() {}

func (x *RevokeCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RevokeCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{5}
}

// CredentialLease mirrors the §4.9 in-process credential.Lease on the
// wire. Pod-facing delivery uses the lenny.adapter.v1.CredentialLease
// projection; this gateway↔Token-Service shape carries the full lease
// record so the gateway can record it and route proxy traffic.
type CredentialLease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_id is the opaque per-mint identifier (cl-…).
	LeaseId string `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// session_id is the bound session.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// provider is the §4.9 upstream provider (anthropic_direct, …).
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// source is the §4.9 lease source (pool, user).
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// pool_id is the §4.9 pool the lease was minted from (source=pool).
	PoolId string `protobuf:"bytes,5,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// credential_id identifies the pool credential the lease maps to.
	CredentialId string `protobuf:"bytes,6,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// tenant_id is the tenant for a user-scoped lease (source=user).
	TenantId string `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// credential_ref is the user-supplied credential reference (source=user).
	CredentialRef string `protobuf:"bytes,8,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	// delivery_mode is the §4.9 delivery mode (proxy, direct).
	DeliveryMode string `protobuf:"bytes,9,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	// expires_at is the synthetic TTL expiry instant.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// renew_before is the §4.9 proactive-renewal trigger instant.
	RenewBefore *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=renew_before,json=renewBefore,proto3" json:"renew_before,omitempty"`
	// fallback_allowed reports whether the §4.9 fallback rotation may
	// replace the lease without LLM-proxy circuit involvement.
	FallbackAllowed bool `protobuf:"varint,12,opt,name=fallback_allowed,json=fallbackAllowed,proto3" json:"fallback_allowed,omitempty"`
	// spiffe_uri is the issuing pod's SPIFFE URI when proxy SPIFFE
	// binding is in effect.
	SpiffeUri string `protobuf:"bytes,13,opt,name=spiffe_uri,json=spiffeUri,proto3" json:"spiffe_uri,omitempty"`
	// proxy_url is the §4.9 LLM-proxy endpoint for a proxy-mode lease.
	ProxyUrl string `protobuf:"bytes,14,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	// proxy_dialect is the §4.9 LLM-proxy dialect for a proxy-mode lease.
	ProxyDialect string `protobuf:"bytes,15,opt,name=proxy_dialect,json=proxyDialect,proto3" json:"proxy_dialect,omitempty"`
	// lease_token is the opaque bearer the pod's SDK uses on the proxy
	// endpoint. Empty for direct-mode leases.
	LeaseToken string `protobuf:"bytes,16,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	// upstream_model is the optional proxy-mode upstream model hint.
	UpstreamModel string `protobuf:"bytes,17,opt,name=upstream_model,json=upstreamModel,proto3" json:"upstream_model,omitempty"`
	// upstream_credential is the materialized upstream provider secret
	// (API key, access token) the Token Service resolved for this lease.
	// The gateway caches it in its in-memory §4.9 credential cache
	// (`pkg/gateway/credcache`) keyed by the lease's CredentialKey so the
	// LLM reverse proxy can inject it into upstream calls. The field
	// carries credential material and MUST be excluded from gRPC access
	// log payload capture, OpenTelemetry span attributes, and any
	// request/response logging middleware. The mTLS transport between
	// gateway and Token Service protects it on the wire; no other layer
	// sees it. Empty for direct-mode leases where the upstream secret is
	// delivered to the runtime via the adapter credential file instead.
	UpstreamCredential string `protobuf:"bytes,18,opt,name=upstream_credential,json=upstreamCredential,proto3" json:"upstream_credential,omitempty"`
	// issued_at is the lease-mint instant. The §4.9 expiry rule computes
	// expires_at as issued_at + min(leaseTTLSeconds, providerMaxTTL); the
	// gateway records it so the lease's wall-clock duration is auditable
	// and feeds the §16.1 lenny_credential_lease_duration_seconds
	// histogram. spec: §4.9 line 1145.
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialLease) Reset() {
	*x = CredentialLease{}
	mi := &file_lenny_tokenservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialLease) ProtoMessage() {}

func (x *CredentialLease) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_tokenservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialLease.ProtoReflect.Descriptor instead.
func (*CredentialLease) Descriptor() ([]byte, []int) {
	return file_lenny_tokenservice_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialLease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CredentialLease) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CredentialLease) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CredentialLease) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CredentialLease) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *CredentialLease) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *CredentialLease) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CredentialLease) GetCredentialRef() string {
	if x != nil {
		return x.CredentialRef
	}
	return ""
}

func (x *CredentialLease) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *CredentialLease) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CredentialLease) GetRenewBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.RenewBefore
	}
	return nil
}

func (x *CredentialLease) GetFallbackAllowed() bool {
	if x != nil {
		return x.FallbackAllowed
	}
	return false
}

func (x *CredentialLease) GetSpiffeUri() string {
	if x != nil {
		return x.SpiffeUri
	}
	return ""
}

func (x *CredentialLease) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *CredentialLease) GetProxyDialect() string {
	if x != nil {
		return x.ProxyDialect
	}
	return ""
}

func (x *CredentialLease) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *CredentialLease) GetUpstreamModel() string {
	if x != nil {
		return x.UpstreamModel
	}
	return ""
}

func (x *CredentialLease) GetUpstreamCredential() string {
	if x != nil {
		return x.UpstreamCredential
	}
	return ""
}

func (x *CredentialLease) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

var File_lenny_tokenservice_proto protoreflect.FileDescriptor

const file_lenny_tokenservice_proto_rawDesc = "" +
	"\n" +
	"\x18lenny-tokenservice.proto\x12\x15lenny.tokenservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\x18AssignCredentialsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12$\n" +
	"\x0epod_spiffe_uri\x18\x04 \x01(\tR\fpodSpiffeUri\x12\x19\n" +
	"\bpool_ids\x18\x05 \x03(\tR\apoolIds\"\xd4\x01\n" +
	"\x19AssignCredentialsResponse\x12T\n" +
	"\x06leases\x18\x01 \x03(\v2<.lenny.tokenservice.v1.AssignCredentialsResponse.LeasesEntryR\x06leases\x1aa\n" +
	"\vLeasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.lenny.tokenservice.v1.CredentialLeaseR\x05value:\x028\x01\"R\n" +
	"\x18RotateCredentialsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\"Y\n" +
	"\x19RotateCredentialsResponse\x12<\n" +
	"\x05lease\x18\x01 \x01(\v2&.lenny.tokenservice.v1.CredentialLeaseR\x05lease\"j\n" +
	"\x18RevokeCredentialsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x1b\n" +
	"\x19RevokeCredentialsResponse\"\xde\x05\n" +
	"\x0fCredentialLease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x17\n" +
	"\apool_id\x18\x05 \x01(\tR\x06poolId\x12#\n" +
	"\rcredential_id\x18\x06 \x01(\tR\fcredentialId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12%\n" +
	"\x0ecredential_ref\x18\b \x01(\tR\rcredentialRef\x12#\n" +
	"\rdelivery_mode\x18\t \x01(\tR\fdeliveryMode\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\frenew_before\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vrenewBefore\x12)\n" +
	"\x10fallback_allowed\x18\f \x01(\bR\x0ffallbackAllowed\x12\x1d\n" +
	"\n" +
	"spiffe_uri\x18\r \x01(\tR\tspiffeUri\x12\x1b\n" +
	"\tproxy_url\x18\x0e \x01(\tR\bproxyUrl\x12#\n" +
	"\rproxy_dialect\x18\x0f \x01(\tR\fproxyDialect\x12\x1f\n" +
	"\vlease_token\x18\x10 \x01(\tR\n" +
	"leaseToken\x12%\n" +
	"\x0eupstream_model\x18\x11 \x01(\tR\rupstreamModel\x12/\n" +
	"\x13upstream_credential\x18\x12 \x01(\tR\x12upstreamCredential\x127\n" +
	"\tissued_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt2\xfc\x02\n" +
	"\fTokenService\x12x\n" +
	"\x11AssignCredentials\x12/.lenny.tokenservice.v1.AssignCredentialsRequest\x1a0.lenny.tokenservice.v1.AssignCredentialsResponse\"\x00\x12x\n" +
	"\x11RotateCredentials\x12/.lenny.tokenservice.v1.RotateCredentialsRequest\x1a0.lenny.tokenservice.v1.RotateCredentialsResponse\"\x00\x12x\n" +
	"\x11RevokeCredentials\x12/.lenny.tokenservice.v1.RevokeCredentialsRequest\x1a0.lenny.tokenservice.v1.RevokeCredentialsResponse\"\x00BEZCgithub.com/lennylabs/lenny/pkg/proto/tokenservice/v1;tokenservicev1b\x06proto3"

var (
	file_lenny_tokenservice_proto_rawDescOnce sync.Once
	file_lenny_tokenservice_proto_rawDescData []byte
)

func file_lenny_tokenservice_proto_rawDescGZIP() []byte {
	file_lenny_tokenservice_proto_rawDescOnce.Do(func() {
		file_lenny_tokenservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lenny_tokenservice_proto_rawDesc), len(file_lenny_tokenservice_proto_rawDesc)))
	})
	return file_lenny_tokenservice_proto_rawDescData
}

var file_lenny_tokenservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lenny_tokenservice_proto_goTypes = []any{
	(*AssignCredentialsRequest)(nil),  // 0: lenny.tokenservice.v1.AssignCredentialsRequest
	(*AssignCredentialsResponse)(nil), // 1: lenny.tokenservice.v1.AssignCredentialsResponse
	(*RotateCredentialsRequest)(nil),  // 2: lenny.tokenservice.v1.RotateCredentialsRequest
	(*RotateCredentialsResponse)(nil), // 3: lenny.tokenservice.v1.RotateCredentialsResponse
	(*RevokeCredentialsRequest)(nil),  // 4: lenny.tokenservice.v1.RevokeCredentialsRequest
	(*RevokeCredentialsResponse)(nil), // 5: lenny.tokenservice.v1.RevokeCredentialsResponse
	(*CredentialLease)(nil),           // 6: lenny.tokenservice.v1.CredentialLease
	nil,                               // 7: lenny.tokenservice.v1.AssignCredentialsResponse.LeasesEntry
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_lenny_tokenservice_proto_depIdxs = []int32{
	7, // 0: lenny.tokenservice.v1.AssignCredentialsResponse.leases:type_name -> lenny.tokenservice.v1.AssignCredentialsResponse.LeasesEntry
	6, // 1: lenny.tokenservice.v1.RotateCredentialsResponse.lease:type_name -> lenny.tokenservice.v1.CredentialLease
	8, // 2: lenny.tokenservice.v1.CredentialLease.expires_at:type_name -> google.protobuf.Timestamp
	8, // 3: lenny.tokenservice.v1.CredentialLease.renew_before:type_name -> google.protobuf.Timestamp
	8, // 4: lenny.tokenservice.v1.CredentialLease.issued_at:type_name -> google.protobuf.Timestamp
	6, // 5: lenny.tokenservice.v1.AssignCredentialsResponse.LeasesEntry.value:type_name -> lenny.tokenservice.v1.CredentialLease
	0, // 6: lenny.tokenservice.v1.TokenService.AssignCredentials:input_type -> lenny.tokenservice.v1.AssignCredentialsRequest
	2, // 7: lenny.tokenservice.v1.TokenService.RotateCredentials:input_type -> lenny.tokenservice.v1.RotateCredentialsRequest
	4, // 8: lenny.tokenservice.v1.TokenService.RevokeCredentials:input_type -> lenny.tokenservice.v1.RevokeCredentialsRequest
	1, // 9: lenny.tokenservice.v1.TokenService.AssignCredentials:output_type -> lenny.tokenservice.v1.AssignCredentialsResponse
	3, // 10: lenny.tokenservice.v1.TokenService.RotateCredentials:output_type -> lenny.tokenservice.v1.RotateCredentialsResponse
	5, // 11: lenny.tokenservice.v1.TokenService.RevokeCredentials:output_type -> lenny.tokenservice.v1.RevokeCredentialsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_lenny_tokenservice_proto_init() }
func file_lenny_tokenservice_proto_init() {
	if File_lenny_tokenservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lenny_tokenservice_proto_rawDesc), len(file_lenny_tokenservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lenny_tokenservice_proto_goTypes,
		DependencyIndexes: file_lenny_tokenservice_proto_depIdxs,
		MessageInfos:      file_lenny_tokenservice_proto_msgTypes,
	}.Build()
	File_lenny_tokenservice_proto = out.File
	file_lenny_tokenservice_proto_goTypes = nil
	file_lenny_tokenservice_proto_depIdxs = nil
}
