// SPDX-License-Identifier: MIT

package ocsf

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// MappingSchemaVersion is the audit-event schema version the OCSF
// mapping mirror is published under. It matches the audit_log
// `event_schema_version` column default ('v1', migrations/0001) so the
// schemas/ocsf-mapping.yaml mirror and the schemas/audit-events/v1.json
// registry name the same version.
//
// spec: §11.7 line 365 ("schema-version registry as schemas/audit-events/v*.json").
const MappingSchemaVersion = "v1"

// CatalogEntry is one row of the §11.7 event-type → OCSF class/activity
// catalog in a serialization-friendly form. The generator emits the
// committed schemas/ocsf-mapping.yaml mirror from Catalog() so external
// verifiers can consume the mapping without reading Go source.
//
// spec: §11.7 line 414 ("The full mapping is maintained in
// schemas/ocsf-mapping.yaml ... regenerated in CI from Lenny's
// event-type catalog").
type CatalogEntry struct {
	// EventType is the exact event type for an exact-match row, or the
	// namespace prefix for a prefix-match row.
	EventType string `yaml:"event_type"`
	// Match is "exact" or "prefix".
	Match string `yaml:"match"`
	// ClassUID / ClassName are the OCSF class the event maps to.
	ClassUID  int    `yaml:"class_uid"`
	ClassName string `yaml:"class_name"`
	// CategoryUID / CategoryName are the OCSF category the class sits in.
	CategoryUID  int    `yaml:"category_uid"`
	CategoryName string `yaml:"category_name"`
	// ActivityID / ActivityName are the OCSF activity within the class.
	ActivityID   int    `yaml:"activity_id"`
	ActivityName string `yaml:"activity_name"`
}

// ClassName returns the OCSF class name for a class_uid, or "Unknown"
// for an unrecognized value.
func ClassName(classUID int) string {
	switch classUID {
	case ClassAuthentication:
		return "Authentication"
	case ClassAccountChange:
		return "Account Change"
	case ClassEntityManagement:
		return "Entity Management"
	case ClassAPIActivity:
		return "API Activity"
	case ClassFileSystemActivity:
		return "File System Activity"
	case ClassAppSecurityFinding:
		return "Application Security Finding"
	}
	return "Unknown"
}

// CategoryName returns the OCSF category name for a category_uid, or
// "Unknown" for an unrecognized value.
func CategoryName(categoryUID int) string {
	switch categoryUID {
	case categoryFindings:
		return "Findings"
	case categoryIAM:
		return "Identity & Access Management"
	case categoryDiscovery:
		return "Discovery"
	case categoryApplication:
		return "Application Activity"
	}
	return "Unknown"
}

// ActivityName returns the OCSF activity name for an activity_id within
// classUID. The activity_id space overlaps with the class: id 1 is
// "Logon" for Authentication (3002) and "Create" elsewhere, so the
// class is required to disambiguate.
func ActivityName(classUID, activityID int) string {
	switch activityID {
	case ActivityUnknown:
		return "Unknown"
	case ActivityCreate: // == ActivityLogon (1)
		if classUID == ClassAuthentication {
			return "Logon"
		}
		return "Create"
	case ActivityRead:
		return "Read"
	case ActivityUpdate:
		return "Update"
	case ActivityDelete:
		return "Delete"
	case ActivityDisable:
		return "Disable"
	}
	return "Unknown"
}

// entry builds a CatalogEntry from a (name, match, mapping) tuple,
// resolving the human-readable OCSF names.
func entry(name, match string, m ClassMapping) CatalogEntry {
	return CatalogEntry{
		EventType:    name,
		Match:        match,
		ClassUID:     m.ClassUID,
		ClassName:    ClassName(m.ClassUID),
		CategoryUID:  m.CategoryUID,
		CategoryName: CategoryName(m.CategoryUID),
		ActivityID:   m.ActivityID,
		ActivityName: ActivityName(m.ClassUID, m.ActivityID),
	}
}

// Catalog returns every mapping row, exact entries first (sorted by
// event type) and then prefix entries in longest-match declaration
// order. The order is deterministic so the generated YAML mirror is
// stable across regenerations.
func Catalog() []CatalogEntry {
	out := make([]CatalogEntry, 0, len(exactCatalog)+len(prefixCatalog))
	for _, name := range CatalogEventTypes() {
		out = append(out, entry(name, "exact", exactCatalog[name]))
	}
	for _, e := range prefixCatalog {
		out = append(out, entry(e.prefix, "prefix", e.mapping))
	}
	return out
}

// mappingDoc is the top-level structure of schemas/ocsf-mapping.yaml.
type mappingDoc struct {
	SchemaVersion string         `yaml:"schema_version"`
	GeneratedFrom string         `yaml:"generated_from"`
	Mappings      []CatalogEntry `yaml:"mappings"`
}

// mappingHeader is the non-prose comment block prepended to the
// generated YAML so a reader of the file knows it is generated and how
// to regenerate it.
const mappingHeader = `# Generated by cmd/lenny-ocsf-mapping-gen from pkg/audit/ocsf/mapping.go.
# Do not edit by hand. Run: go run ./cmd/lenny-ocsf-mapping-gen
# spec: 11_security-trust-model.md line 414 (OCSF mapping mirror).
`

// MarshalMappingYAML renders the committed schemas/ocsf-mapping.yaml
// mirror from the live Go catalog. The generator binary and the
// in-sync test both call this so the file has a single source of truth.
func MarshalMappingYAML() ([]byte, error) {
	doc := mappingDoc{
		SchemaVersion: MappingSchemaVersion,
		GeneratedFrom: "pkg/audit/ocsf/mapping.go",
		Mappings:      Catalog(),
	}
	var buf bytes.Buffer
	buf.WriteString(mappingHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("encode ocsf mapping yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("close ocsf mapping encoder: %w", err)
	}
	return buf.Bytes(), nil
}
