# SPDX-License-Identifier: MIT
#
# Lenny test infrastructure Makefile.
#
# This Makefile is a thin convenience layer around `go build`,
# `go test`, and `lenny-test`. The harness (cmd/lenny-test) is the
# single source of truth for what runs and in what order; targets
# here exist so contributors don't have to memorize the harness
# invocation for the common cases. See TESTING.md §6 for the full
# command surface.
#
# Targets that depend on `lenny-test` first run `install` so the
# binary is on PATH at $(go env GOPATH)/bin.
#
# The contributor dev loop (`make run`) is a forward-looking target;
# it activates once cmd/lenny-dev ships in a later phase. The other
# targets work against the current Phase 0 surface.

.DEFAULT_GOAL := help
GOPATH_BIN := $(shell go env GOPATH)/bin

.PHONY: help
help: ## Print this message
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

.PHONY: build
build: ## Build every cmd/ binary into ./bin
	@mkdir -p bin
	@for d in $$(find cmd -mindepth 1 -name '*.go' -exec dirname {} \; | sort -u); do \
		name=$$(basename $$d); \
		echo "  build $$name"; \
		go build -o bin/$$name ./$$d || exit 1; \
	done

.PHONY: images
images: ## Build container images for the deployable platform binaries
	@for b in lenny-adapter lenny-controller lenny-gateway lenny-ops lenny-webhook lenny-token-service lenny-preflight; do \
		echo "  image $$b"; \
		docker build --build-arg BINARY=$$b -t ghcr.io/lennylabs/$$b:dev . || exit 1; \
	done

.PHONY: runtime-images
runtime-images: ## Build container images for the §4.7 reference runtimes
	@# §4.7 sidecar-model runtimes: a runtime image paired with the
	@# lenny-adapter sidecar image. §4.7 embedded-model runtimes
	@# (echo-embedded) link the adapter and ship as a single image.
	@for r in echo streaming-echo delegation-echo mcp-reference echo-embedded; do \
		echo "  image runtime-$$r"; \
		docker build --build-arg BINARY=runtimes/$$r -t ghcr.io/lennylabs/runtime-$$r:dev . || exit 1; \
	done

# §17.4 Embedded Mode pre-rendered control-plane manifests. The chart is
# rendered to plain manifests at build time so the `lenny` CLI applies
# them through a dynamic client without carrying a Helm SDK. --no-hooks
# excludes every helm.sh/hook-annotated resource (bootstrap, preflight,
# migrate, the post-upgrade CRD-validate and deployment-config-sync Jobs,
# the MinIO-lifecycle Job, and the Redis-cluster hook), which Helm emits
# into template output by default and which a plain server-side apply
# would create as ordinary objects. The recipe and the tier-11 sync check
# (TestEmbeddedManifestsMatchDevProfileRender) MUST stay byte-identical;
# both read EMBEDDED_MANIFEST_HEADER and the same helm invocation.
EMBEDDED_MANIFESTS := pkg/embedded/manifests/manifests.yaml
EMBEDDED_DEV_PROFILE := charts/lenny/presets/dev.yaml
define EMBEDDED_MANIFEST_HEADER
# Code generated by 'make generate' (helm template --no-hooks); DO NOT EDIT.
# Source: charts/lenny rendered under charts/lenny/presets/dev.yaml.
# Regenerate with 'make generate'. The tier-11 sync check
# (TestEmbeddedManifestsMatchDevProfileRender) fails on any drift.
# spec: §17.4 (pre-rendered embedded manifests).
endef
export EMBEDDED_MANIFEST_HEADER

.PHONY: generate
generate: ## Regenerate DeepCopy + CRD manifests + bundled alerting rules + embedded manifests
	@echo "  controller-gen object → pkg/apis DeepCopy"
	@$(GOPATH_BIN)/controller-gen object:headerFile=hack/boilerplate.go.txt paths=./pkg/apis/lenny/v1alpha1/...
	@echo "  controller-gen crd → charts/lenny/crds"
	@$(GOPATH_BIN)/controller-gen crd paths=./pkg/apis/lenny/v1alpha1/... output:crd:dir=charts/lenny/crds
	@echo "  gen-alerting-rules → charts/lenny/files/alerting-rules.yaml"
	@go run ./cmd/gen-alerting-rules
	@echo "  helm template --no-hooks → $(EMBEDDED_MANIFESTS)"
	@mkdir -p $(dir $(EMBEDDED_MANIFESTS))
	@{ printf '%s\n' "$$EMBEDDED_MANIFEST_HEADER"; \
		helm template lenny charts/lenny -f $(EMBEDDED_DEV_PROFILE) --no-hooks; \
	} > $(EMBEDDED_MANIFESTS)

.PHONY: generate-proto
generate-proto: ## Regenerate the gRPC bindings from schemas/*.proto
	@echo "  buf generate → pkg/proto"
	@cd schemas && PATH="$(GOPATH_BIN):$$PATH" buf generate
	@find pkg/proto -name '*.go' | while read -r f; do \
		head -1 "$$f" | grep -q SPDX-License-Identifier || \
		{ printf '// SPDX-License-Identifier: MIT\n\n' | cat - "$$f" > "$$f.tmp" && mv "$$f.tmp" "$$f"; }; \
	done
	@echo "  goimports → pkg/proto"
	@PATH="$(GOPATH_BIN):$$PATH" goimports -w -local github.com/lennylabs/lenny ./pkg/proto

.PHONY: install
install: ## Install lenny-test + lenny-compliance into $(go env GOPATH)/bin
	@echo "  install lenny-test → $(GOPATH_BIN)"
	@go install ./cmd/lenny-test
	@echo "  install lenny-compliance → $(GOPATH_BIN)"
	@go install ./cmd/lenny-compliance

.PHONY: test
test: install ## Run the unit tier (go test ./...)
	@lenny-test --tier unit --output human

.PHONY: pr
pr: install ## Run the pr-fast group (changed-only, fast tiers)
	@lenny-test --group pr-fast --output human

.PHONY: pr-full
pr-full: install ## Run the full pr group (everything that runs on every push)
	@lenny-test --group pr --output human

.PHONY: validate
validate: install ## Run validate-maps and validate-diagnosis
	@lenny-test validate-maps
	@lenny-test validate-diagnosis

.PHONY: lint
lint: install ## Run every Tier 0 static linter
	@lenny-test --tier static --output human

.PHONY: coverage
coverage: install ## Report Go and spec coverage
	@lenny-test coverage --go
	@lenny-test coverage --spec

.PHONY: clean
clean: ## Remove ./bin and the test results directory
	@rm -rf bin tests/results

.PHONY: upgrade
upgrade: ## §10.5 CRD-aware upgrade: preflight, diff/apply CRDs, then helm upgrade. RELEASE= NAMESPACE= VALUES= [NON_INTERACTIVE=true]
	@if [ -z "$(RELEASE)" ] || [ -z "$(VALUES)" ]; then \
		echo "usage: make upgrade RELEASE=<version> VALUES=<values.yaml> [NAMESPACE=<ns>] [NON_INTERACTIVE=true]" >&2; \
		exit 2; \
	fi
	@scripts/lenny-upgrade.sh \
		--release "$(RELEASE)" \
		--values "$(VALUES)" \
		$(if $(NAMESPACE),--namespace "$(NAMESPACE)",) \
		$(if $(filter true,$(NON_INTERACTIVE)),--non-interactive,)

.PHONY: run
run: ## §17.4 Source Mode: gateway + embedded SQLite + local-filesystem artifacts + built-in echo runtime. LENNY_AGENT_BINARY=<path> swaps in a custom runtime binary.
	@mkdir -p bin lenny-data/artifacts
	@echo "  build echo runtime"
	@go build -o bin/echo ./cmd/runtimes/echo
	@echo "  build lenny-gateway"
	@go build -o bin/lenny-gateway ./cmd/lenny-gateway
	@echo "  starting gateway on :8080 (dev mode, echo runtime)"
	@echo "  §17.4 substitutions: embedded SQLite (lenny-data/lenny.db), local-filesystem artifacts (lenny-data/artifacts/), in-memory caches"
	@echo "  POST http://localhost:8080/v1/sessions/start to drive a session;"
	@echo "  GET  http://localhost:8080/healthz for liveness; Ctrl-C to stop."
	@LENNY_AGENT_BINARY="$(LENNY_AGENT_BINARY)" ./bin/lenny-gateway --addr :8080 --dev-mode \
		--sqlite-path ./lenny-data/lenny.db \
		--object-storage-provider filesystem --object-storage-filesystem-root ./lenny-data/artifacts \
		$(if $(LENNY_AGENT_BINARY),,--agent-runtime echo)

.PHONY: compose
compose: ## §17.4 Compose Mode: full local stack (gateway + echo agent + Postgres + Redis + MinIO) via docker compose.
	docker compose up

.PHONY: compose-down
compose-down: ## §17.4 tear down the Compose Mode stack and its volumes.
	docker compose down -v

.PHONY: compose-tls
compose-tls: ## §17.4 credential-testing profile: generate self-signed mTLS material, then start with LENNY_DEV_TLS=true.
	@scripts/dev-certs.sh ./lenny-data/certs
	LENNY_DEV_TLS=true docker compose --profile credentials up

.PHONY: test-smoke
test-smoke: ## §17.4 line 276 Source Mode smoke test: boot the gateway, create an echo session, send a prompt, verify the response.
	@go test -tags smoke -count=1 -timeout 120s -run TestSourceModeSmoke ./tests/tier4_integration/...

ECHO_TARBALL ?= $(CURDIR)/bin/runtime-echo-embedded.tar

.PHONY: echo-embedded-tarball
echo-embedded-tarball: ## Build the echo-embedded image and docker-save it to bin/runtime-echo-embedded.tar, the credential-free pod image the Embedded Mode bring-up imports into the embedded containerd (resolveEchoTarball / LENNY_ECHO_TARBALL).
	@mkdir -p bin
	@echo "  image runtime-echo-embedded"
	@docker build --build-arg BINARY=runtimes/echo-embedded -t ghcr.io/lennylabs/runtime-echo-embedded:dev .
	@echo "  docker save → $(ECHO_TARBALL)"
	@docker save ghcr.io/lennylabs/runtime-echo-embedded:dev -o $(ECHO_TARBALL)

.PHONY: test-smoke-embedded
test-smoke-embedded: echo-embedded-tarball ## §17.4 line 150 Embedded Mode quick-start smoke: lenny up -> session new --runtime echo -> down. Needs LENNY_EMBEDDED_SMOKE=1 on a host with the embedded substrate (Linux, or Docker Desktop on macOS/Windows). Builds and stages the echo tarball first.
	@LENNY_EMBEDDED_SMOKE=$${LENNY_EMBEDDED_SMOKE:-1} LENNY_EMBEDDED_SMOKE_RUNTIME=$${LENNY_EMBEDDED_SMOKE_RUNTIME:-echo} LENNY_ECHO_TARBALL=$${LENNY_ECHO_TARBALL:-$(ECHO_TARBALL)} LENNY_EMBEDDED_UP_TIMEOUT=$${LENNY_EMBEDDED_UP_TIMEOUT:-12m} go test -tags smoke -count=1 -timeout 1500s -run TestEmbeddedModeSmoke ./tests/tier4_integration/...
