// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

// Package v1alpha1 sits under no producer's output set, so the header
// generation declaration is the only disjunct that selects it. Its doc
// comment names the lifecycle channel and the register holds no entry
// for the site, so a run that read the header would abort here.
package v1alpha1

// DeepCopy copies a value.
func DeepCopy() bool { return true }
