// SPDX-License-Identifier: MIT

// Gateway → external interceptor SPI. This is the gRPC contract a
// deployer-supplied RequestInterceptor service implements so the gateway
// can run it inside a phase chain alongside the built-in interceptors.
// External interceptors are invoked the same way Kubernetes admission
// webhooks are: the gateway is the client, the interceptor is the server.
//
// The gateway-facing surface for a pod's adapter is a separate contract
// (lenny-adapter.proto); this proto covers only the §4 RequestInterceptor
// extension point.
//
// See spec/04_system-components.md §4.8 (the RequestInterceptor extension
// point) and spec/08_recursive-delegation.md §8.7 (the PreExportMaterialization
// phase that runs this contract over delegation-exported files).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lenny-interceptor.proto

package interceptorv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestInterceptor_Intercept_FullMethodName = "/lenny.interceptor.v1.RequestInterceptor/Intercept"
)

// RequestInterceptorClient is the client API for RequestInterceptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequestInterceptor is the gRPC service a deployer implements to plug a
// custom policy hook into a gateway phase chain. The gateway connects to
// the configured endpoint and calls Intercept once per request at each
// phase the interceptor is registered for. Any language with gRPC code
// generation can implement it.
//
// An external interceptor runs in the same per-phase chain as the
// built-in interceptors, subject to the same priority ordering and the
// same fail-policy. It must register at a priority above the reserved
// built-in ceiling (priorities 1–100 are reserved) and may not register
// for the PreAuth phase.
type RequestInterceptorClient interface {
	// Intercept evaluates one request at one phase and returns the
	// interceptor's decision. The gateway applies a per-interceptor
	// deadline; a timeout or transport error is resolved by the
	// interceptor's configured fail-policy.
	Intercept(ctx context.Context, in *InterceptRequest, opts ...grpc.CallOption) (*InterceptResponse, error)
}

type requestInterceptorClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestInterceptorClient(cc grpc.ClientConnInterface) RequestInterceptorClient {
	return &requestInterceptorClient{cc}
}

func (c *requestInterceptorClient) Intercept(ctx context.Context, in *InterceptRequest, opts ...grpc.CallOption) (*InterceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterceptResponse)
	err := c.cc.Invoke(ctx, RequestInterceptor_Intercept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestInterceptorServer is the server API for RequestInterceptor service.
// All implementations should embed UnimplementedRequestInterceptorServer
// for forward compatibility.
//
// RequestInterceptor is the gRPC service a deployer implements to plug a
// custom policy hook into a gateway phase chain. The gateway connects to
// the configured endpoint and calls Intercept once per request at each
// phase the interceptor is registered for. Any language with gRPC code
// generation can implement it.
//
// An external interceptor runs in the same per-phase chain as the
// built-in interceptors, subject to the same priority ordering and the
// same fail-policy. It must register at a priority above the reserved
// built-in ceiling (priorities 1–100 are reserved) and may not register
// for the PreAuth phase.
type RequestInterceptorServer interface {
	// Intercept evaluates one request at one phase and returns the
	// interceptor's decision. The gateway applies a per-interceptor
	// deadline; a timeout or transport error is resolved by the
	// interceptor's configured fail-policy.
	Intercept(context.Context, *InterceptRequest) (*InterceptResponse, error)
}

// UnimplementedRequestInterceptorServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestInterceptorServer struct{}

func (UnimplementedRequestInterceptorServer) Intercept(context.Context, *InterceptRequest) (*InterceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Intercept not implemented")
}
func (UnimplementedRequestInterceptorServer) testEmbeddedByValue() {}

// UnsafeRequestInterceptorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestInterceptorServer will
// result in compilation errors.
type UnsafeRequestInterceptorServer interface {
	mustEmbedUnimplementedRequestInterceptorServer()
}

func RegisterRequestInterceptorServer(s grpc.ServiceRegistrar, srv RequestInterceptorServer) {
	// If the following call panics, it indicates UnimplementedRequestInterceptorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestInterceptor_ServiceDesc, srv)
}

func _RequestInterceptor_Intercept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestInterceptorServer).Intercept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestInterceptor_Intercept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestInterceptorServer).Intercept(ctx, req.(*InterceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestInterceptor_ServiceDesc is the grpc.ServiceDesc for RequestInterceptor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestInterceptor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lenny.interceptor.v1.RequestInterceptor",
	HandlerType: (*RequestInterceptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Intercept",
			Handler:    _RequestInterceptor_Intercept_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lenny-interceptor.proto",
}
