// SPDX-License-Identifier: MIT

// Gateway → external interceptor SPI. This is the gRPC contract a
// deployer-supplied RequestInterceptor service implements so the gateway
// can run it inside a phase chain alongside the built-in interceptors.
// External interceptors are invoked the same way Kubernetes admission
// webhooks are: the gateway is the client, the interceptor is the server.
//
// The gateway-facing surface for a pod's adapter is a separate contract
// (lenny-adapter.proto); this proto covers only the §4 RequestInterceptor
// extension point.
//
// See spec/04_system-components.md §4.8 (the RequestInterceptor extension
// point) and spec/08_recursive-delegation.md §8.7 (the PreExportMaterialization
// phase that runs this contract over delegation-exported files).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lenny-interceptor.proto

package interceptorv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action is the interceptor's decision. The §4.8 protobuf definition
// fixes the value names (ALLOW, REJECT, MODIFY) and numbers, so the
// enum-value naming-convention lint rules are suppressed here. The
// values match the in-process interceptor.Action enum in
// pkg/gateway/interceptor.
//
// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
// buf:lint:ignore ENUM_VALUE_PREFIX
type InterceptResponse_Action int32

const (
	// ALLOW passes the request through unchanged.
	InterceptResponse_ALLOW InterceptResponse_Action = 0
	// REJECT blocks the request and short-circuits the chain.
	InterceptResponse_REJECT InterceptResponse_Action = 1
	// MODIFY rewrites the payload; the rewritten bytes are returned in
	// modified_content.
	InterceptResponse_MODIFY InterceptResponse_Action = 2
)

// Enum value maps for InterceptResponse_Action.
var (
	InterceptResponse_Action_name = map[int32]string{
		0: "ALLOW",
		1: "REJECT",
		2: "MODIFY",
	}
	InterceptResponse_Action_value = map[string]int32{
		"ALLOW":  0,
		"REJECT": 1,
		"MODIFY": 2,
	}
)

func (x InterceptResponse_Action) Enum() *InterceptResponse_Action {
	p := new(InterceptResponse_Action)
	*p = x
	return p
}

func (x InterceptResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterceptResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_lenny_interceptor_proto_enumTypes[0].Descriptor()
}

func (InterceptResponse_Action) Type() protoreflect.EnumType {
	return &file_lenny_interceptor_proto_enumTypes[0]
}

func (x InterceptResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterceptResponse_Action.Descriptor instead.
func (InterceptResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_lenny_interceptor_proto_rawDescGZIP(), []int{1, 0}
}

// InterceptRequest is the payload the gateway sends to an external
// interceptor. The field numbers match the §4.8 protobuf definition.
type InterceptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// phase names the gateway interception point, e.g. "PreDelegation",
	// "PreExportMaterialization", or "PostAgentOutput".
	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// session_id is the session the request belongs to.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// tenant_id is the session's tenant.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// content is the phase-dependent payload. For PreDelegation it is the
	// serialized TaskSpec.input; for PreExportMaterialization it is the
	// serialized exported-file record.
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// metadata carries phase-dependent context. For external interceptors
	// (priority > 100) it always includes the authenticated identity
	// populated by AuthEvaluator.
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptRequest) Reset() {
	*x = InterceptRequest{}
	mi := &file_lenny_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptRequest) ProtoMessage() {}

func (x *InterceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptRequest.ProtoReflect.Descriptor instead.
func (*InterceptRequest) Descriptor() ([]byte, []int) {
	return file_lenny_interceptor_proto_rawDescGZIP(), []int{0}
}

func (x *InterceptRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *InterceptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InterceptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InterceptRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InterceptRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InterceptResponse is the interceptor's decision on a request.
type InterceptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action is the decision the gateway applies.
	Action InterceptResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=lenny.interceptor.v1.InterceptResponse_Action" json:"action,omitempty"`
	// reason is the human-readable cause. On REJECT it is logged and
	// returned to the caller.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// modified_content carries the rewritten payload. It is read only when
	// action is MODIFY.
	ModifiedContent []byte `protobuf:"bytes,3,opt,name=modified_content,json=modifiedContent,proto3" json:"modified_content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterceptResponse) Reset() {
	*x = InterceptResponse{}
	mi := &file_lenny_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptResponse) ProtoMessage() {}

func (x *InterceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lenny_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptResponse.ProtoReflect.Descriptor instead.
func (*InterceptResponse) Descriptor() ([]byte, []int) {
	return file_lenny_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *InterceptResponse) GetAction() InterceptResponse_Action {
	if x != nil {
		return x.Action
	}
	return InterceptResponse_ALLOW
}

func (x *InterceptResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InterceptResponse) GetModifiedContent() []byte {
	if x != nil {
		return x.ModifiedContent
	}
	return nil
}

var File_lenny_interceptor_proto protoreflect.FileDescriptor

const file_lenny_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x17lenny-interceptor.proto\x12\x14lenny.interceptor.v1\"\x8d\x02\n" +
	"\x10InterceptRequest\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12P\n" +
	"\bmetadata\x18\x05 \x03(\v24.lenny.interceptor.v1.InterceptRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x11InterceptResponse\x12F\n" +
	"\x06action\x18\x01 \x01(\x0e2..lenny.interceptor.v1.InterceptResponse.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10modified_content\x18\x03 \x01(\fR\x0fmodifiedContent\"+\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\n" +
	"\n" +
	"\x06REJECT\x10\x01\x12\n" +
	"\n" +
	"\x06MODIFY\x10\x022t\n" +
	"\x12RequestInterceptor\x12^\n" +
	"\tIntercept\x12&.lenny.interceptor.v1.InterceptRequest\x1a'.lenny.interceptor.v1.InterceptResponse\"\x00BCZAgithub.com/lennylabs/lenny/pkg/proto/interceptor/v1;interceptorv1b\x06proto3"

var (
	file_lenny_interceptor_proto_rawDescOnce sync.Once
	file_lenny_interceptor_proto_rawDescData []byte
)

func file_lenny_interceptor_proto_rawDescGZIP() []byte {
	file_lenny_interceptor_proto_rawDescOnce.Do(func() {
		file_lenny_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lenny_interceptor_proto_rawDesc), len(file_lenny_interceptor_proto_rawDesc)))
	})
	return file_lenny_interceptor_proto_rawDescData
}

var file_lenny_interceptor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lenny_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lenny_interceptor_proto_goTypes = []any{
	(InterceptResponse_Action)(0), // 0: lenny.interceptor.v1.InterceptResponse.Action
	(*InterceptRequest)(nil),      // 1: lenny.interceptor.v1.InterceptRequest
	(*InterceptResponse)(nil),     // 2: lenny.interceptor.v1.InterceptResponse
	nil,                           // 3: lenny.interceptor.v1.InterceptRequest.MetadataEntry
}
var file_lenny_interceptor_proto_depIdxs = []int32{
	3, // 0: lenny.interceptor.v1.InterceptRequest.metadata:type_name -> lenny.interceptor.v1.InterceptRequest.MetadataEntry
	0, // 1: lenny.interceptor.v1.InterceptResponse.action:type_name -> lenny.interceptor.v1.InterceptResponse.Action
	1, // 2: lenny.interceptor.v1.RequestInterceptor.Intercept:input_type -> lenny.interceptor.v1.InterceptRequest
	2, // 3: lenny.interceptor.v1.RequestInterceptor.Intercept:output_type -> lenny.interceptor.v1.InterceptResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lenny_interceptor_proto_init() }
func file_lenny_interceptor_proto_init() {
	if File_lenny_interceptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lenny_interceptor_proto_rawDesc), len(file_lenny_interceptor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lenny_interceptor_proto_goTypes,
		DependencyIndexes: file_lenny_interceptor_proto_depIdxs,
		EnumInfos:         file_lenny_interceptor_proto_enumTypes,
		MessageInfos:      file_lenny_interceptor_proto_msgTypes,
	}.Build()
	File_lenny_interceptor_proto = out.File
	file_lenny_interceptor_proto_goTypes = nil
	file_lenny_interceptor_proto_depIdxs = nil
}
