// SPDX-License-Identifier: MIT

package loadgen

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Baseline is a stored fingerprint of a tier-7a scenario's
// historical performance. Generated by `LENNY_TIER7A_UPDATE_BASELINES=1
// LENNY_TIER7A_BASELINE_DIR=<dir>` and consumed by subsequent runs
// in `LENNY_TIER7A_BASELINE_DIR=<dir>` mode.
type Baseline struct {
	Scenario   string             `json:"scenario"`
	RecordedAt time.Time          `json:"recorded_at"`
	Profile    profileSummaryJSON `json:"profile"`
	Iterations int64              `json:"iterations"`
	Throughput float64            `json:"throughput_per_sec"`
	ErrorRate  float64            `json:"error_rate"`
	Latency    HistogramSnapshot  `json:"latency_seconds"`
}

// BaselineFromResult builds a Baseline from a Result.
func BaselineFromResult(scenario string, profile Profile, r *Result) *Baseline {
	if r == nil {
		return nil
	}
	return &Baseline{
		Scenario:   scenario,
		RecordedAt: time.Now().UTC(),
		Profile:    encodeProfile(profile),
		Iterations: r.Iterations,
		Throughput: r.Throughput,
		ErrorRate:  r.ErrorRate,
		Latency:    r.Latency,
	}
}

// BaselineStore is the read/write surface for stored baselines.
type BaselineStore interface {
	Load(scenario string) (*Baseline, bool, error)
	Save(b *Baseline) error
}

// FileBaselineStore stores one JSON file per scenario under Dir:
// <Dir>/<scenario>.json.
type FileBaselineStore struct {
	Dir string
}

// Load reads the baseline for scenario, or returns ok=false when the
// file does not exist.
func (s *FileBaselineStore) Load(scenario string) (*Baseline, bool, error) {
	path := s.path(scenario)
	body, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	var b Baseline
	if err := json.Unmarshal(body, &b); err != nil {
		return nil, false, fmt.Errorf("parse %s: %w", path, err)
	}
	return &b, true, nil
}

// Save writes the baseline.
func (s *FileBaselineStore) Save(b *Baseline) error {
	if b == nil {
		return errors.New("loadgen.FileBaselineStore.Save: nil baseline")
	}
	if err := os.MkdirAll(s.Dir, 0o755); err != nil {
		return err
	}
	body, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(s.path(b.Scenario), body, 0o644)
}

func (s *FileBaselineStore) path(scenario string) string {
	safe := strings.ReplaceAll(scenario, "/", "_")
	return filepath.Join(s.Dir, safe+".json")
}

// Threshold defines acceptable regression for a baseline comparison.
// Zero fields disable the corresponding check.
type Threshold struct {
	// ThroughputDropPct fails when the current throughput is more
	// than this percentage below the baseline. 15 means -15%.
	ThroughputDropPct float64
	// LatencyP95RisePct fails when current P95 rises more than this
	// percentage above the baseline.
	LatencyP95RisePct float64
	// LatencyP99RisePct fails when current P99 rises more than this
	// percentage above the baseline.
	LatencyP99RisePct float64
	// ErrorRateAbs is an absolute ceiling. 0.01 means fail when
	// current error rate > 1% regardless of baseline.
	ErrorRateAbs float64
}

// Regression is a single Threshold violation.
type Regression struct {
	Metric string
	Got    float64
	Want   float64
	Note   string
}

func (r Regression) String() string {
	return fmt.Sprintf("%s: got %.6f, threshold %.6f (%s)", r.Metric, r.Got, r.Want, r.Note)
}

// CompareToBaseline returns the list of Threshold violations the
// current Result exhibits against base. An empty slice means the
// run is within budget.
func CompareToBaseline(current *Result, base *Baseline, t Threshold) []Regression {
	if current == nil || base == nil {
		return nil
	}
	var out []Regression
	if t.ThroughputDropPct > 0 && base.Throughput > 0 {
		floor := base.Throughput * (1 - t.ThroughputDropPct/100)
		if current.Throughput < floor {
			out = append(out, Regression{
				Metric: "throughput_per_sec",
				Got:    current.Throughput,
				Want:   floor,
				Note:   fmt.Sprintf("baseline=%.2f, threshold=-%.1f%%", base.Throughput, t.ThroughputDropPct),
			})
		}
	}
	if t.LatencyP95RisePct > 0 && base.Latency.P95 > 0 {
		ceiling := base.Latency.P95 * (1 + t.LatencyP95RisePct/100)
		if current.Latency.P95 > ceiling {
			out = append(out, Regression{
				Metric: "latency_p95_seconds",
				Got:    current.Latency.P95,
				Want:   ceiling,
				Note:   fmt.Sprintf("baseline=%.6f, threshold=+%.1f%%", base.Latency.P95, t.LatencyP95RisePct),
			})
		}
	}
	if t.LatencyP99RisePct > 0 && base.Latency.P99 > 0 {
		ceiling := base.Latency.P99 * (1 + t.LatencyP99RisePct/100)
		if current.Latency.P99 > ceiling {
			out = append(out, Regression{
				Metric: "latency_p99_seconds",
				Got:    current.Latency.P99,
				Want:   ceiling,
				Note:   fmt.Sprintf("baseline=%.6f, threshold=+%.1f%%", base.Latency.P99, t.LatencyP99RisePct),
			})
		}
	}
	if t.ErrorRateAbs > 0 && current.ErrorRate > t.ErrorRateAbs {
		out = append(out, Regression{
			Metric: "error_rate",
			Got:    current.ErrorRate,
			Want:   t.ErrorRateAbs,
			Note:   "absolute ceiling",
		})
	}
	return out
}
