// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schemas/lenny-adapter.proto

// Package adapterv1 is producer output of the proto generation and it
// carries a generation declaration in its header. Its doc comment names
// the lifecycle channel, mirrored from the comment its source proto
// carries, and the register holds no entry for the site: the file leaves
// the population through the regeneration of that source rather than
// through a write here, and an ordinary carrier in the same run is still
// substituted.
package adapterv1

// Ack reports delivery over the control channel this stub mirrors.
func Ack() bool { return true }
