// SPDX-License-Identifier: MIT

package stack

import (
	"testing"
	"testing/fstest"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/lennylabs/lenny/pkg/embedded/manifests"
)

// TestApplyOrderSequencesPrerequisitesFirst_spec_17_4 pins the §17.4 apply
// order: namespaces, CRDs, RBAC, ConfigMaps/Secrets, Services, then
// Deployments, with every other kind between the Services and the
// Deployments. The order matters because a Deployment whose pods reference a
// missing namespace, ConfigMap, or Service would fail to start, so the
// applier must place the prerequisites first.
//
// spec: §17.4 (in-cluster control plane apply order).
func TestApplyOrderSequencesPrerequisitesFirst_spec_17_4(t *testing.T) {
	// Each kind paired with the kind that must apply no earlier than it.
	type rank struct {
		kind string
		want int
	}
	ranks := []rank{
		{"Namespace", 0},
		{"CustomResourceDefinition", 1},
		{"ServiceAccount", 2},
		{"Role", 2},
		{"RoleBinding", 2},
		{"ClusterRole", 2},
		{"ClusterRoleBinding", 2},
		{"ConfigMap", 3},
		{"Secret", 3},
		{"Service", 4},
		{"RuntimeClass", 5}, // an unenumerated kind lands between Services and Deployments
		{"Deployment", 6},
	}
	for _, r := range ranks {
		if got := applyOrder(r.kind); got != r.want {
			t.Errorf("applyOrder(%q) = %d, want %d", r.kind, got, r.want)
		}
	}

	// The deployment must rank strictly after every prerequisite kind so the
	// sort never schedules a workload ahead of the objects its pods reference.
	dep := applyOrder("Deployment")
	for _, before := range []string{"Namespace", "CustomResourceDefinition", "ServiceAccount", "ConfigMap", "Secret", "Service"} {
		if applyOrder(before) >= dep {
			t.Errorf("applyOrder(%q) = %d is not before Deployment = %d", before, applyOrder(before), dep)
		}
	}
}

// TestSortByApplyOrderIsStableWithinPhase_spec_17_4 asserts the sort places
// the namespace first and the Deployment last while keeping two objects in
// the same apply phase (two Services) in their original render order, so the
// chart's within-phase ordering survives the sort.
//
// spec: §17.4 (in-cluster control plane apply order).
func TestSortByApplyOrderIsStableWithinPhase_spec_17_4(t *testing.T) {
	objs := []unstructured.Unstructured{
		newObj("apps/v1", "Deployment", "lenny-gateway"),
		newObj("v1", "Service", "svc-a"),
		newObj("v1", "Namespace", "lenny-agents"),
		newObj("v1", "Service", "svc-b"),
		newObj("v1", "ConfigMap", "cfg"),
	}
	sortByApplyOrder(objs)

	gotKinds := make([]string, len(objs))
	for i, o := range objs {
		gotKinds[i] = o.GetKind()
	}
	wantKinds := []string{"Namespace", "ConfigMap", "Service", "Service", "Deployment"}
	for i := range wantKinds {
		if gotKinds[i] != wantKinds[i] {
			t.Fatalf("sorted kinds = %v, want %v", gotKinds, wantKinds)
		}
	}
	// The two Services must keep their render order (svc-a before svc-b).
	if objs[2].GetName() != "svc-a" || objs[3].GetName() != "svc-b" {
		t.Errorf("within-phase Service order = [%s %s], want [svc-a svc-b]", objs[2].GetName(), objs[3].GetName())
	}
}

// TestDecodeManifestsSplitsDocumentsAndSkipsCommentsAndEmpties_spec_17_4
// asserts the decoder splits a multi-document stream on the document
// separator, decodes each kind-bearing document, and skips the
// comment-only generated header and empty documents, so the applier sees
// exactly the renderable objects.
//
// spec: §17.4 (pre-rendered embedded manifests).
func TestDecodeManifestsSplitsDocumentsAndSkipsCommentsAndEmpties_spec_17_4(t *testing.T) {
	stream := []byte(`# generated by make generate
# do not edit
---
apiVersion: v1
kind: Namespace
metadata:
  name: lenny-agents
---
# a stray comment document
---
apiVersion: v1
kind: Service
metadata:
  name: lenny-gateway
  namespace: lenny-agents
---
`)
	fsys := fstest.MapFS{
		"manifests.yaml": &fstest.MapFile{Data: stream},
		"README.md":      &fstest.MapFile{Data: []byte("not yaml")},
	}
	objs, err := decodeManifests(fsys)
	if err != nil {
		t.Fatalf("decodeManifests: %v", err)
	}
	if len(objs) != 2 {
		t.Fatalf("decoded %d objects, want 2 (Namespace, Service); got %v", len(objs), kinds(objs))
	}
	if objs[0].GetKind() != "Namespace" || objs[0].GetName() != "lenny-agents" {
		t.Errorf("first object = %s/%s, want Namespace/lenny-agents", objs[0].GetKind(), objs[0].GetName())
	}
	if objs[1].GetKind() != "Service" || objs[1].GetName() != "lenny-gateway" {
		t.Errorf("second object = %s/%s, want Service/lenny-gateway", objs[1].GetKind(), objs[1].GetName())
	}
}

// TestDecodeManifestsRejectsMalformedDocument_spec_17_4 asserts a YAML
// document that does not decode surfaces an error naming the source file
// rather than being silently dropped, so a corrupt embedded render fails the
// bring-up loudly.
//
// spec: §17.4 (pre-rendered embedded manifests).
func TestDecodeManifestsRejectsMalformedDocument_spec_17_4(t *testing.T) {
	fsys := fstest.MapFS{
		"manifests.yaml": &fstest.MapFile{Data: []byte("kind: [unterminated")},
	}
	if _, err := decodeManifests(fsys); err == nil {
		t.Fatal("decodeManifests accepted a malformed document, want a decode error")
	}
}

// TestEmbeddedManifestSetDecodes_spec_17_4 asserts the real embedded render
// (the S3 `make generate` output) decodes to the §17.4 control-plane objects:
// the gateway, controller, and lenny-ops Deployments, and the gateway
// NodePort Service. This guards the decoder against the actual embedded
// bytes rather than a synthetic fixture, so a render that the decoder cannot
// parse fails here rather than at bring-up.
//
// spec: §17.4 (in-cluster control plane).
func TestEmbeddedManifestSetDecodes_spec_17_4(t *testing.T) {
	objs, err := decodeManifests(manifests.FS)
	if err != nil {
		t.Fatalf("decode embedded manifest set: %v", err)
	}
	deployments := map[string]bool{}
	services := map[string]bool{}
	for _, o := range objs {
		switch o.GetKind() {
		case "Deployment":
			deployments[o.GetName()] = true
		case "Service":
			services[o.GetName()] = true
		}
	}
	for _, want := range []string{"lenny-gateway", "lenny-controller", "lenny-ops"} {
		if !deployments[want] {
			t.Errorf("embedded manifest set missing the %q Deployment", want)
		}
	}
	if !services["lenny-gateway"] {
		t.Error("embedded manifest set missing the lenny-gateway Service")
	}
}

// newObj builds a minimal Unstructured carrying apiVersion, kind, and name.
func newObj(apiVersion, kind, name string) unstructured.Unstructured {
	return unstructured.Unstructured{Object: map[string]any{
		"apiVersion": apiVersion,
		"kind":       kind,
		"metadata":   map[string]any{"name": name},
	}}
}

// kinds projects the kind of each decoded object for a failure message.
func kinds(objs []unstructured.Unstructured) []string {
	out := make([]string, len(objs))
	for i, o := range objs {
		out[i] = o.GetKind()
	}
	return out
}
