#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# scripts/cloud/azure/render-values.sh — emit a Helm values overlay
# pointing the Lenny chart at the ACR-hosted images and the
# Terraform-emitted Azure resources.
#
# Mirrors scripts/cloud/aws/render-values.sh. The overlay defaults
# the gateway at the in-cluster lenny-postgres / lenny-redis fixtures,
# and routes through Azure Database for PostgreSQL Flexible Server +
# Azure Cache for Redis when LENNY_POSTGRES_DSN / LENNY_REDIS_URL are
# set (the tier-7 cloud-load path composes these from Key Vault
# secrets emitted by managed-services.tf).
#
# Required environment:
#
#   ACR_REGISTRY  The ACR registry host, e.g. lennye2e.azurecr.io.
#
# Optional environment:
#
#   IMAGE_TAG                              Tag to reference (default 0.1.0).
#   LENNY_POSTGRES_DSN                     Override the in-cluster default.
#   LENNY_REDIS_URL                        Override the in-cluster default.
#   LENNY_AZURE_WORKLOAD_IDENTITY_CLIENT_ID
#                                          Adds the azure.workload.identity
#                                          annotations to the gateway SA.

set -euo pipefail

if [[ -z "${ACR_REGISTRY:-}" ]]; then
  echo "render-values.sh: ACR_REGISTRY is required" >&2
  exit 2
fi

TAG="${IMAGE_TAG:-0.1.0}"
OUT="${1:-/dev/stdout}"
WI_CLIENT_ID="${LENNY_AZURE_WORKLOAD_IDENTITY_CLIENT_ID:-}"

if [[ -n "${WI_CLIENT_ID}" ]]; then
  GATEWAY_SA_BLOCK=$'  serviceAccount:\n    annotations:\n      azure.workload.identity/client-id: "'"${WI_CLIENT_ID}"'"\n  podAnnotations:\n    azure.workload.identity/use: "true"'
else
  GATEWAY_SA_BLOCK=""
fi

cat > "${OUT}" <<YAML
# SPDX-License-Identifier: MIT
#
# Generated by scripts/cloud/azure/render-values.sh. Overrides the
# chart's default ghcr.io image registry with the per-release ACR,
# and points the gateway / artifact store at the Terraform-provisioned
# Azure resources. Re-render between runs; do not check in.

global:
  devMode: true

controller:
  image:
    repository: ${ACR_REGISTRY}/lenny-controller
    tag: "${TAG}"
    pullPolicy: IfNotPresent
  adapterImage: ${ACR_REGISTRY}/lenny-adapter:${TAG}

admissionWebhooks:
  image:
    repository: ${ACR_REGISTRY}/lenny-webhook
    tag: "${TAG}"
    pullPolicy: IfNotPresent

tokenService:
  image:
    repository: ${ACR_REGISTRY}/lenny-token-service
    tag: "${TAG}"
    pullPolicy: IfNotPresent

gateway:
  image:
    repository: ${ACR_REGISTRY}/lenny-gateway
    tag: "${TAG}"
    pullPolicy: IfNotPresent
${GATEWAY_SA_BLOCK}

observability:
  otlpEndpoint: "http://adot-collector.lenny-system.svc:4317"

billing:
  sink: "postgres"

ops:
  image:
    repository: ${ACR_REGISTRY}/lenny-ops
    tag: "${TAG}"
    pullPolicy: IfNotPresent

preflight:
  image:
    repository: ${ACR_REGISTRY}/lenny-preflight
    tag: "${TAG}"
    pullPolicy: IfNotPresent

backups:
  image:
    repository: ${ACR_REGISTRY}/lenny-backup
    tag: "${TAG}"
    pullPolicy: IfNotPresent

bootstrap:
  image:
    repository: ${ACR_REGISTRY}/lenny-ctl
    tag: "${TAG}"
    pullPolicy: IfNotPresent

postgres:
  dsn: "${LENNY_POSTGRES_DSN:-postgres://lenny:lenny@lenny-postgres.lenny-system.svc:5432/lenny?sslmode=disable}"
  # When the gateway routes to a managed Postgres, the chart's
  # default-deny NetworkPolicy blocks the external connection
  # unless a CIDR egress rule is added. Empty default keeps the rule
  # absent on the in-cluster-fixture path. Tier-7 cloud-load on
  # Azure exports POSTGRES_GATEWAY_EGRESS_CIDR=0.0.0.0/0 — Flexible
  # Server is reached over the public Internet (firewalled to
  # AllowAllAzureIps), so the egress is bound per port, not by IP.
  gatewayEgressCIDR: "${POSTGRES_GATEWAY_EGRESS_CIDR:-}"

redis:
  url: "${LENNY_REDIS_URL:-redis://lenny-redis.lenny-system.svc:6379}"
  gatewayEgressCIDR: "${REDIS_GATEWAY_EGRESS_CIDR:-}"
  gatewayEgressPort: ${REDIS_GATEWAY_EGRESS_PORT:-6380}
YAML

if [[ "${OUT}" != "/dev/stdout" ]]; then
  echo "render-values.sh: wrote ${OUT}" >&2
fi
