// SPDX-License-Identifier: MIT

// Command gen-alerting-rules renders the §16.5 alert catalog from the
// shared pkg/alerting/rules package into the YAML fragment the Helm
// chart bundles and into the docs/alerting/ reference set.
//
// §16.9 and §25.13 require the chart's PrometheusRule to be generated
// from the single pkg/alerting/rules source so the rendered manifest
// cannot drift from the gateway's in-process alert evaluator. The
// generator is that build step. §25.13 line 4720 also requires the
// catalog to be rendered into docs/alerting/rules.yaml for deployers
// using non-Prometheus stacks (Datadog, Grafana Cloud, Victoria
// Metrics, etc.), and §25.13 line 4804 requires a severity → routing
// recommendation page in docs/alerting/routing-recommendations.md.
//
// Usage:
//
//	gen-alerting-rules                Write all generated artefacts.
//	gen-alerting-rules -o <path>      Write the chart fragment only,
//	                                  to the supplied path.
//	gen-alerting-rules -check         Exit non-zero if any committed
//	                                  artefact is stale (no write).
//
// The Makefile `generate` target runs it; the alerting-rules
// cross-check test runs it with -check so a stale fragment fails CI.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/lennylabs/lenny/pkg/alerting/rules"
)

// ruleGroupPrefix is the PrometheusRule group-name prefix. The
// generator splits the catalog into one rule group per §16.5 severity
// ("lenny.critical", "lenny.warning", "lenny.info") so Prometheus can
// evaluate the buckets in parallel rather than serialising the full
// catalog through a single group; see §25.13 line 4822 per-group
// evaluation cost. F-25.13.9.
const ruleGroupPrefix = "lenny"

// chartFragmentPath is the chart-relative path of the bundled fragment.
const chartFragmentPath = "charts/lenny/files/alerting-rules.yaml"

// openSLOFragmentPath is the chart-relative path of the §16.10 OpenSLO
// export fragment. The chart's openslo-configmap.yaml template splices
// it into a ConfigMap, substituting global.deploymentTier for the
// SLOTierPlaceholder the fragment carries.
const openSLOFragmentPath = "charts/lenny/files/openslo.yaml"

// docsOpenSLOPath is the operator-facing OpenSLO reference, rendered
// with a concrete tier1 example tier so deployers translating to an
// OpenSLO tool have a readable starting point (§16.10).
const docsOpenSLOPath = "docs/alerting/openslo.yaml"

// docsRulesPath is the §25.13 line 4720 docs reference: the full rule
// set rendered for deployers translating to non-Prometheus stacks.
const docsRulesPath = "docs/alerting/rules.yaml"

// docsRoutingPath is the §25.13 line 4804 severity → routing
// recommendations page.
const docsRoutingPath = "docs/alerting/routing-recommendations.md"

const chartHeader = "# Code generated by cmd/gen-alerting-rules from the §16.5 catalog in\n" +
	"# pkg/alerting/rules. DO NOT EDIT. Run `make generate` to refresh.\n" +
	"#\n" +
	"# This file is the spec.groups fragment the chart's prometheusrule.yaml\n" +
	"# template splices into a PrometheusRule CRD. Editing the §16.5 alert\n" +
	"# catalog in pkg/alerting/rules and regenerating is the only supported\n" +
	"# way to change these rules.\n"

const docsRulesHeader = "# Code generated by cmd/gen-alerting-rules from the §16.5 catalog in\n" +
	"# pkg/alerting/rules. DO NOT EDIT. Run `make generate` to refresh.\n" +
	"#\n" +
	"# spec: §25.13 line 4720 — the full rule set rendered as a\n" +
	"# Prometheus-compatible YAML reference for deployers translating the\n" +
	"# §16.5 alert catalogue to non-Prometheus stacks (Datadog, Grafana\n" +
	"# Cloud, Victoria Metrics, etc.). The chart bundles\n" +
	"# charts/lenny/files/alerting-rules.yaml in the rendered PrometheusRule\n" +
	"# and ConfigMap manifests; this docs reference is the operator-facing\n" +
	"# canonical form for translation.\n"

const openSLOChartHeader = "# Code generated by cmd/gen-alerting-rules from the §16.5 SLO catalog\n" +
	"# (SLODefinitions) in pkg/alerting/rules. DO NOT EDIT. Run\n" +
	"# `make generate` to refresh.\n" +
	"#\n" +
	"# spec: §16.10 lines 732-736 — the §16.5 latency and availability SLOs\n" +
	"# rendered as OpenSLO v1 SLO/SLI/AlertPolicy documents. The chart's\n" +
	"# openslo-configmap.yaml template splices this fragment into a\n" +
	"# ConfigMap when monitoring.openslo.enabled is set, substituting\n" +
	"# global.deploymentTier for the " + rules.SLOTierPlaceholder + " token below. The\n" +
	"# export is a view of the same SLO catalog the bundled §16.5\n" +
	"# burn-rate alerts derive from.\n"

const openSLODocsHeader = "# Code generated by cmd/gen-alerting-rules from the §16.5 SLO catalog\n" +
	"# (SLODefinitions) in pkg/alerting/rules. DO NOT EDIT. Run\n" +
	"# `make generate` to refresh.\n" +
	"#\n" +
	"# spec: §16.10 lines 732-736 — operator-facing OpenSLO v1 reference,\n" +
	"# rendered with deployment_tier=\"tier1\" as a concrete example. The\n" +
	"# chart fragment charts/lenny/files/openslo.yaml carries a tier\n" +
	"# placeholder the Helm chart substitutes per deployment.\n"

// routingDoc is the §25.13 line 4804 severity → routing recommendation
// page. It is static prose — every release re-renders it from this
// constant so the generator owns the file alongside the rules.
const routingDoc = `<!--
spec: §25.13 line 4804 — severity → routing recommendations for the §16.5
bundled alerting rules. Generated by cmd/gen-alerting-rules from the
constant in cmd/gen-alerting-rules/main.go. DO NOT EDIT; run
` + "`make generate`" + ` to refresh.
-->

# Alertmanager routing recommendations

The chart does not bundle Alertmanager configuration. Routing is
deployer-specific (PagerDuty vs Slack vs OpsGenie vs email, on-call
rotations, per-team routing, severity-based escalation policies), so a
bundled default would either be wrong for most deployers or generic
enough to be useless. Use the recommendations below as a starting
point and adapt them to the deployment's escalation policies.

| Severity   | Recommended routing                                                                                  | Rationale                                                              |
| ---------- | ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| critical | Page on-call (PagerDuty / OpsGenie) immediately; post to ` + "`#lenny-alerts-critical`" + ` Slack channel | Platform-affecting; needs human response within minutes                |
| warning  | Post to ` + "`#lenny-alerts`" + ` Slack channel; page only if unresolved >30 minutes                       | Indicates degradation but the platform is still serving traffic        |
| info     | Log or notification only                                                                              | Informational; no immediate action required                            |

## Example Alertmanager route block

The block matches the bundled rule severity labels. Replace receivers
with the deployer's escalation targets.

` + "```yaml" + `
route:
  receiver: lenny-default
  group_by: [alertname, severity]
  routes:
    - matchers:
        - severity = "critical"
      receiver: lenny-pagerduty
      continue: true
    - matchers:
        - severity = "warning"
      receiver: lenny-slack-warnings
    - matchers:
        - severity = "info"
      receiver: lenny-slack-info

receivers:
  - name: lenny-default
  - name: lenny-pagerduty
    pagerduty_configs:
      - service_key: ${PAGERDUTY_KEY}
  - name: lenny-slack-warnings
    slack_configs:
      - channel: "#lenny-alerts"
        api_url: ${SLACK_WEBHOOK_URL}
  - name: lenny-slack-info
    slack_configs:
      - channel: "#lenny-alerts-info"
        api_url: ${SLACK_WEBHOOK_URL}
` + "```" + `

## See also

- ` + "`docs/alerting/rules.yaml`" + ` — the full §16.5 rule set in
  Prometheus YAML form for translation to non-Prometheus stacks.
- Section 25.13 of the spec for the bundled-rules customisation model
  (` + "`monitoring.alertOverrides`" + `, ` + "`monitoring.alertThresholds`" + `).
- Section 25.7 of the spec for the runbook pointers each rule's
  ` + "`runbook_url`" + ` annotation references.
`

type artifact struct {
	relPath string
	content []byte
}

func main() {
	out := flag.String("o", "", "chart-fragment output path (default: "+chartFragmentPath+" under the repo root)")
	check := flag.Bool("check", false, "verify every committed artefact is current; exit non-zero if any is stale")
	flag.Parse()

	chartFragment, err := renderChartFragment()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}

	root, err := repoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}

	chartPath := *out
	if chartPath == "" {
		chartPath = filepath.Join(root, chartFragmentPath)
	}

	docsRules, err := renderDocsRules()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}

	openSLOFragment, err := renderOpenSLOFragment()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}

	docsOpenSLO, err := renderDocsOpenSLO()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}

	artefacts := []artifact{
		{relPath: chartPath, content: chartFragment},
		{relPath: filepath.Join(root, docsRulesPath), content: docsRules},
		{relPath: filepath.Join(root, docsRoutingPath), content: []byte(routingDoc)},
		{relPath: filepath.Join(root, openSLOFragmentPath), content: openSLOFragment},
		{relPath: filepath.Join(root, docsOpenSLOPath), content: docsOpenSLO},
	}

	if *check {
		stale := false
		for _, a := range artefacts {
			existing, err := os.ReadFile(a.relPath)
			if err != nil {
				fmt.Fprintf(os.Stderr, "gen-alerting-rules: -check: %v\n", err)
				stale = true
				continue
			}
			if !bytes.Equal(existing, a.content) {
				fmt.Fprintf(os.Stderr, "gen-alerting-rules: %s is stale; run `make generate`\n", a.relPath)
				stale = true
			}
		}
		if stale {
			os.Exit(1)
		}
		return
	}

	for _, a := range artefacts {
		if err := os.MkdirAll(filepath.Dir(a.relPath), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(a.relPath, a.content, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
			os.Exit(1)
		}
	}
	fmt.Printf("gen-alerting-rules: rendered %d rules and %d SLOs → %s, %s, %s, %s, %s\n",
		len(rules.Catalog()), len(rules.SLODefinitions()),
		chartPath, docsRulesPath, docsRoutingPath, openSLOFragmentPath, docsOpenSLOPath)
}

// renderChartFragment builds the header-prefixed spec.groups fragment
// the Helm chart splices into the PrometheusRule CRD and the ConfigMap
// rule-file data section.
func renderChartFragment() ([]byte, error) {
	groups, err := rules.RenderRuleGroupsBySeverity(ruleGroupPrefix, rules.Catalog())
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString(chartHeader)
	buf.Write(groups)
	return buf.Bytes(), nil
}

// renderDocsRules builds the docs/alerting/rules.yaml reference. The
// content is identical to the chart fragment but carries a docs-facing
// header pointing operators at the translation use case.
func renderDocsRules() ([]byte, error) {
	groups, err := rules.RenderRuleGroupsBySeverity(ruleGroupPrefix, rules.Catalog())
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString(docsRulesHeader)
	buf.Write(groups)
	return buf.Bytes(), nil
}

// renderOpenSLOFragment builds the §16.10 OpenSLO export the chart
// bundles. It carries the tier placeholder so the chart can substitute
// global.deploymentTier at install time.
func renderOpenSLOFragment() ([]byte, error) {
	docs, err := rules.RenderOpenSLO(rules.OpenSLOService, rules.SLOTierPlaceholder, rules.SLONotificationTargetPlaceholder)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString(openSLOChartHeader)
	buf.Write(docs)
	return buf.Bytes(), nil
}

// renderDocsOpenSLO builds the operator-facing OpenSLO reference with a
// concrete tier1 example so deployers translating to an OpenSLO tool see
// resolved queries rather than the chart's substitution placeholder.
func renderDocsOpenSLO() ([]byte, error) {
	docs, err := rules.RenderOpenSLO(rules.OpenSLOService, "tier1", rules.OpenSLODefaultNotificationTarget)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString(openSLODocsHeader)
	buf.Write(docs)
	return buf.Bytes(), nil
}

// repoRoot walks up from the working directory to the module root.
func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for d := wd; ; {
		if _, err := os.Stat(filepath.Join(d, "go.mod")); err == nil {
			return d, nil
		}
		parent := filepath.Dir(d)
		if parent == d {
			return "", fmt.Errorf("no go.mod found above %s", wd)
		}
		d = parent
	}
}
