// SPDX-License-Identifier: MIT

// Command gen-alerting-rules renders the §16.5 alert catalog from the
// shared pkg/alerting/rules package into the YAML fragment the Helm
// chart bundles.
//
// §16.9 and §25.13 require the chart's PrometheusRule to be generated
// from the single pkg/alerting/rules source so the rendered manifest
// cannot drift from the gateway's in-process alert evaluator. This
// generator is that build step: it writes the spec.groups fragment to
// charts/lenny/files/alerting-rules.yaml, and the chart's
// prometheusrule.yaml template splices the fragment into a
// PrometheusRule CRD wrapped with chart-managed metadata.
//
// Usage:
//
//	gen-alerting-rules                Write the chart's bundled fragment.
//	gen-alerting-rules -o <path>      Write to an explicit path.
//	gen-alerting-rules -check         Exit non-zero if the committed
//	                                  fragment is stale (no write).
//
// The Makefile `generate` target runs it; the alerting-rules
// cross-check test runs it with -check so a stale fragment fails CI.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/lennylabs/lenny/pkg/alerting/rules"
)

// ruleGroupName is the single PrometheusRule group name. It matches
// the group the gateway's in-process evaluator uses so the two
// surfaces share one identifier.
const ruleGroupName = "lenny.rules"

// defaultOutput is the chart-relative path of the bundled fragment.
const defaultOutput = "charts/lenny/files/alerting-rules.yaml"

const header = "# Code generated by cmd/gen-alerting-rules from the §16.5 catalog in\n" +
	"# pkg/alerting/rules. DO NOT EDIT. Run `make generate` to refresh.\n" +
	"#\n" +
	"# This file is the spec.groups fragment the chart's prometheusrule.yaml\n" +
	"# template splices into a PrometheusRule CRD. Editing the §16.5 alert\n" +
	"# catalog in pkg/alerting/rules and regenerating is the only supported\n" +
	"# way to change these rules.\n"

func main() {
	out := flag.String("o", "", "output path (default: "+defaultOutput+" under the repo root)")
	check := flag.Bool("check", false, "verify the committed fragment is current; exit non-zero if stale")
	flag.Parse()

	rendered, err := render()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}

	path := *out
	if path == "" {
		root, err := repoRoot()
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
			os.Exit(1)
		}
		path = filepath.Join(root, defaultOutput)
	}

	if *check {
		existing, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-alerting-rules: -check: %v\n", err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, rendered) {
			fmt.Fprintf(os.Stderr, "gen-alerting-rules: %s is stale; run `make generate`\n", path)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(path, rendered, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-alerting-rules: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen-alerting-rules: wrote %d rules to %s\n", len(rules.Catalog()), path)
}

// render builds the header-prefixed spec.groups fragment.
func render() ([]byte, error) {
	groups, err := rules.RenderRuleGroups(ruleGroupName, rules.Catalog())
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString(header)
	buf.Write(groups)
	return buf.Bytes(), nil
}

// repoRoot walks up from the working directory to the module root.
func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for d := wd; ; {
		if _, err := os.Stat(filepath.Join(d, "go.mod")); err == nil {
			return d, nil
		}
		parent := filepath.Dir(d)
		if parent == d {
			return "", fmt.Errorf("no go.mod found above %s", wd)
		}
		d = parent
	}
}
