// SPDX-License-Identifier: MIT

// Gateway ↔ pod control protocol. This is the gRPC contract the gateway uses
// to drive a pod's adapter sidecar: deliver messages, push credentials,
// interrupt, request checkpoints, and report usage. The adapter ↔ agent
// channel is JSON Lines (see lenny-adapter-jsonl.schema.json); this proto
// covers only the gateway-facing surface.
//
// See spec/15_external-api-surface.md §15.3 and §15.4.
//
// Phase 1 ships the service skeleton and the canonical message types.
// Field shapes for individual RPCs are deliberately conservative: Phase 2
// implementation fleshes them out and `buf breaking` catches incompatible
// changes against this baseline.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lenny-adapter.proto

package adapterv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Adapter_PrepareWorkspace_FullMethodName            = "/lenny.adapter.v1.Adapter/PrepareWorkspace"
	Adapter_FinalizeWorkspace_FullMethodName           = "/lenny.adapter.v1.Adapter/FinalizeWorkspace"
	Adapter_RunSetup_FullMethodName                    = "/lenny.adapter.v1.Adapter/RunSetup"
	Adapter_StartSession_FullMethodName                = "/lenny.adapter.v1.Adapter/StartSession"
	Adapter_ConfigureWorkspace_FullMethodName          = "/lenny.adapter.v1.Adapter/ConfigureWorkspace"
	Adapter_SendMessage_FullMethodName                 = "/lenny.adapter.v1.Adapter/SendMessage"
	Adapter_Attach_FullMethodName                      = "/lenny.adapter.v1.Adapter/Attach"
	Adapter_AssignCredentials_FullMethodName           = "/lenny.adapter.v1.Adapter/AssignCredentials"
	Adapter_RotateCredentials_FullMethodName           = "/lenny.adapter.v1.Adapter/RotateCredentials"
	Adapter_RevokeCredentials_FullMethodName           = "/lenny.adapter.v1.Adapter/RevokeCredentials"
	Adapter_Interrupt_FullMethodName                   = "/lenny.adapter.v1.Adapter/Interrupt"
	Adapter_Checkpoint_FullMethodName                  = "/lenny.adapter.v1.Adapter/Checkpoint"
	Adapter_SignalDeadline_FullMethodName              = "/lenny.adapter.v1.Adapter/SignalDeadline"
	Adapter_Resume_FullMethodName                      = "/lenny.adapter.v1.Adapter/Resume"
	Adapter_CoordinatorFence_FullMethodName            = "/lenny.adapter.v1.Adapter/CoordinatorFence"
	Adapter_CheckpointBarrier_FullMethodName           = "/lenny.adapter.v1.Adapter/CheckpointBarrier"
	Adapter_ExportPaths_FullMethodName                 = "/lenny.adapter.v1.Adapter/ExportPaths"
	Adapter_ReportUsage_FullMethodName                 = "/lenny.adapter.v1.Adapter/ReportUsage"
	Adapter_Shutdown_FullMethodName                    = "/lenny.adapter.v1.Adapter/Shutdown"
	Adapter_DemoteSDK_FullMethodName                   = "/lenny.adapter.v1.Adapter/DemoteSDK"
	Adapter_NegotiateVersion_FullMethodName            = "/lenny.adapter.v1.Adapter/NegotiateVersion"
	Adapter_GetObservedIntegrationLevel_FullMethodName = "/lenny.adapter.v1.Adapter/GetObservedIntegrationLevel"
	Adapter_LifecycleChannel_FullMethodName            = "/lenny.adapter.v1.Adapter/LifecycleChannel"
)

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Adapter is the long-running gRPC server hosted by the adapter sidecar
// inside every Lenny pod. The gateway connects over mTLS and uses it for
// session lifecycle, credential delivery, interrupt control, checkpoint
// orchestration, and usage reporting. Pod → gateway traffic is initiated
// by the gateway only; the adapter responds to RPCs and emits structured
// events via a separate streaming RPC (the lifecycle channel).
type AdapterClient interface {
	// PrepareWorkspace accepts streamed upload-file content into the pod's
	// staging area. It is the first RPC in the §4.7 session assignment
	// sequence (PrepareWorkspace, FinalizeWorkspace, RunSetup,
	// StartSession). Frames sharing an upload_ref are concatenated in
	// arrival order into one staged file; FinalizeWorkspace then
	// materializes the uploadFile and uploadArchive plan sources from the
	// staged content.
	PrepareWorkspace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PrepareWorkspaceRequest, PrepareWorkspaceResponse], error)
	// FinalizeWorkspace validates the staged workspace content and
	// materializes the §14 WorkspacePlan into /workspace/current. It is
	// the second RPC in the §4.7 session assignment sequence
	// (PrepareWorkspace, FinalizeWorkspace, RunSetup, StartSession).
	FinalizeWorkspace(ctx context.Context, in *FinalizeWorkspaceRequest, opts ...grpc.CallOption) (*FinalizeWorkspaceResponse, error)
	// RunSetup executes the §14 WorkspacePlan setup commands against the
	// materialized workspace. It is the third RPC in the §4.7 session
	// assignment sequence (PrepareWorkspace, FinalizeWorkspace, RunSetup,
	// StartSession). The §5.1 setupPolicy in the request bounds the
	// aggregate setup phase.
	RunSetup(ctx context.Context, in *RunSetupRequest, opts ...grpc.CallOption) (*RunSetupResponse, error)
	// StartSession starts the agent runtime on this pod. It is the final
	// RPC of the §4.7 session assignment sequence (PrepareWorkspace,
	// FinalizeWorkspace, RunSetup, StartSession): the workspace is already
	// materialized by FinalizeWorkspace and setup is already run by
	// RunSetup. Returns Unavailable if the pod is not in `idle` state.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// ConfigureWorkspace points a pre-connected SDK-warm session at the
	// finalized working directory (§4.7 SDK-warm mode). It is the SDK-warm
	// counterpart of StartSession: the runtime has already connected its SDK
	// at warm time, so instead of starting it fresh the adapter delivers the
	// final cwd. Timeout: 10s. Idempotent — sending the same cwd twice is
	// safe. On failure the gateway calls DemoteSDK and falls back to pod-warm
	// materialization. Applies only to runtimes that declare
	// capabilities.preConnect: true; pod-warm adapters return Unimplemented.
	ConfigureWorkspace(ctx context.Context, in *ConfigureWorkspaceRequest, opts ...grpc.CallOption) (*ConfigureWorkspaceResponse, error)
	// SendMessage delivers a content message to the agent over the adapter's
	// stdin JSONL channel. See lenny-adapter-jsonl.schema.json `message`.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Attach opens the bidirectional content stream between the gateway and a
	// running session (spec §4.7 RPC table: "Connect client stream to running
	// session"). The gateway streams client-to-agent envelopes in; the adapter
	// streams the agent's response, tool-call, and status envelopes back.
	// Envelope payloads are §15.4.1 JSONL frames carried verbatim as JSON
	// bytes, mirroring SendMessage.envelope_json.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error)
	// AssignCredentials pushes a per-session credential lease map to the
	// adapter. Adapter writes the credential file under /run/lenny/. Atomic
	// across providers; partial failures are rolled back.
	AssignCredentials(ctx context.Context, in *AssignCredentialsRequest, opts ...grpc.CallOption) (*AssignCredentialsResponse, error)
	// RotateCredentials replaces a previously assigned credential lease with
	// a new lease. Emits a `credentials_rotated` lifecycle event to the
	// agent. Used for hot rotation without pod restart.
	RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error)
	// RevokeCredentials removes a credential lease immediately. The agent
	// receives no chance to drain in-flight requests; emergency revocation.
	RevokeCredentials(ctx context.Context, in *RevokeCredentialsRequest, opts ...grpc.CallOption) (*RevokeCredentialsResponse, error)
	// Interrupt asks the agent to pause and (optionally) checkpoint. Two
	// modes: clean (graceful, with deadline) and hard (SIGTERM/SIGKILL).
	Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error)
	// Checkpoint requests an immediate checkpoint of the current session
	// state to the artifact store. Used for eviction, drain, and session
	// suspend.
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// SignalDeadline warns the running session's runtime that the session is
	// approaching its §11.3 line 240 deadline so the agent can checkpoint and
	// the client can wrap up. The gateway watchdog fires it once, five minutes
	// before `maxSessionAge` expires. The adapter forwards it as a
	// DEADLINE_APPROACHING frame over the §15.4.6 lifecycle channel; a
	// Basic/Standard runtime with no lifecycle channel cannot receive advance
	// notice (§15 line 2141) and the call returns delivered=false rather than
	// erroring so the watchdog's best-effort warning never fails. One-way: the
	// adapter does not block on a runtime acknowledgement.
	SignalDeadline(ctx context.Context, in *SignalDeadlineRequest, opts ...grpc.CallOption) (*SignalDeadlineResponse, error)
	// Resume restores a session's workspace from a checkpoint on a
	// replacement pod (§4.7, §7.1). The adapter claims the session,
	// rebuilds /workspace/current from the named checkpoint, and starts
	// the runtime — the replacement-pod counterpart of StartSession.
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	// CoordinatorFence announces a new `coordination_generation` to the pod
	// on coordinator handoff (§4.7 line 632, §10.1). The pod records the new
	// generation and from this point rejects any RPC carrying an older one.
	// Deadline: 5 s (hard-coded, §11.3). Includes gap detection: if the
	// received generation skips one or more values relative to the last
	// acknowledged fence, the adapter cancels and discards every in-flight
	// RPC received under the missing generation(s), resets transient
	// tool-call state, and logs a `coordinator_generation_gap` event before
	// acknowledging the new generation. The first call on a pod's lifetime
	// is never treated as a gap regardless of value.
	CoordinatorFence(ctx context.Context, in *CoordinatorFenceRequest, opts ...grpc.CallOption) (*CoordinatorFenceResponse, error)
	// CheckpointBarrier dispatches a barrier signal during gateway graceful
	// drain (§4.7 line 631, §10.1). The adapter validates the request's
	// `coordination_generation` against the last fenced generation, quiesces
	// tool-call dispatch, flushes a best-effort checkpoint, and acknowledges
	// via `CheckpointBarrierAck` on the LifecycleChannel control stream
	// (§4.7 line 660 — fields: `barrier_id`, `last_tool_call_id`,
	// `checkpoint_ref`). The RPC return value mirrors the ack so a
	// synchronous caller has the same information; the control-stream emit
	// is the canonical surface for the gateway's barrier-target reconciler.
	// The single wall-clock deadline `checkpointBarrierAckTimeoutSeconds`
	// is enforced by the gateway across all coordinated pods.
	CheckpointBarrier(ctx context.Context, in *CheckpointBarrierRequest, opts ...grpc.CallOption) (*CheckpointBarrierResponse, error)
	// ExportPaths packages files from /workspace/current for delegation,
	// rebased per the export spec (§8.7). The adapter resolves each export
	// source glob inside the workspace root, rejects any matched file whose
	// realpath escapes the workspace via symlink, strips the glob's base
	// path, and re-roots each file under the export's dest_prefix. The
	// gateway applies the lease's fileExportLimits and optional content
	// scanning to the returned set. Spec: §4.7 line 633, §8.7.
	ExportPaths(ctx context.Context, in *ExportPathsRequest, opts ...grpc.CallOption) (*ExportPathsResponse, error)
	// ReportUsage returns token-usage and time-usage accounting since the
	// last call. The gateway uses this for budget enforcement and billing.
	ReportUsage(ctx context.Context, in *ReportUsageRequest, opts ...grpc.CallOption) (*ReportUsageResponse, error)
	// Shutdown asks the adapter to terminate the agent and release the pod.
	// The adapter forwards a JSONL `shutdown` to the agent with the supplied
	// deadline. Returns when the agent process has exited.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// DemoteSDK is required for runtimes that declare
	// `capabilities.preConnect: true`. The gateway calls DemoteSDK when an
	// SDK-warm pod's incoming WorkspacePlan matches a `sdkWarmBlockingPaths`
	// pattern, instructing the adapter to tear down the pre-connected SDK
	// and demote the pod to pod-warm before workspace materialization
	// proceeds. Pods without preConnect: true return Unimplemented.
	// Spec: §4.7, §6.1, §15.4.
	DemoteSDK(ctx context.Context, in *DemoteSDKRequest, opts ...grpc.CallOption) (*DemoteSDKResponse, error)
	// NegotiateVersion is called once per gateway↔adapter handshake.
	// The adapter advertises the protocol versions and capabilities it
	// supports; the gateway selects a compatible version. Subsequent
	// RPCs assume the negotiated version. See spec §15.5 (versioning).
	NegotiateVersion(ctx context.Context, in *NegotiateVersionRequest, opts ...grpc.CallOption) (*NegotiateVersionResponse, error)
	// GetObservedIntegrationLevel reports the §5.1 / §15.4.3 integration
	// level the adapter observed the runtime actually implement, derived
	// from whether the runtime completed the §4.7
	// lifecycle_capabilities/lifecycle_support exchange (full) and whether
	// it connected to the intra-pod platform MCP server (standard). The
	// gateway calls it once per runtime on the first session assignment to
	// compare the observed level against the runtime's declared
	// integrationLevel and reject an underperforming runtime
	// (RUNTIME_LEVEL_UNDERPERFORMS). See spec §5.1.
	GetObservedIntegrationLevel(ctx context.Context, in *GetObservedIntegrationLevelRequest, opts ...grpc.CallOption) (*GetObservedIntegrationLevelResponse, error)
	// LifecycleChannel is a bidirectional stream the adapter uses to surface
	// Full-level lifecycle events (checkpoint_ready, interrupt_acknowledged,
	// credentials_acknowledged, deadline_approaching). See spec §15.4 for
	// the event taxonomy.
	LifecycleChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LifecycleChannelRequest, LifecycleChannelResponse], error)
}

type adapterClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterClient(cc grpc.ClientConnInterface) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) PrepareWorkspace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PrepareWorkspaceRequest, PrepareWorkspaceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[0], Adapter_PrepareWorkspace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PrepareWorkspaceRequest, PrepareWorkspaceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_PrepareWorkspaceClient = grpc.ClientStreamingClient[PrepareWorkspaceRequest, PrepareWorkspaceResponse]

func (c *adapterClient) FinalizeWorkspace(ctx context.Context, in *FinalizeWorkspaceRequest, opts ...grpc.CallOption) (*FinalizeWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeWorkspaceResponse)
	err := c.cc.Invoke(ctx, Adapter_FinalizeWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) RunSetup(ctx context.Context, in *RunSetupRequest, opts ...grpc.CallOption) (*RunSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSetupResponse)
	err := c.cc.Invoke(ctx, Adapter_RunSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, Adapter_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ConfigureWorkspace(ctx context.Context, in *ConfigureWorkspaceRequest, opts ...grpc.CallOption) (*ConfigureWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureWorkspaceResponse)
	err := c.cc.Invoke(ctx, Adapter_ConfigureWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Adapter_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[1], Adapter_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachRequest, AttachResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AttachClient = grpc.BidiStreamingClient[AttachRequest, AttachResponse]

func (c *adapterClient) AssignCredentials(ctx context.Context, in *AssignCredentialsRequest, opts ...grpc.CallOption) (*AssignCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignCredentialsResponse)
	err := c.cc.Invoke(ctx, Adapter_AssignCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCredentialsResponse)
	err := c.cc.Invoke(ctx, Adapter_RotateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) RevokeCredentials(ctx context.Context, in *RevokeCredentialsRequest, opts ...grpc.CallOption) (*RevokeCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialsResponse)
	err := c.cc.Invoke(ctx, Adapter_RevokeCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterruptResponse)
	err := c.cc.Invoke(ctx, Adapter_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, Adapter_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SignalDeadline(ctx context.Context, in *SignalDeadlineRequest, opts ...grpc.CallOption) (*SignalDeadlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalDeadlineResponse)
	err := c.cc.Invoke(ctx, Adapter_SignalDeadline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, Adapter_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) CoordinatorFence(ctx context.Context, in *CoordinatorFenceRequest, opts ...grpc.CallOption) (*CoordinatorFenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorFenceResponse)
	err := c.cc.Invoke(ctx, Adapter_CoordinatorFence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) CheckpointBarrier(ctx context.Context, in *CheckpointBarrierRequest, opts ...grpc.CallOption) (*CheckpointBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointBarrierResponse)
	err := c.cc.Invoke(ctx, Adapter_CheckpointBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ExportPaths(ctx context.Context, in *ExportPathsRequest, opts ...grpc.CallOption) (*ExportPathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportPathsResponse)
	err := c.cc.Invoke(ctx, Adapter_ExportPaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ReportUsage(ctx context.Context, in *ReportUsageRequest, opts ...grpc.CallOption) (*ReportUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportUsageResponse)
	err := c.cc.Invoke(ctx, Adapter_ReportUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, Adapter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) DemoteSDK(ctx context.Context, in *DemoteSDKRequest, opts ...grpc.CallOption) (*DemoteSDKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoteSDKResponse)
	err := c.cc.Invoke(ctx, Adapter_DemoteSDK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) NegotiateVersion(ctx context.Context, in *NegotiateVersionRequest, opts ...grpc.CallOption) (*NegotiateVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiateVersionResponse)
	err := c.cc.Invoke(ctx, Adapter_NegotiateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) GetObservedIntegrationLevel(ctx context.Context, in *GetObservedIntegrationLevelRequest, opts ...grpc.CallOption) (*GetObservedIntegrationLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObservedIntegrationLevelResponse)
	err := c.cc.Invoke(ctx, Adapter_GetObservedIntegrationLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) LifecycleChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LifecycleChannelRequest, LifecycleChannelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[2], Adapter_LifecycleChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LifecycleChannelRequest, LifecycleChannelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_LifecycleChannelClient = grpc.BidiStreamingClient[LifecycleChannelRequest, LifecycleChannelResponse]

// AdapterServer is the server API for Adapter service.
// All implementations should embed UnimplementedAdapterServer
// for forward compatibility.
//
// Adapter is the long-running gRPC server hosted by the adapter sidecar
// inside every Lenny pod. The gateway connects over mTLS and uses it for
// session lifecycle, credential delivery, interrupt control, checkpoint
// orchestration, and usage reporting. Pod → gateway traffic is initiated
// by the gateway only; the adapter responds to RPCs and emits structured
// events via a separate streaming RPC (the lifecycle channel).
type AdapterServer interface {
	// PrepareWorkspace accepts streamed upload-file content into the pod's
	// staging area. It is the first RPC in the §4.7 session assignment
	// sequence (PrepareWorkspace, FinalizeWorkspace, RunSetup,
	// StartSession). Frames sharing an upload_ref are concatenated in
	// arrival order into one staged file; FinalizeWorkspace then
	// materializes the uploadFile and uploadArchive plan sources from the
	// staged content.
	PrepareWorkspace(grpc.ClientStreamingServer[PrepareWorkspaceRequest, PrepareWorkspaceResponse]) error
	// FinalizeWorkspace validates the staged workspace content and
	// materializes the §14 WorkspacePlan into /workspace/current. It is
	// the second RPC in the §4.7 session assignment sequence
	// (PrepareWorkspace, FinalizeWorkspace, RunSetup, StartSession).
	FinalizeWorkspace(context.Context, *FinalizeWorkspaceRequest) (*FinalizeWorkspaceResponse, error)
	// RunSetup executes the §14 WorkspacePlan setup commands against the
	// materialized workspace. It is the third RPC in the §4.7 session
	// assignment sequence (PrepareWorkspace, FinalizeWorkspace, RunSetup,
	// StartSession). The §5.1 setupPolicy in the request bounds the
	// aggregate setup phase.
	RunSetup(context.Context, *RunSetupRequest) (*RunSetupResponse, error)
	// StartSession starts the agent runtime on this pod. It is the final
	// RPC of the §4.7 session assignment sequence (PrepareWorkspace,
	// FinalizeWorkspace, RunSetup, StartSession): the workspace is already
	// materialized by FinalizeWorkspace and setup is already run by
	// RunSetup. Returns Unavailable if the pod is not in `idle` state.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// ConfigureWorkspace points a pre-connected SDK-warm session at the
	// finalized working directory (§4.7 SDK-warm mode). It is the SDK-warm
	// counterpart of StartSession: the runtime has already connected its SDK
	// at warm time, so instead of starting it fresh the adapter delivers the
	// final cwd. Timeout: 10s. Idempotent — sending the same cwd twice is
	// safe. On failure the gateway calls DemoteSDK and falls back to pod-warm
	// materialization. Applies only to runtimes that declare
	// capabilities.preConnect: true; pod-warm adapters return Unimplemented.
	ConfigureWorkspace(context.Context, *ConfigureWorkspaceRequest) (*ConfigureWorkspaceResponse, error)
	// SendMessage delivers a content message to the agent over the adapter's
	// stdin JSONL channel. See lenny-adapter-jsonl.schema.json `message`.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Attach opens the bidirectional content stream between the gateway and a
	// running session (spec §4.7 RPC table: "Connect client stream to running
	// session"). The gateway streams client-to-agent envelopes in; the adapter
	// streams the agent's response, tool-call, and status envelopes back.
	// Envelope payloads are §15.4.1 JSONL frames carried verbatim as JSON
	// bytes, mirroring SendMessage.envelope_json.
	Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error
	// AssignCredentials pushes a per-session credential lease map to the
	// adapter. Adapter writes the credential file under /run/lenny/. Atomic
	// across providers; partial failures are rolled back.
	AssignCredentials(context.Context, *AssignCredentialsRequest) (*AssignCredentialsResponse, error)
	// RotateCredentials replaces a previously assigned credential lease with
	// a new lease. Emits a `credentials_rotated` lifecycle event to the
	// agent. Used for hot rotation without pod restart.
	RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error)
	// RevokeCredentials removes a credential lease immediately. The agent
	// receives no chance to drain in-flight requests; emergency revocation.
	RevokeCredentials(context.Context, *RevokeCredentialsRequest) (*RevokeCredentialsResponse, error)
	// Interrupt asks the agent to pause and (optionally) checkpoint. Two
	// modes: clean (graceful, with deadline) and hard (SIGTERM/SIGKILL).
	Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error)
	// Checkpoint requests an immediate checkpoint of the current session
	// state to the artifact store. Used for eviction, drain, and session
	// suspend.
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// SignalDeadline warns the running session's runtime that the session is
	// approaching its §11.3 line 240 deadline so the agent can checkpoint and
	// the client can wrap up. The gateway watchdog fires it once, five minutes
	// before `maxSessionAge` expires. The adapter forwards it as a
	// DEADLINE_APPROACHING frame over the §15.4.6 lifecycle channel; a
	// Basic/Standard runtime with no lifecycle channel cannot receive advance
	// notice (§15 line 2141) and the call returns delivered=false rather than
	// erroring so the watchdog's best-effort warning never fails. One-way: the
	// adapter does not block on a runtime acknowledgement.
	SignalDeadline(context.Context, *SignalDeadlineRequest) (*SignalDeadlineResponse, error)
	// Resume restores a session's workspace from a checkpoint on a
	// replacement pod (§4.7, §7.1). The adapter claims the session,
	// rebuilds /workspace/current from the named checkpoint, and starts
	// the runtime — the replacement-pod counterpart of StartSession.
	Resume(context.Context, *ResumeRequest) (*ResumeResponse, error)
	// CoordinatorFence announces a new `coordination_generation` to the pod
	// on coordinator handoff (§4.7 line 632, §10.1). The pod records the new
	// generation and from this point rejects any RPC carrying an older one.
	// Deadline: 5 s (hard-coded, §11.3). Includes gap detection: if the
	// received generation skips one or more values relative to the last
	// acknowledged fence, the adapter cancels and discards every in-flight
	// RPC received under the missing generation(s), resets transient
	// tool-call state, and logs a `coordinator_generation_gap` event before
	// acknowledging the new generation. The first call on a pod's lifetime
	// is never treated as a gap regardless of value.
	CoordinatorFence(context.Context, *CoordinatorFenceRequest) (*CoordinatorFenceResponse, error)
	// CheckpointBarrier dispatches a barrier signal during gateway graceful
	// drain (§4.7 line 631, §10.1). The adapter validates the request's
	// `coordination_generation` against the last fenced generation, quiesces
	// tool-call dispatch, flushes a best-effort checkpoint, and acknowledges
	// via `CheckpointBarrierAck` on the LifecycleChannel control stream
	// (§4.7 line 660 — fields: `barrier_id`, `last_tool_call_id`,
	// `checkpoint_ref`). The RPC return value mirrors the ack so a
	// synchronous caller has the same information; the control-stream emit
	// is the canonical surface for the gateway's barrier-target reconciler.
	// The single wall-clock deadline `checkpointBarrierAckTimeoutSeconds`
	// is enforced by the gateway across all coordinated pods.
	CheckpointBarrier(context.Context, *CheckpointBarrierRequest) (*CheckpointBarrierResponse, error)
	// ExportPaths packages files from /workspace/current for delegation,
	// rebased per the export spec (§8.7). The adapter resolves each export
	// source glob inside the workspace root, rejects any matched file whose
	// realpath escapes the workspace via symlink, strips the glob's base
	// path, and re-roots each file under the export's dest_prefix. The
	// gateway applies the lease's fileExportLimits and optional content
	// scanning to the returned set. Spec: §4.7 line 633, §8.7.
	ExportPaths(context.Context, *ExportPathsRequest) (*ExportPathsResponse, error)
	// ReportUsage returns token-usage and time-usage accounting since the
	// last call. The gateway uses this for budget enforcement and billing.
	ReportUsage(context.Context, *ReportUsageRequest) (*ReportUsageResponse, error)
	// Shutdown asks the adapter to terminate the agent and release the pod.
	// The adapter forwards a JSONL `shutdown` to the agent with the supplied
	// deadline. Returns when the agent process has exited.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// DemoteSDK is required for runtimes that declare
	// `capabilities.preConnect: true`. The gateway calls DemoteSDK when an
	// SDK-warm pod's incoming WorkspacePlan matches a `sdkWarmBlockingPaths`
	// pattern, instructing the adapter to tear down the pre-connected SDK
	// and demote the pod to pod-warm before workspace materialization
	// proceeds. Pods without preConnect: true return Unimplemented.
	// Spec: §4.7, §6.1, §15.4.
	DemoteSDK(context.Context, *DemoteSDKRequest) (*DemoteSDKResponse, error)
	// NegotiateVersion is called once per gateway↔adapter handshake.
	// The adapter advertises the protocol versions and capabilities it
	// supports; the gateway selects a compatible version. Subsequent
	// RPCs assume the negotiated version. See spec §15.5 (versioning).
	NegotiateVersion(context.Context, *NegotiateVersionRequest) (*NegotiateVersionResponse, error)
	// GetObservedIntegrationLevel reports the §5.1 / §15.4.3 integration
	// level the adapter observed the runtime actually implement, derived
	// from whether the runtime completed the §4.7
	// lifecycle_capabilities/lifecycle_support exchange (full) and whether
	// it connected to the intra-pod platform MCP server (standard). The
	// gateway calls it once per runtime on the first session assignment to
	// compare the observed level against the runtime's declared
	// integrationLevel and reject an underperforming runtime
	// (RUNTIME_LEVEL_UNDERPERFORMS). See spec §5.1.
	GetObservedIntegrationLevel(context.Context, *GetObservedIntegrationLevelRequest) (*GetObservedIntegrationLevelResponse, error)
	// LifecycleChannel is a bidirectional stream the adapter uses to surface
	// Full-level lifecycle events (checkpoint_ready, interrupt_acknowledged,
	// credentials_acknowledged, deadline_approaching). See spec §15.4 for
	// the event taxonomy.
	LifecycleChannel(grpc.BidiStreamingServer[LifecycleChannelRequest, LifecycleChannelResponse]) error
}

// UnimplementedAdapterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterServer struct{}

func (UnimplementedAdapterServer) PrepareWorkspace(grpc.ClientStreamingServer[PrepareWorkspaceRequest, PrepareWorkspaceResponse]) error {
	return status.Error(codes.Unimplemented, "method PrepareWorkspace not implemented")
}
func (UnimplementedAdapterServer) FinalizeWorkspace(context.Context, *FinalizeWorkspaceRequest) (*FinalizeWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeWorkspace not implemented")
}
func (UnimplementedAdapterServer) RunSetup(context.Context, *RunSetupRequest) (*RunSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSetup not implemented")
}
func (UnimplementedAdapterServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedAdapterServer) ConfigureWorkspace(context.Context, *ConfigureWorkspaceRequest) (*ConfigureWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureWorkspace not implemented")
}
func (UnimplementedAdapterServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAdapterServer) Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedAdapterServer) AssignCredentials(context.Context, *AssignCredentialsRequest) (*AssignCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCredentials not implemented")
}
func (UnimplementedAdapterServer) RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCredentials not implemented")
}
func (UnimplementedAdapterServer) RevokeCredentials(context.Context, *RevokeCredentialsRequest) (*RevokeCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCredentials not implemented")
}
func (UnimplementedAdapterServer) Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedAdapterServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedAdapterServer) SignalDeadline(context.Context, *SignalDeadlineRequest) (*SignalDeadlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalDeadline not implemented")
}
func (UnimplementedAdapterServer) Resume(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedAdapterServer) CoordinatorFence(context.Context, *CoordinatorFenceRequest) (*CoordinatorFenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoordinatorFence not implemented")
}
func (UnimplementedAdapterServer) CheckpointBarrier(context.Context, *CheckpointBarrierRequest) (*CheckpointBarrierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointBarrier not implemented")
}
func (UnimplementedAdapterServer) ExportPaths(context.Context, *ExportPathsRequest) (*ExportPathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPaths not implemented")
}
func (UnimplementedAdapterServer) ReportUsage(context.Context, *ReportUsageRequest) (*ReportUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUsage not implemented")
}
func (UnimplementedAdapterServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAdapterServer) DemoteSDK(context.Context, *DemoteSDKRequest) (*DemoteSDKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DemoteSDK not implemented")
}
func (UnimplementedAdapterServer) NegotiateVersion(context.Context, *NegotiateVersionRequest) (*NegotiateVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NegotiateVersion not implemented")
}
func (UnimplementedAdapterServer) GetObservedIntegrationLevel(context.Context, *GetObservedIntegrationLevelRequest) (*GetObservedIntegrationLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObservedIntegrationLevel not implemented")
}
func (UnimplementedAdapterServer) LifecycleChannel(grpc.BidiStreamingServer[LifecycleChannelRequest, LifecycleChannelResponse]) error {
	return status.Error(codes.Unimplemented, "method LifecycleChannel not implemented")
}
func (UnimplementedAdapterServer) testEmbeddedByValue() {}

// UnsafeAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterServer will
// result in compilation errors.
type UnsafeAdapterServer interface {
	mustEmbedUnimplementedAdapterServer()
}

func RegisterAdapterServer(s grpc.ServiceRegistrar, srv AdapterServer) {
	// If the following call panics, it indicates UnimplementedAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Adapter_ServiceDesc, srv)
}

func _Adapter_PrepareWorkspace_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).PrepareWorkspace(&grpc.GenericServerStream[PrepareWorkspaceRequest, PrepareWorkspaceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_PrepareWorkspaceServer = grpc.ClientStreamingServer[PrepareWorkspaceRequest, PrepareWorkspaceResponse]

func _Adapter_FinalizeWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).FinalizeWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_FinalizeWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).FinalizeWorkspace(ctx, req.(*FinalizeWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_RunSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).RunSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_RunSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).RunSetup(ctx, req.(*RunSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ConfigureWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ConfigureWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_ConfigureWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ConfigureWorkspace(ctx, req.(*ConfigureWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).Attach(&grpc.GenericServerStream[AttachRequest, AttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AttachServer = grpc.BidiStreamingServer[AttachRequest, AttachResponse]

func _Adapter_AssignCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).AssignCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_AssignCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).AssignCredentials(ctx, req.(*AssignCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_RotateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).RotateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_RotateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).RotateCredentials(ctx, req.(*RotateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_RevokeCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).RevokeCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_RevokeCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).RevokeCredentials(ctx, req.(*RevokeCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Interrupt(ctx, req.(*InterruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SignalDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SignalDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_SignalDeadline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SignalDeadline(ctx, req.(*SignalDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_CoordinatorFence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorFenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).CoordinatorFence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_CoordinatorFence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).CoordinatorFence(ctx, req.(*CoordinatorFenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_CheckpointBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).CheckpointBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_CheckpointBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).CheckpointBarrier(ctx, req.(*CheckpointBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ExportPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ExportPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_ExportPaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ExportPaths(ctx, req.(*ExportPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_ReportUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ReportUsage(ctx, req.(*ReportUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_DemoteSDK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoteSDKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).DemoteSDK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_DemoteSDK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).DemoteSDK(ctx, req.(*DemoteSDKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_NegotiateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).NegotiateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_NegotiateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).NegotiateVersion(ctx, req.(*NegotiateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_GetObservedIntegrationLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservedIntegrationLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).GetObservedIntegrationLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_GetObservedIntegrationLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).GetObservedIntegrationLevel(ctx, req.(*GetObservedIntegrationLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_LifecycleChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).LifecycleChannel(&grpc.GenericServerStream[LifecycleChannelRequest, LifecycleChannelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_LifecycleChannelServer = grpc.BidiStreamingServer[LifecycleChannelRequest, LifecycleChannelResponse]

// Adapter_ServiceDesc is the grpc.ServiceDesc for Adapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Adapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lenny.adapter.v1.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FinalizeWorkspace",
			Handler:    _Adapter_FinalizeWorkspace_Handler,
		},
		{
			MethodName: "RunSetup",
			Handler:    _Adapter_RunSetup_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _Adapter_StartSession_Handler,
		},
		{
			MethodName: "ConfigureWorkspace",
			Handler:    _Adapter_ConfigureWorkspace_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Adapter_SendMessage_Handler,
		},
		{
			MethodName: "AssignCredentials",
			Handler:    _Adapter_AssignCredentials_Handler,
		},
		{
			MethodName: "RotateCredentials",
			Handler:    _Adapter_RotateCredentials_Handler,
		},
		{
			MethodName: "RevokeCredentials",
			Handler:    _Adapter_RevokeCredentials_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _Adapter_Interrupt_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Adapter_Checkpoint_Handler,
		},
		{
			MethodName: "SignalDeadline",
			Handler:    _Adapter_SignalDeadline_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Adapter_Resume_Handler,
		},
		{
			MethodName: "CoordinatorFence",
			Handler:    _Adapter_CoordinatorFence_Handler,
		},
		{
			MethodName: "CheckpointBarrier",
			Handler:    _Adapter_CheckpointBarrier_Handler,
		},
		{
			MethodName: "ExportPaths",
			Handler:    _Adapter_ExportPaths_Handler,
		},
		{
			MethodName: "ReportUsage",
			Handler:    _Adapter_ReportUsage_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Adapter_Shutdown_Handler,
		},
		{
			MethodName: "DemoteSDK",
			Handler:    _Adapter_DemoteSDK_Handler,
		},
		{
			MethodName: "NegotiateVersion",
			Handler:    _Adapter_NegotiateVersion_Handler,
		},
		{
			MethodName: "GetObservedIntegrationLevel",
			Handler:    _Adapter_GetObservedIntegrationLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrepareWorkspace",
			Handler:       _Adapter_PrepareWorkspace_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Attach",
			Handler:       _Adapter_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LifecycleChannel",
			Handler:       _Adapter_LifecycleChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lenny-adapter.proto",
}

const (
	GatewayControl_ExtendLease_FullMethodName           = "/lenny.adapter.v1.GatewayControl/ExtendLease"
	GatewayControl_ListPlatformTools_FullMethodName     = "/lenny.adapter.v1.GatewayControl/ListPlatformTools"
	GatewayControl_CallPlatformTool_FullMethodName      = "/lenny.adapter.v1.GatewayControl/CallPlatformTool"
	GatewayControl_ListSessionConnectors_FullMethodName = "/lenny.adapter.v1.GatewayControl/ListSessionConnectors"
	GatewayControl_ListConnectorTools_FullMethodName    = "/lenny.adapter.v1.GatewayControl/ListConnectorTools"
	GatewayControl_CallConnectorTool_FullMethodName     = "/lenny.adapter.v1.GatewayControl/CallConnectorTool"
)

// GatewayControlClient is the client API for GatewayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayControl is the adapter→gateway control surface. It is the
// inverse direction of the Adapter service: the gateway hosts this
// gRPC server and the adapter dials it as a client. Adapter traffic
// on this service is initiated by the adapter, in contrast to the
// Adapter service where the gateway initiates every RPC.
//
// The service exists because a few §8 control operations originate at
// the pod and need a gateway decision. ExtendLease is the first such
// operation: the adapter cannot resolve a token-budget extension
// itself because the layered §8.6 ceiling and the per-tree budget
// state live on the gateway.
type GatewayControlClient interface {
	// ExtendLease is the adapter's request to the gateway for additional
	// token budget. Per spec §8.6 the adapter issues it when the LLM
	// proxy rejects a call for budget exhaustion. Response carries one
	// of GRANTED, PARTIALLY_GRANTED, CEILING_REACHED, REJECTED. On
	// CEILING_REACHED or REJECTED the adapter MUST NOT retry the
	// extension; it propagates BUDGET_EXHAUSTED to the runtime.
	ExtendLease(ctx context.Context, in *ExtendLeaseRequest, opts ...grpc.CallOption) (*ExtendLeaseResponse, error)
	// ListPlatformTools returns the §9.1 platform tool catalog (lines
	// 14-31: lenny/delegate_task, lenny/await_children, ...) the adapter's
	// intra-pod platform MCP server advertises to a type:agent runtime on
	// tools/list. The catalog is sourced from the gateway's platform tool
	// surface so the intra-pod server never duplicates the tool schemas.
	// spec: §9.1 lines 14-31.
	ListPlatformTools(ctx context.Context, in *ListPlatformToolsRequest, opts ...grpc.CallOption) (*ListPlatformToolsResponse, error)
	// CallPlatformTool dispatches one §9.1 platform tool call a type:agent
	// runtime made against the adapter's intra-pod platform MCP server
	// (the @lenny-platform-mcp socket) to the gateway's platform tool
	// surface, scoped to the calling session. The gateway runs the same
	// handler the gateway-edge /mcp surface runs, so the intra-pod and
	// edge surfaces stay in lockstep. The response carries the JSON-encoded
	// MCP tool result; a tool-level failure is an is_error result rather
	// than a gRPC error. spec: §9.1 line 14; §4.7 line 942.
	CallPlatformTool(ctx context.Context, in *CallPlatformToolRequest, opts ...grpc.CallOption) (*CallPlatformToolResponse, error)
	// ListSessionConnectors returns the §9.3 connectors a session's
	// effective delegation policy permits. The adapter opens one intra-pod
	// MCP server (the @lenny-connector-<id> socket) per returned connector
	// and lists them in the manifest connectorServers array, so a
	// type:agent runtime can reach every external tool its policy admits.
	// The gateway filters the tenant's connector registry by the calling
	// session's delegation policy, so a connector the policy denies is
	// never advertised to the pod. spec: §9.3 line 142.
	ListSessionConnectors(ctx context.Context, in *ListSessionConnectorsRequest, opts ...grpc.CallOption) (*ListSessionConnectorsResponse, error)
	// ListConnectorTools returns the tool catalog a single §9.3 connector
	// exposes, for the adapter's intra-pod per-connector MCP server to
	// advertise on tools/list. The gateway acts as the MCP client to the
	// external endpoint (the connector's mcpServerUrl), using the
	// gateway-held OAuth credential — the credential never transits the
	// pod. A connector the calling session's policy denies is rejected.
	// spec: §9.3 lines 142-164.
	ListConnectorTools(ctx context.Context, in *ListConnectorToolsRequest, opts ...grpc.CallOption) (*ListConnectorToolsResponse, error)
	// CallConnectorTool forwards one §9.3 external tool call a type:agent
	// runtime made against the adapter's intra-pod @lenny-connector-<id>
	// socket to the gateway, which validates the connector_id against the
	// calling pod's effective delegation policy (line 164) and proxies the
	// tools/call to the external MCP endpoint with the gateway-held
	// credential. The response carries the JSON-encoded MCP tool result; a
	// tool-level failure is an is_error result rather than a gRPC error.
	// spec: §9.3 lines 142-164.
	CallConnectorTool(ctx context.Context, in *CallConnectorToolRequest, opts ...grpc.CallOption) (*CallConnectorToolResponse, error)
}

type gatewayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlClient(cc grpc.ClientConnInterface) GatewayControlClient {
	return &gatewayControlClient{cc}
}

func (c *gatewayControlClient) ExtendLease(ctx context.Context, in *ExtendLeaseRequest, opts ...grpc.CallOption) (*ExtendLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendLeaseResponse)
	err := c.cc.Invoke(ctx, GatewayControl_ExtendLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayControlClient) ListPlatformTools(ctx context.Context, in *ListPlatformToolsRequest, opts ...grpc.CallOption) (*ListPlatformToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformToolsResponse)
	err := c.cc.Invoke(ctx, GatewayControl_ListPlatformTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayControlClient) CallPlatformTool(ctx context.Context, in *CallPlatformToolRequest, opts ...grpc.CallOption) (*CallPlatformToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallPlatformToolResponse)
	err := c.cc.Invoke(ctx, GatewayControl_CallPlatformTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayControlClient) ListSessionConnectors(ctx context.Context, in *ListSessionConnectorsRequest, opts ...grpc.CallOption) (*ListSessionConnectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionConnectorsResponse)
	err := c.cc.Invoke(ctx, GatewayControl_ListSessionConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayControlClient) ListConnectorTools(ctx context.Context, in *ListConnectorToolsRequest, opts ...grpc.CallOption) (*ListConnectorToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectorToolsResponse)
	err := c.cc.Invoke(ctx, GatewayControl_ListConnectorTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayControlClient) CallConnectorTool(ctx context.Context, in *CallConnectorToolRequest, opts ...grpc.CallOption) (*CallConnectorToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallConnectorToolResponse)
	err := c.cc.Invoke(ctx, GatewayControl_CallConnectorTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayControlServer is the server API for GatewayControl service.
// All implementations should embed UnimplementedGatewayControlServer
// for forward compatibility.
//
// GatewayControl is the adapter→gateway control surface. It is the
// inverse direction of the Adapter service: the gateway hosts this
// gRPC server and the adapter dials it as a client. Adapter traffic
// on this service is initiated by the adapter, in contrast to the
// Adapter service where the gateway initiates every RPC.
//
// The service exists because a few §8 control operations originate at
// the pod and need a gateway decision. ExtendLease is the first such
// operation: the adapter cannot resolve a token-budget extension
// itself because the layered §8.6 ceiling and the per-tree budget
// state live on the gateway.
type GatewayControlServer interface {
	// ExtendLease is the adapter's request to the gateway for additional
	// token budget. Per spec §8.6 the adapter issues it when the LLM
	// proxy rejects a call for budget exhaustion. Response carries one
	// of GRANTED, PARTIALLY_GRANTED, CEILING_REACHED, REJECTED. On
	// CEILING_REACHED or REJECTED the adapter MUST NOT retry the
	// extension; it propagates BUDGET_EXHAUSTED to the runtime.
	ExtendLease(context.Context, *ExtendLeaseRequest) (*ExtendLeaseResponse, error)
	// ListPlatformTools returns the §9.1 platform tool catalog (lines
	// 14-31: lenny/delegate_task, lenny/await_children, ...) the adapter's
	// intra-pod platform MCP server advertises to a type:agent runtime on
	// tools/list. The catalog is sourced from the gateway's platform tool
	// surface so the intra-pod server never duplicates the tool schemas.
	// spec: §9.1 lines 14-31.
	ListPlatformTools(context.Context, *ListPlatformToolsRequest) (*ListPlatformToolsResponse, error)
	// CallPlatformTool dispatches one §9.1 platform tool call a type:agent
	// runtime made against the adapter's intra-pod platform MCP server
	// (the @lenny-platform-mcp socket) to the gateway's platform tool
	// surface, scoped to the calling session. The gateway runs the same
	// handler the gateway-edge /mcp surface runs, so the intra-pod and
	// edge surfaces stay in lockstep. The response carries the JSON-encoded
	// MCP tool result; a tool-level failure is an is_error result rather
	// than a gRPC error. spec: §9.1 line 14; §4.7 line 942.
	CallPlatformTool(context.Context, *CallPlatformToolRequest) (*CallPlatformToolResponse, error)
	// ListSessionConnectors returns the §9.3 connectors a session's
	// effective delegation policy permits. The adapter opens one intra-pod
	// MCP server (the @lenny-connector-<id> socket) per returned connector
	// and lists them in the manifest connectorServers array, so a
	// type:agent runtime can reach every external tool its policy admits.
	// The gateway filters the tenant's connector registry by the calling
	// session's delegation policy, so a connector the policy denies is
	// never advertised to the pod. spec: §9.3 line 142.
	ListSessionConnectors(context.Context, *ListSessionConnectorsRequest) (*ListSessionConnectorsResponse, error)
	// ListConnectorTools returns the tool catalog a single §9.3 connector
	// exposes, for the adapter's intra-pod per-connector MCP server to
	// advertise on tools/list. The gateway acts as the MCP client to the
	// external endpoint (the connector's mcpServerUrl), using the
	// gateway-held OAuth credential — the credential never transits the
	// pod. A connector the calling session's policy denies is rejected.
	// spec: §9.3 lines 142-164.
	ListConnectorTools(context.Context, *ListConnectorToolsRequest) (*ListConnectorToolsResponse, error)
	// CallConnectorTool forwards one §9.3 external tool call a type:agent
	// runtime made against the adapter's intra-pod @lenny-connector-<id>
	// socket to the gateway, which validates the connector_id against the
	// calling pod's effective delegation policy (line 164) and proxies the
	// tools/call to the external MCP endpoint with the gateway-held
	// credential. The response carries the JSON-encoded MCP tool result; a
	// tool-level failure is an is_error result rather than a gRPC error.
	// spec: §9.3 lines 142-164.
	CallConnectorTool(context.Context, *CallConnectorToolRequest) (*CallConnectorToolResponse, error)
}

// UnimplementedGatewayControlServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlServer struct{}

func (UnimplementedGatewayControlServer) ExtendLease(context.Context, *ExtendLeaseRequest) (*ExtendLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendLease not implemented")
}
func (UnimplementedGatewayControlServer) ListPlatformTools(context.Context, *ListPlatformToolsRequest) (*ListPlatformToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatformTools not implemented")
}
func (UnimplementedGatewayControlServer) CallPlatformTool(context.Context, *CallPlatformToolRequest) (*CallPlatformToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallPlatformTool not implemented")
}
func (UnimplementedGatewayControlServer) ListSessionConnectors(context.Context, *ListSessionConnectorsRequest) (*ListSessionConnectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionConnectors not implemented")
}
func (UnimplementedGatewayControlServer) ListConnectorTools(context.Context, *ListConnectorToolsRequest) (*ListConnectorToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnectorTools not implemented")
}
func (UnimplementedGatewayControlServer) CallConnectorTool(context.Context, *CallConnectorToolRequest) (*CallConnectorToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallConnectorTool not implemented")
}
func (UnimplementedGatewayControlServer) testEmbeddedByValue() {}

// UnsafeGatewayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlServer will
// result in compilation errors.
type UnsafeGatewayControlServer interface {
	mustEmbedUnimplementedGatewayControlServer()
}

func RegisterGatewayControlServer(s grpc.ServiceRegistrar, srv GatewayControlServer) {
	// If the following call panics, it indicates UnimplementedGatewayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControl_ServiceDesc, srv)
}

func _GatewayControl_ExtendLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).ExtendLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_ExtendLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).ExtendLease(ctx, req.(*ExtendLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayControl_ListPlatformTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).ListPlatformTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_ListPlatformTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).ListPlatformTools(ctx, req.(*ListPlatformToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayControl_CallPlatformTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPlatformToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).CallPlatformTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_CallPlatformTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).CallPlatformTool(ctx, req.(*CallPlatformToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayControl_ListSessionConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionConnectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).ListSessionConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_ListSessionConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).ListSessionConnectors(ctx, req.(*ListSessionConnectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayControl_ListConnectorTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectorToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).ListConnectorTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_ListConnectorTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).ListConnectorTools(ctx, req.(*ListConnectorToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayControl_CallConnectorTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallConnectorToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).CallConnectorTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_CallConnectorTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).CallConnectorTool(ctx, req.(*CallConnectorToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayControl_ServiceDesc is the grpc.ServiceDesc for GatewayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lenny.adapter.v1.GatewayControl",
	HandlerType: (*GatewayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtendLease",
			Handler:    _GatewayControl_ExtendLease_Handler,
		},
		{
			MethodName: "ListPlatformTools",
			Handler:    _GatewayControl_ListPlatformTools_Handler,
		},
		{
			MethodName: "CallPlatformTool",
			Handler:    _GatewayControl_CallPlatformTool_Handler,
		},
		{
			MethodName: "ListSessionConnectors",
			Handler:    _GatewayControl_ListSessionConnectors_Handler,
		},
		{
			MethodName: "ListConnectorTools",
			Handler:    _GatewayControl_ListConnectorTools_Handler,
		},
		{
			MethodName: "CallConnectorTool",
			Handler:    _GatewayControl_CallConnectorTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lenny-adapter.proto",
}
