// SPDX-License-Identifier: MIT

// Gateway ↔ pod control protocol. This is the gRPC contract the gateway uses
// to drive a pod's adapter sidecar: deliver messages, push credentials,
// interrupt, request checkpoints, and report usage. The adapter ↔ agent
// channel is JSON Lines (see lenny-adapter-jsonl.schema.json); this proto
// covers only the gateway-facing surface.
//
// See spec/15_external-api-surface.md §15.3 and §15.4.
//
// Phase 1 ships the service skeleton and the canonical message types.
// Field shapes for individual RPCs are deliberately conservative: Phase 2
// implementation fleshes them out and `buf breaking` catches incompatible
// changes against this baseline.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lenny-adapter.proto

package adapterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Adapter_StartSession_FullMethodName      = "/lenny.adapter.v1.Adapter/StartSession"
	Adapter_SendMessage_FullMethodName       = "/lenny.adapter.v1.Adapter/SendMessage"
	Adapter_Attach_FullMethodName            = "/lenny.adapter.v1.Adapter/Attach"
	Adapter_AssignCredentials_FullMethodName = "/lenny.adapter.v1.Adapter/AssignCredentials"
	Adapter_RotateCredentials_FullMethodName = "/lenny.adapter.v1.Adapter/RotateCredentials"
	Adapter_RevokeCredentials_FullMethodName = "/lenny.adapter.v1.Adapter/RevokeCredentials"
	Adapter_Interrupt_FullMethodName         = "/lenny.adapter.v1.Adapter/Interrupt"
	Adapter_Checkpoint_FullMethodName        = "/lenny.adapter.v1.Adapter/Checkpoint"
	Adapter_ReportUsage_FullMethodName       = "/lenny.adapter.v1.Adapter/ReportUsage"
	Adapter_ExtendLease_FullMethodName       = "/lenny.adapter.v1.Adapter/ExtendLease"
	Adapter_Shutdown_FullMethodName          = "/lenny.adapter.v1.Adapter/Shutdown"
	Adapter_DemoteSDK_FullMethodName         = "/lenny.adapter.v1.Adapter/DemoteSDK"
	Adapter_NegotiateVersion_FullMethodName  = "/lenny.adapter.v1.Adapter/NegotiateVersion"
	Adapter_LifecycleChannel_FullMethodName  = "/lenny.adapter.v1.Adapter/LifecycleChannel"
)

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Adapter is the long-running gRPC server hosted by the adapter sidecar
// inside every Lenny pod. The gateway connects over mTLS and uses it for
// session lifecycle, credential delivery, interrupt control, checkpoint
// orchestration, and usage reporting. Pod → gateway traffic is initiated
// by the gateway only; the adapter responds to RPCs and emits structured
// events via a separate streaming RPC (the lifecycle channel).
type AdapterClient interface {
	// StartSession assigns a session to this pod. Workspace materialization
	// (per the supplied WorkspacePlan) and setup-command execution happen
	// before the response. Returns Unavailable if the pod is not in `idle`
	// state.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// SendMessage delivers a content message to the agent over the adapter's
	// stdin JSONL channel. See lenny-adapter-jsonl.schema.json `message`.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Attach opens the bidirectional content stream between the gateway and a
	// running session (spec §4.7 RPC table: "Connect client stream to running
	// session"). The gateway streams client-to-agent envelopes in; the adapter
	// streams the agent's response, tool-call, and status envelopes back.
	// Envelope payloads are §15.4.1 JSONL frames carried verbatim as JSON
	// bytes, mirroring SendMessage.envelope_json.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachClientMessage, AttachServerMessage], error)
	// AssignCredentials pushes a per-session credential lease map to the
	// adapter. Adapter writes the credential file under /run/lenny/. Atomic
	// across providers; partial failures are rolled back.
	AssignCredentials(ctx context.Context, in *AssignCredentialsRequest, opts ...grpc.CallOption) (*AssignCredentialsResponse, error)
	// RotateCredentials replaces a previously assigned credential lease with
	// a new lease. Emits a `credentials_rotated` lifecycle event to the
	// agent. Used for hot rotation without pod restart.
	RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error)
	// RevokeCredentials removes a credential lease immediately. The agent
	// receives no chance to drain in-flight requests; emergency revocation.
	RevokeCredentials(ctx context.Context, in *RevokeCredentialsRequest, opts ...grpc.CallOption) (*RevokeCredentialsResponse, error)
	// Interrupt asks the agent to pause and (optionally) checkpoint. Two
	// modes: clean (graceful, with deadline) and hard (SIGTERM/SIGKILL).
	Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error)
	// Checkpoint requests an immediate checkpoint of the current session
	// state to the artifact store. Used for eviction, drain, and session
	// suspend.
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// ReportUsage returns token-usage and time-usage accounting since the
	// last call. The gateway uses this for budget enforcement and billing.
	ReportUsage(ctx context.Context, in *ReportUsageRequest, opts ...grpc.CallOption) (*ReportUsageResponse, error)
	// ExtendLease is the adapter's request to the gateway for additional
	// token budget when the current session lease is about to expire.
	// Response carries one of GRANTED, PARTIALLY_GRANTED, CEILING_REACHED,
	// REJECTED (see spec §8.6).
	ExtendLease(ctx context.Context, in *ExtendLeaseRequest, opts ...grpc.CallOption) (*ExtendLeaseResponse, error)
	// Shutdown asks the adapter to terminate the agent and release the pod.
	// The adapter forwards a JSONL `shutdown` to the agent with the supplied
	// deadline. Returns when the agent process has exited.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// DemoteSDK is required for runtimes that declare
	// `capabilities.preConnect: true`. The gateway calls DemoteSDK when an
	// SDK-warm pod's incoming WorkspacePlan matches a `sdkWarmBlockingPaths`
	// pattern, instructing the adapter to tear down the pre-connected SDK
	// and demote the pod to pod-warm before workspace materialization
	// proceeds. Pods without preConnect: true return Unimplemented.
	// Spec: §4.7, §6.1, §15.4.
	DemoteSDK(ctx context.Context, in *DemoteSDKRequest, opts ...grpc.CallOption) (*DemoteSDKResponse, error)
	// NegotiateVersion is called once per gateway↔adapter handshake.
	// The adapter advertises the protocol versions and capabilities it
	// supports; the gateway selects a compatible version. Subsequent
	// RPCs assume the negotiated version. See spec §15.5 (versioning).
	NegotiateVersion(ctx context.Context, in *NegotiateVersionRequest, opts ...grpc.CallOption) (*NegotiateVersionResponse, error)
	// LifecycleChannel is a bidirectional stream the adapter uses to surface
	// Full-level lifecycle events (checkpoint_ready, interrupt_acknowledged,
	// credentials_acknowledged, deadline_approaching). See spec §15.4 for
	// the event taxonomy.
	LifecycleChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LifecycleChannelRequest, LifecycleChannelResponse], error)
}

type adapterClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterClient(cc grpc.ClientConnInterface) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, Adapter_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Adapter_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachClientMessage, AttachServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[0], Adapter_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachClientMessage, AttachServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AttachClient = grpc.BidiStreamingClient[AttachClientMessage, AttachServerMessage]

func (c *adapterClient) AssignCredentials(ctx context.Context, in *AssignCredentialsRequest, opts ...grpc.CallOption) (*AssignCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignCredentialsResponse)
	err := c.cc.Invoke(ctx, Adapter_AssignCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCredentialsResponse)
	err := c.cc.Invoke(ctx, Adapter_RotateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) RevokeCredentials(ctx context.Context, in *RevokeCredentialsRequest, opts ...grpc.CallOption) (*RevokeCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialsResponse)
	err := c.cc.Invoke(ctx, Adapter_RevokeCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterruptResponse)
	err := c.cc.Invoke(ctx, Adapter_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, Adapter_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ReportUsage(ctx context.Context, in *ReportUsageRequest, opts ...grpc.CallOption) (*ReportUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportUsageResponse)
	err := c.cc.Invoke(ctx, Adapter_ReportUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) ExtendLease(ctx context.Context, in *ExtendLeaseRequest, opts ...grpc.CallOption) (*ExtendLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendLeaseResponse)
	err := c.cc.Invoke(ctx, Adapter_ExtendLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, Adapter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) DemoteSDK(ctx context.Context, in *DemoteSDKRequest, opts ...grpc.CallOption) (*DemoteSDKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoteSDKResponse)
	err := c.cc.Invoke(ctx, Adapter_DemoteSDK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) NegotiateVersion(ctx context.Context, in *NegotiateVersionRequest, opts ...grpc.CallOption) (*NegotiateVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiateVersionResponse)
	err := c.cc.Invoke(ctx, Adapter_NegotiateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) LifecycleChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LifecycleChannelRequest, LifecycleChannelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Adapter_ServiceDesc.Streams[1], Adapter_LifecycleChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LifecycleChannelRequest, LifecycleChannelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_LifecycleChannelClient = grpc.BidiStreamingClient[LifecycleChannelRequest, LifecycleChannelResponse]

// AdapterServer is the server API for Adapter service.
// All implementations should embed UnimplementedAdapterServer
// for forward compatibility.
//
// Adapter is the long-running gRPC server hosted by the adapter sidecar
// inside every Lenny pod. The gateway connects over mTLS and uses it for
// session lifecycle, credential delivery, interrupt control, checkpoint
// orchestration, and usage reporting. Pod → gateway traffic is initiated
// by the gateway only; the adapter responds to RPCs and emits structured
// events via a separate streaming RPC (the lifecycle channel).
type AdapterServer interface {
	// StartSession assigns a session to this pod. Workspace materialization
	// (per the supplied WorkspacePlan) and setup-command execution happen
	// before the response. Returns Unavailable if the pod is not in `idle`
	// state.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// SendMessage delivers a content message to the agent over the adapter's
	// stdin JSONL channel. See lenny-adapter-jsonl.schema.json `message`.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Attach opens the bidirectional content stream between the gateway and a
	// running session (spec §4.7 RPC table: "Connect client stream to running
	// session"). The gateway streams client-to-agent envelopes in; the adapter
	// streams the agent's response, tool-call, and status envelopes back.
	// Envelope payloads are §15.4.1 JSONL frames carried verbatim as JSON
	// bytes, mirroring SendMessage.envelope_json.
	Attach(grpc.BidiStreamingServer[AttachClientMessage, AttachServerMessage]) error
	// AssignCredentials pushes a per-session credential lease map to the
	// adapter. Adapter writes the credential file under /run/lenny/. Atomic
	// across providers; partial failures are rolled back.
	AssignCredentials(context.Context, *AssignCredentialsRequest) (*AssignCredentialsResponse, error)
	// RotateCredentials replaces a previously assigned credential lease with
	// a new lease. Emits a `credentials_rotated` lifecycle event to the
	// agent. Used for hot rotation without pod restart.
	RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error)
	// RevokeCredentials removes a credential lease immediately. The agent
	// receives no chance to drain in-flight requests; emergency revocation.
	RevokeCredentials(context.Context, *RevokeCredentialsRequest) (*RevokeCredentialsResponse, error)
	// Interrupt asks the agent to pause and (optionally) checkpoint. Two
	// modes: clean (graceful, with deadline) and hard (SIGTERM/SIGKILL).
	Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error)
	// Checkpoint requests an immediate checkpoint of the current session
	// state to the artifact store. Used for eviction, drain, and session
	// suspend.
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// ReportUsage returns token-usage and time-usage accounting since the
	// last call. The gateway uses this for budget enforcement and billing.
	ReportUsage(context.Context, *ReportUsageRequest) (*ReportUsageResponse, error)
	// ExtendLease is the adapter's request to the gateway for additional
	// token budget when the current session lease is about to expire.
	// Response carries one of GRANTED, PARTIALLY_GRANTED, CEILING_REACHED,
	// REJECTED (see spec §8.6).
	ExtendLease(context.Context, *ExtendLeaseRequest) (*ExtendLeaseResponse, error)
	// Shutdown asks the adapter to terminate the agent and release the pod.
	// The adapter forwards a JSONL `shutdown` to the agent with the supplied
	// deadline. Returns when the agent process has exited.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// DemoteSDK is required for runtimes that declare
	// `capabilities.preConnect: true`. The gateway calls DemoteSDK when an
	// SDK-warm pod's incoming WorkspacePlan matches a `sdkWarmBlockingPaths`
	// pattern, instructing the adapter to tear down the pre-connected SDK
	// and demote the pod to pod-warm before workspace materialization
	// proceeds. Pods without preConnect: true return Unimplemented.
	// Spec: §4.7, §6.1, §15.4.
	DemoteSDK(context.Context, *DemoteSDKRequest) (*DemoteSDKResponse, error)
	// NegotiateVersion is called once per gateway↔adapter handshake.
	// The adapter advertises the protocol versions and capabilities it
	// supports; the gateway selects a compatible version. Subsequent
	// RPCs assume the negotiated version. See spec §15.5 (versioning).
	NegotiateVersion(context.Context, *NegotiateVersionRequest) (*NegotiateVersionResponse, error)
	// LifecycleChannel is a bidirectional stream the adapter uses to surface
	// Full-level lifecycle events (checkpoint_ready, interrupt_acknowledged,
	// credentials_acknowledged, deadline_approaching). See spec §15.4 for
	// the event taxonomy.
	LifecycleChannel(grpc.BidiStreamingServer[LifecycleChannelRequest, LifecycleChannelResponse]) error
}

// UnimplementedAdapterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterServer struct{}

func (UnimplementedAdapterServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedAdapterServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAdapterServer) Attach(grpc.BidiStreamingServer[AttachClientMessage, AttachServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedAdapterServer) AssignCredentials(context.Context, *AssignCredentialsRequest) (*AssignCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCredentials not implemented")
}
func (UnimplementedAdapterServer) RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCredentials not implemented")
}
func (UnimplementedAdapterServer) RevokeCredentials(context.Context, *RevokeCredentialsRequest) (*RevokeCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCredentials not implemented")
}
func (UnimplementedAdapterServer) Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedAdapterServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedAdapterServer) ReportUsage(context.Context, *ReportUsageRequest) (*ReportUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUsage not implemented")
}
func (UnimplementedAdapterServer) ExtendLease(context.Context, *ExtendLeaseRequest) (*ExtendLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendLease not implemented")
}
func (UnimplementedAdapterServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAdapterServer) DemoteSDK(context.Context, *DemoteSDKRequest) (*DemoteSDKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DemoteSDK not implemented")
}
func (UnimplementedAdapterServer) NegotiateVersion(context.Context, *NegotiateVersionRequest) (*NegotiateVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NegotiateVersion not implemented")
}
func (UnimplementedAdapterServer) LifecycleChannel(grpc.BidiStreamingServer[LifecycleChannelRequest, LifecycleChannelResponse]) error {
	return status.Error(codes.Unimplemented, "method LifecycleChannel not implemented")
}
func (UnimplementedAdapterServer) testEmbeddedByValue() {}

// UnsafeAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterServer will
// result in compilation errors.
type UnsafeAdapterServer interface {
	mustEmbedUnimplementedAdapterServer()
}

func RegisterAdapterServer(s grpc.ServiceRegistrar, srv AdapterServer) {
	// If the following call panics, it indicates UnimplementedAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Adapter_ServiceDesc, srv)
}

func _Adapter_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).Attach(&grpc.GenericServerStream[AttachClientMessage, AttachServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_AttachServer = grpc.BidiStreamingServer[AttachClientMessage, AttachServerMessage]

func _Adapter_AssignCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).AssignCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_AssignCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).AssignCredentials(ctx, req.(*AssignCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_RotateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).RotateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_RotateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).RotateCredentials(ctx, req.(*RotateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_RevokeCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).RevokeCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_RevokeCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).RevokeCredentials(ctx, req.(*RevokeCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Interrupt(ctx, req.(*InterruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_ReportUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ReportUsage(ctx, req.(*ReportUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_ExtendLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ExtendLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_ExtendLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ExtendLease(ctx, req.(*ExtendLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_DemoteSDK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoteSDKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).DemoteSDK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_DemoteSDK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).DemoteSDK(ctx, req.(*DemoteSDKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_NegotiateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).NegotiateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Adapter_NegotiateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).NegotiateVersion(ctx, req.(*NegotiateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_LifecycleChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdapterServer).LifecycleChannel(&grpc.GenericServerStream[LifecycleChannelRequest, LifecycleChannelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Adapter_LifecycleChannelServer = grpc.BidiStreamingServer[LifecycleChannelRequest, LifecycleChannelResponse]

// Adapter_ServiceDesc is the grpc.ServiceDesc for Adapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Adapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lenny.adapter.v1.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _Adapter_StartSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Adapter_SendMessage_Handler,
		},
		{
			MethodName: "AssignCredentials",
			Handler:    _Adapter_AssignCredentials_Handler,
		},
		{
			MethodName: "RotateCredentials",
			Handler:    _Adapter_RotateCredentials_Handler,
		},
		{
			MethodName: "RevokeCredentials",
			Handler:    _Adapter_RevokeCredentials_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _Adapter_Interrupt_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Adapter_Checkpoint_Handler,
		},
		{
			MethodName: "ReportUsage",
			Handler:    _Adapter_ReportUsage_Handler,
		},
		{
			MethodName: "ExtendLease",
			Handler:    _Adapter_ExtendLease_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Adapter_Shutdown_Handler,
		},
		{
			MethodName: "DemoteSDK",
			Handler:    _Adapter_DemoteSDK_Handler,
		},
		{
			MethodName: "NegotiateVersion",
			Handler:    _Adapter_NegotiateVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _Adapter_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LifecycleChannel",
			Handler:       _Adapter_LifecycleChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lenny-adapter.proto",
}
