// SPDX-License-Identifier: MIT

// Tier-11 documentation/consistency check for proposal 0017 (re-architect
// §17.4 Embedded Mode to run the production gateway and controllers as
// in-cluster pods rendered from the chart). These tests are NOT under a
// build tag because they exercise the repository state directly: they
// re-render the chart and diff against the embedded manifests, the same
// no-drift obligation the embedded CRDs already carry
// (pkg/embedded/crds/crds_test.go).
//
// The §17.4 in-cluster control plane is applied from pre-rendered
// manifests so the `lenny` CLI carries no Helm SDK. `make generate` runs
// `helm template --no-hooks` over charts/lenny under the development
// profile and writes pkg/embedded/manifests/manifests.yaml. This file is
// the regression guard that the committed manifests match a fresh render
// and that no helm.sh/hook-annotated resource leaked into the embedded
// set. A failure means the embedded manifests drifted from the chart;
// run `make generate` and commit the result.

package tier11_docs_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// embeddedManifestHeader is the byte-identical header `make generate`
// prepends to the rendered stream. Keep this in lockstep with the
// EMBEDDED_MANIFEST_HEADER define in the Makefile; the sync check
// reconstructs the full file (header + render) and diffs it against the
// committed copy.
const embeddedManifestHeader = "# Code generated by 'make generate' (helm template --no-hooks); DO NOT EDIT.\n" +
	"# Source: charts/lenny rendered under charts/lenny/presets/dev.yaml.\n" +
	"# Regenerate with 'make generate'. The tier-11 sync check\n" +
	"# (TestEmbeddedManifestsMatchDevProfileRender) fails on any drift.\n" +
	"# spec: §17.4 (pre-rendered embedded manifests).\n"

const (
	embeddedManifestRel = "pkg/embedded/manifests/manifests.yaml"
	embeddedDevProfile  = "charts/lenny/presets/dev.yaml"
)

// helmBinary returns the helm binary the render uses, honoring the same
// LENNY_HELM_BIN override the tests/testinfra/helm helper accepts.
func helmBinary() string {
	if v := os.Getenv("LENNY_HELM_BIN"); v != "" {
		return v
	}
	return "helm"
}

// renderDevProfile shells out to `helm template --no-hooks` with the
// exact arguments the Makefile `generate` target uses, so the test render
// is byte-identical to what `make generate` writes.
func renderDevProfile(t *testing.T, root string) []byte {
	t.Helper()
	if _, err := exec.LookPath(helmBinary()); err != nil {
		t.Skipf("helm not on PATH (%v); skipping embedded-manifest sync check", err)
	}
	cmd := exec.Command(
		helmBinary(),
		"template", "lenny", "charts/lenny",
		"-f", embeddedDevProfile,
		"--no-hooks",
	)
	cmd.Dir = root
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("helm template --no-hooks failed: %v\nstderr:\n%s", err, stderr.String())
	}
	return append([]byte(embeddedManifestHeader), stdout.Bytes()...)
}

// TestEmbeddedManifestsMatchDevProfileRender pins the no-drift invariant
// the manifests package documents: pkg/embedded/manifests/manifests.yaml
// is byte-for-byte a `helm template --no-hooks` render of charts/lenny
// under the development profile. A drift means the embedded control-plane
// manifests no longer match the chart, so Embedded Mode would apply stale
// gateway/controller/RBAC objects. Regenerate with `make generate`.
//
// spec: §17.4 (pre-rendered embedded manifests).
func TestEmbeddedManifestsMatchDevProfileRender_spec_17_4(t *testing.T) {
	root := repoRoot(t)
	committed, err := os.ReadFile(filepath.Join(root, embeddedManifestRel))
	if err != nil {
		t.Fatalf("read embedded manifests %s: %v", embeddedManifestRel, err)
	}
	fresh := renderDevProfile(t, root)
	if !bytes.Equal(committed, fresh) {
		t.Errorf("%s drifted from a fresh `helm template --no-hooks` render of charts/lenny -f %s; run `make generate` and commit the result",
			embeddedManifestRel, embeddedDevProfile)
		// Surface the first divergent line to make the drift diagnosable
		// without re-rendering by hand.
		cLines := strings.Split(string(committed), "\n")
		fLines := strings.Split(string(fresh), "\n")
		n := len(cLines)
		if len(fLines) < n {
			n = len(fLines)
		}
		for i := 0; i < n; i++ {
			if cLines[i] != fLines[i] {
				t.Errorf("first divergence at line %d:\n  committed: %q\n  rendered:  %q", i+1, cLines[i], fLines[i])
				break
			}
		}
		if len(cLines) != len(fLines) {
			t.Errorf("line count differs: committed=%d rendered=%d", len(cLines), len(fLines))
		}
	}
}

// TestEmbeddedManifestsCarryNoHelmHook verifies the §17.4 decision that
// no helm.sh/hook-annotated resource (bootstrap, preflight, migrate, the
// post-upgrade CRD-validate and deployment-config-sync Jobs, the
// MinIO-lifecycle Job, and the Redis-cluster hook) enters the embedded
// set. A plain server-side apply has no Helm install/upgrade engine, so a
// leaked hook resource would be created as an ordinary object and run
// against the embedded stack. The `--no-hooks` render must keep them out.
//
// spec: §17.4 (pre-rendered embedded manifests).
func TestEmbeddedManifestsCarryNoHelmHook_spec_17_4(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, embeddedManifestRel))
	if err != nil {
		t.Fatalf("read embedded manifests %s: %v", embeddedManifestRel, err)
	}
	for i, line := range strings.Split(string(raw), "\n") {
		if strings.Contains(line, "helm.sh/hook") {
			t.Errorf("%s line %d carries a helm.sh/hook annotation; the embedded set must be rendered with --no-hooks: %q",
				embeddedManifestRel, i+1, strings.TrimSpace(line))
		}
	}
}

// TestEmbeddedManifestsCarryNoCertManager verifies the §17.4 decision
// that the disabled admission/mTLS stack renders no cert-manager.io
// object into the embedded set. A bare k3s has no cert-manager CA
// injector, so a leaked cert-manager.io/v1 object would fail the dynamic
// applier's GVR resolution and abort bring-up, contradicting the §17.4
// "no cert-manager" requirement.
//
// spec: §17.4 (pre-rendered embedded manifests).
func TestEmbeddedManifestsCarryNoCertManager_spec_17_4(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, embeddedManifestRel))
	if err != nil {
		t.Fatalf("read embedded manifests %s: %v", embeddedManifestRel, err)
	}
	for i, line := range strings.Split(string(raw), "\n") {
		if strings.Contains(line, "cert-manager.io/") {
			t.Errorf("%s line %d references cert-manager.io; the development profile disables the admission/mTLS stack so no cert-manager object may enter the embedded set: %q",
				embeddedManifestRel, i+1, strings.TrimSpace(line))
		}
	}
}
