// SPDX-License-Identifier: MIT

// Command genmcpschemas is the build-pipeline code generation step §15.2.1
// rule 4 mandates: it produces the MCP tool input JSON schemas for the
// operations that overlap the REST API from the canonical OpenAPI document,
// writing them to generated_schemas.go in the mcptools package.
//
// Run it via `go generate ./pkg/gateway/mcptools/...` after editing the
// OpenAPI document or the overlap registry. The drift-guard test
// (TestGeneratedSchemasMatchOpenAPI) fails the build if the committed
// output diverges from a fresh generation, so the generated schemas stay
// structurally consistent with OpenAPI by construction.
//
// spec: §15.2.1 rule 4 line 1386.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/lennylabs/lenny/pkg/gateway/mcpfabric/mcpschemagen"
	"github.com/lennylabs/lenny/pkg/gateway/openapi"
)

const outputFile = "generated_schemas.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genmcpschemas:", err)
		os.Exit(1)
	}
}

func run() error {
	doc := openapi.Document()

	overlaps := mcpschemagen.DefaultOverlaps()
	sort.Slice(overlaps, func(i, j int) bool { return overlaps[i].ToolName < overlaps[j].ToolName })

	var body bytes.Buffer
	fmt.Fprint(&body, header)
	for _, ov := range overlaps {
		schema, err := mcpschemagen.BuildToolInputSchema(doc, ov.OperationID, ov.Options)
		if err != nil {
			return fmt.Errorf("build schema for %s (%s): %w", ov.ToolName, ov.OperationID, err)
		}
		fmt.Fprintf(&body, "\n// %s is generated from the OpenAPI operation %q\n// (MCP tool %q). spec: §15.2.1 rule 4 line 1386.\nvar %s = json.RawMessage(%s)\n",
			varName(ov.ToolName), ov.OperationID, ov.ToolName, varName(ov.ToolName), backtick(string(schema)))
	}

	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w\n%s", err, body.String())
	}
	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputFile, err)
	}
	fmt.Fprintf(os.Stderr, "genmcpschemas: wrote %d schema(s) to %s\n", len(overlaps), outputFile)
	return nil
}

// varName maps an MCP tool name to the exported generated variable name:
// "lenny/create_session" -> "GeneratedCreateSessionInputSchema".
func varName(tool string) string {
	name := tool
	if i := strings.IndexByte(name, '/'); i >= 0 {
		name = name[i+1:]
	}
	parts := strings.Split(name, "_")
	var b strings.Builder
	b.WriteString("Generated")
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	b.WriteString("InputSchema")
	return b.String()
}

func backtick(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}

const header = `// SPDX-License-Identifier: MIT

// Code generated by genmcpschemas; DO NOT EDIT.
//
// The MCP tool input schemas below are generated from the gateway OpenAPI
// document by the build-pipeline code generation step §15.2.1 rule 4
// mandates. Regenerate with: go generate ./pkg/gateway/mcptools/...
//
// spec: §15.2.1 rule 4 line 1386.

package mcptools

import "encoding/json"
`
