#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# scripts/cloud/gcp/render-values.sh — emit a Helm values overlay
# pointing the Lenny chart at the Artifact Registry images and the
# Terraform-emitted GCP resources.
#
# Mirrors scripts/cloud/aws/render-values.sh. The overlay defaults
# the gateway at the in-cluster lenny-postgres / lenny-redis fixtures,
# and routes through Cloud SQL + Memorystore when LENNY_POSTGRES_DSN /
# LENNY_REDIS_URL are set (the tier-7 cloud-load path composes these
# from Secret Manager entries emitted by managed-services.tf).
#
# Required environment:
#
#   AR_REGISTRY                          Artifact Registry host, e.g.
#                                        us-central1-docker.pkg.dev/acme/lenny.
#
# Optional environment:
#
#   IMAGE_TAG                            Default 0.1.0.
#   LENNY_POSTGRES_DSN                   Override in-cluster default.
#   LENNY_REDIS_URL                      Override in-cluster default.
#   LENNY_GCP_SERVICE_ACCOUNT_EMAIL      Adds the iam.gke.io/gcp-service-account
#                                        annotation to the gateway SA.

set -euo pipefail

if [[ -z "${AR_REGISTRY:-}" ]]; then
  echo "render-values.sh: AR_REGISTRY is required" >&2
  exit 2
fi

TAG="${IMAGE_TAG:-0.1.0}"
OUT="${1:-/dev/stdout}"
SA_EMAIL="${LENNY_GCP_SERVICE_ACCOUNT_EMAIL:-}"

if [[ -n "${SA_EMAIL}" ]]; then
  GATEWAY_SA_BLOCK=$'  serviceAccount:\n    annotations:\n      iam.gke.io/gcp-service-account: "'"${SA_EMAIL}"'"'
else
  GATEWAY_SA_BLOCK=""
fi

cat > "${OUT}" <<YAML
# SPDX-License-Identifier: MIT
#
# Generated by scripts/cloud/gcp/render-values.sh. Overrides the
# chart's default ghcr.io image registry with the per-release
# Artifact Registry, and points the gateway / artifact store at the
# Terraform-provisioned GCP resources. Re-render between runs; do
# not check in.

global:
  devMode: true

controller:
  image:
    repository: ${AR_REGISTRY}/lenny-controller
    tag: "${TAG}"
    pullPolicy: IfNotPresent
  adapterImage: ${AR_REGISTRY}/lenny-adapter:${TAG}

admissionWebhooks:
  image:
    repository: ${AR_REGISTRY}/lenny-webhook
    tag: "${TAG}"
    pullPolicy: IfNotPresent

tokenService:
  image:
    repository: ${AR_REGISTRY}/lenny-token-service
    tag: "${TAG}"
    pullPolicy: IfNotPresent

gateway:
  image:
    repository: ${AR_REGISTRY}/lenny-gateway
    tag: "${TAG}"
    pullPolicy: IfNotPresent
${GATEWAY_SA_BLOCK}

observability:
  otlpEndpoint: "http://adot-collector.lenny-system.svc:4317"

billing:
  sink: "postgres"

ops:
  image:
    repository: ${AR_REGISTRY}/lenny-ops
    tag: "${TAG}"
    pullPolicy: IfNotPresent

preflight:
  image:
    repository: ${AR_REGISTRY}/lenny-preflight
    tag: "${TAG}"
    pullPolicy: IfNotPresent

backups:
  image:
    repository: ${AR_REGISTRY}/lenny-backup
    tag: "${TAG}"
    pullPolicy: IfNotPresent

bootstrap:
  image:
    repository: ${AR_REGISTRY}/lenny-ctl
    tag: "${TAG}"
    pullPolicy: IfNotPresent
  # Seed the tenant + user the tier-6 e2e_cloud and tier-7 cloud-load
  # tests authenticate as. Without these the gateway's §4.8
  # QuotaEvaluator returns 429 QUOTA_EXCEEDED on every request
  # bearing X-Lenny-Tenant-ID: acme because no tenant row exists
  # for the quota lookup.
  tenants:
    - id: acme
      displayName: Acme Corp
      workspaceTier: standard
  users:
    - subject: alice@acme.com
      tenantId: acme
      email: alice@acme.com
      roles: [tenant-admin]

postgres:
  dsn: "${LENNY_POSTGRES_DSN:-postgres://lenny:lenny@lenny-postgres.lenny-system.svc:5432/lenny?sslmode=disable}"
  # When the gateway routes to a managed Postgres, the chart's
  # default-deny NetworkPolicy blocks the external connection
  # unless a CIDR egress rule is added. Empty default keeps the
  # rule absent on the in-cluster-fixture path. Tier-7 cloud-load
  # on GCP exports POSTGRES_GATEWAY_EGRESS_CIDR with the VPC CIDR
  # so the gateway can reach the Cloud SQL private IP.
  gatewayEgressCIDR: "${POSTGRES_GATEWAY_EGRESS_CIDR:-}"

redis:
  url: "${LENNY_REDIS_URL:-redis://lenny-redis.lenny-system.svc:6379}"
  gatewayEgressCIDR: "${REDIS_GATEWAY_EGRESS_CIDR:-}"
  gatewayEgressPort: ${REDIS_GATEWAY_EGRESS_PORT:-6379}
YAML

if [[ "${OUT}" != "/dev/stdout" ]]; then
  echo "render-values.sh: wrote ${OUT}" >&2
fi
