// SPDX-License-Identifier: MIT

package main

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

// TestScanLongFuncs exercises the advisory long-funcs analyzer against a
// crafted source tree: a function over threshold is reported with the correct
// body span, a short function is not, and test files and generated files are
// excluded.
func TestScanLongFuncs(t *testing.T) {
	root := t.TempDir()
	pkg := filepath.Join(root, "pkg", "demo")
	if err := os.MkdirAll(pkg, 0o755); err != nil {
		t.Fatal(err)
	}

	// long: opening brace on line 3, closing brace on line 9, so the body
	// spans 7 lines inclusive. short: body spans 3 lines.
	src := `package demo

func long() {
	a := 1
	b := 2
	c := 3
	d := 4
	_ = a + b + c + d
}

func short() {
	return
}
`
	writeFile(t, filepath.Join(pkg, "code.go"), src)
	// A test file with a long function must be excluded.
	writeFile(t, filepath.Join(pkg, "code_test.go"), src)
	// A generated file with a long function must be excluded.
	writeFile(t, filepath.Join(pkg, "zz_generated.go"),
		"// Code generated by fake. DO NOT EDIT.\n"+src)

	findings, err := scanLongFuncs(root, []string{"pkg"}, 5)
	if err != nil {
		t.Fatalf("scanLongFuncs: %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	got := findings[0]
	if got.Name != "long" {
		t.Errorf("name = %q, want \"long\"", got.Name)
	}
	if got.BodyLen != 7 {
		t.Errorf("body_len = %d, want 7", got.BodyLen)
	}
	if got.File != filepath.Join("pkg", "demo", "code.go") {
		t.Errorf("file = %q, want repo-relative pkg/demo/code.go", got.File)
	}
}

// TestLongFuncsThresholdBoundary confirms the threshold is exclusive: a body
// exactly at the threshold is not reported, one line over is.
func TestLongFuncsThresholdBoundary(t *testing.T) {
	fset := token.NewFileSet()
	dir := t.TempDir()
	// Body braces on lines 3 and 6 -> body_len 4.
	src := `package demo

func f() {
	a := 1
	_ = a
}
`
	path := filepath.Join(dir, "f.go")
	writeFile(t, path, src)

	if out, err := longFuncsInFile(fset, path, 4); err != nil || len(out) != 0 {
		t.Fatalf("threshold 4 (== body): got %d findings (err=%v), want 0", len(out), err)
	}
	if out, err := longFuncsInFile(fset, path, 3); err != nil || len(out) != 1 {
		t.Fatalf("threshold 3 (< body): got %d findings (err=%v), want 1", len(out), err)
	}
}

// TestFuncDeclNameReceiver confirms method findings carry their receiver type
// so two methods with the same name on different types stay distinct.
func TestFuncDeclNameReceiver(t *testing.T) {
	fset := token.NewFileSet()
	dir := t.TempDir()
	src := `package demo

type T struct{}

func (t *T) Method() {
	a := 1
	b := 2
	_ = a + b
}

func plain() {
	a := 1
	b := 2
	_ = a + b
}
`
	path := filepath.Join(dir, "m.go")
	writeFile(t, path, src)
	out, err := longFuncsInFile(fset, path, 2)
	if err != nil {
		t.Fatal(err)
	}
	names := map[string]bool{}
	for _, f := range out {
		names[f.Name] = true
	}
	if !names["(*T).Method"] {
		t.Errorf("missing receiver-qualified method name; got %v", names)
	}
	if !names["plain"] {
		t.Errorf("missing plain function name; got %v", names)
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
