// SPDX-License-Identifier: MIT

package scope

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"path/filepath"
	"regexp"
	"strings"
)

// Disjunct names which half of the generated-artifact rule selected a
// file. The rule is a union of three signals, and a caller that has to
// justify an exclusion reports which one fired.
type Disjunct string

// The disjuncts of the generated-artifact rule.
const (
	// NotGenerated means no disjunct selected the file.
	NotGenerated Disjunct = ""
	// HeaderMarker is a generation declaration in the file header.
	HeaderMarker Disjunct = "header-marker"
	// DocumentMetadata is a generation declaration in top-level document
	// metadata, for a format that carries no comment syntax.
	DocumentMetadata Disjunct = "document-metadata"
	// ProducerOutput is membership in the output set of a named producer.
	ProducerOutput Disjunct = "producer-output"
)

// Producer is one generator whose output the passes never write. The
// output sets are held as data so the rule is decidable without running
// a producer, which is what lets a tier-0 gate apply it.
type Producer struct {
	// Command is the invocation that regenerates the outputs.
	Command string
	// Source names what the producer reads, so the sub-step that
	// rewrites a source knows which producer to run.
	Source string
	// Outputs are repo-relative paths. An entry ending in a slash names
	// a directory subtree; any other entry names one file.
	Outputs []string
	// MirrorOf, when set, names the source directory a copying producer
	// mirrors, and qualifies every directory entry in Outputs: a file
	// under such a directory is producer output only when a file of the
	// same name exists under MirrorOf.
	//
	// A copy target directory holds authored files beside the copies.
	// pkg/embedded/crds/ holds the embedding package's own source and its
	// test alongside the five copied manifests, and that test carries
	// line citations. Selecting the whole directory would take those
	// authored files out of every pass's write domain while the citation
	// gates keep counting them, which is what leaves the per-file count
	// unable to reach zero.
	MirrorOf string
}

// producers is the producer list the generated-artifact rule's third
// disjunct ranges over. The third disjunct is necessary rather than
// redundant: the CRDs under charts/lenny/crds/ and their copies under
// pkg/embedded/crds/ are controller-gen and copy output that carries
// neither a header generation declaration nor a document-metadata one,
// so a marker-only rule would classify them as ordinary carriers and
// direct a pass to write them.
var producers = []Producer{
	{
		Command: "make generate",
		Source:  "charts/lenny/templates and pkg/apis/lenny/v1alpha1",
		Outputs: []string{
			"pkg/embedded/manifests/manifests.yaml",
			"charts/lenny/crds/",
			"pkg/ops/mcp/generated_tools.go",
			"docs/alerting/rules.yaml",
			"docs/alerting/routing-recommendations.md",
		},
	},
	{
		Command:  "the chart-to-embedded CRD copy",
		Source:   "charts/lenny/crds",
		Outputs:  []string{"pkg/embedded/crds/"},
		MirrorOf: "charts/lenny/crds/",
	},
	{
		Command: "make generate-proto",
		Source:  "schemas/*.proto",
		Outputs: []string{"pkg/proto/"},
	},
	{
		Command: "go generate ./pkg/gateway/mcpfabric/mcptools/...",
		Source:  "pkg/gateway/externalapi/openapi/openapi.json",
		Outputs: []string{"pkg/gateway/mcpfabric/mcptools/generated_schemas.go"},
	},
	{
		Command: "go run ./cmd/lenny-chart-schema-gen",
		Source:  "pkg/chart/values/values.go",
		Outputs: []string{"charts/lenny/values.schema.json"},
	},
	{
		Command: "go run ./cmd/lenny-ocsf-mapping-gen",
		Source:  "pkg/audit/ocsf/catalog.go",
		Outputs: []string{"schemas/ocsf-mapping.yaml"},
	},
}

// Producers returns the producer list the rule's third disjunct reads.
func Producers() []Producer {
	out := make([]Producer, 0, len(producers))
	for _, p := range producers {
		copied := p
		copied.Outputs = append([]string(nil), p.Outputs...)
		out = append(out, copied)
	}
	return out
}

// generationDeclaration matches the declaration form of a generation
// notice, anchored to the start of a comment body or to a sentence
// boundary inside it.
//
// The anchoring is what separates a declaration from prose. A file the
// rule wrongly classifies as generated is removed from every pass's
// write domain with no route back: the residual gate can record the
// misclassification, but an excluded triage does not return the file to
// a write domain, so its per-file citation count can never reach zero.
// A sentence such as "caches generated by running the SDK" in an
// authored file therefore must not select it.
var generationDeclaration = regexp.MustCompile(`(?i)(?:^|[.;:!]\s+)(?:code generated\b|(?:auto-?generated|generated)\s+(?:by|from)\b|do not edit\b)`)

// metadataDeclaration matches the declaration form of a generation
// notice inside a top-level document-metadata value, anchored to the
// start of the value or to a sentence or clause boundary inside it.
//
// The anchoring carries the same argument the header disjunct's does. A
// metadata value is prose, so a description that mentions generation in
// passing ("schema for plans generated from the session plan") must not
// select the file: the misclassification removes it from every pass's
// write domain with no route back while the citation gates keep counting
// it. A declaration about the document opens its own clause, as
// charts/lenny/values.schema.json's does.
var metadataDeclaration = regexp.MustCompile(`(?i)(?:^|[.;:!,]\s+)(?:code generated\b|(?:auto-?generated|generated)\s+(?:by|from)\b|do not edit\b)`)

// headerFloor is the number of leading lines the header disjunct always
// reads, whatever those lines carry. It keeps a declaration that sits
// just below an opening heading or an opening data key in scope, which a
// scan bounded strictly by the leading comment block would drop.
//
// Beyond the floor the scan continues while the file is still inside its
// leading run of comment and blank lines, and stops at the first line
// that is neither. Reading the header block to its end rather than to a
// fixed line count is what keeps this predicate over-broad, which is the
// direction the rule has to err in: a header carries a licence line and
// a multi-line doc comment above its generation marker often enough that
// a fixed window cuts the marker off, and the file then enters every
// pass's write domain as an ordinary carrier and matches no residual
// class either. Every protoc-generated stub in this tree carries its
// marker below the twelfth line.
const headerFloor = 12

// lineCommentPrefixes are the comment markers the header disjunct
// accepts, which are the carrier dialects the citation form's
// continuation join already names, plus the opening of a block comment.
// The declaration has to sit on a comment line: a generation phrase in
// body prose or in data is not a declaration that the file is derived.
var lineCommentPrefixes = []string{"//", "/*", "*", "#", "--", ";"}

// markupFormats are the extensions whose only comment syntax is the HTML
// comment. In markdown a leading `#` is a heading rather than a comment,
// so the header disjunct reads a declaration only inside `<!-- ... -->`.
var markupFormats = map[string]bool{".md": true, ".markdown": true, ".html": true, ".htm": true}

// commentlessFormats are the extensions whose format carries no comment
// syntax, so a generation declaration has nowhere to sit but the
// document's own metadata.
var commentlessFormats = map[string]bool{".json": true}

// metadataField is the top-level document-metadata field a commentless
// format declares generation in. It is the one field the rule reads:
// widening it to further prose fields widens the irreversible exclusion
// the rule imposes.
const metadataField = "description"

// Generated applies the per-file generated-artifact rule and reports
// which disjunct selected the file. The rule is the union of a header
// generation marker, a top-level document-metadata generation
// declaration for a format with no comment syntax, and membership in
// the output set of a named producer.
//
// The rule is applied per file rather than per directory, because
// excluding a directory that mixes derived and authored content leaves
// the citation gates' zero end state unreachable.
//
// It fails rather than answering when the file cannot be read, so a
// caller never treats an unreadable file as an ordinary carrier.
func Generated(target string, read FileReader) (Disjunct, error) {
	output, err := producerOutput(target, read)
	if err != nil {
		return NotGenerated, fmt.Errorf("generated-artifact rule for %s: %w", target, err)
	}
	if output {
		return ProducerOutput, nil
	}
	return MarkerDeclared(target, read)
}

// MarkerDeclared applies the two marker disjuncts of the
// generated-artifact rule alone and reports which one selected the file:
// a generation marker in the file header, or a generation declaration in
// top-level document metadata for a format that carries no comment
// syntax. It answers NotGenerated for a file that declares nothing,
// whether or not a producer names it.
//
// It is exported for the residual scan of the generated-artifact class,
// whose enumeration is the marker: a file that declares itself generated
// needs no triage, so what the scan reports is the file a producer names
// with no declaration of its own. A scan that re-derived the marker
// would drift from the rule the passes apply.
//
// It fails rather than answering when the file cannot be read, so a
// caller never treats an unreadable file as an ordinary carrier.
func MarkerDeclared(target string, read FileReader) (Disjunct, error) {
	if read == nil {
		return NotGenerated, fmt.Errorf("generated-artifact rule for %s: no file reader", target)
	}
	content, err := read(target)
	if err != nil {
		return NotGenerated, fmt.Errorf("generated-artifact rule for %s: %w", target, err)
	}
	// A format with no comment syntax has nowhere to carry a header
	// declaration, so its metadata is where the declaration sits and the
	// header scan does not apply to it. Running the header scan over
	// such a file would report a metadata declaration as a header one.
	if commentlessFormats[strings.ToLower(filepath.Ext(target))] {
		declared, err := metadataDeclaresGeneration(content)
		if err != nil {
			return NotGenerated, fmt.Errorf("generated-artifact rule for %s: %w", target, err)
		}
		if declared {
			return DocumentMetadata, nil
		}
		return NotGenerated, nil
	}
	declared, err := headerDeclaresGeneration(strings.ToLower(filepath.Ext(target)), content)
	if err != nil {
		return NotGenerated, fmt.Errorf("generated-artifact rule for %s: %w", target, err)
	}
	if declared {
		return HeaderMarker, nil
	}
	return NotGenerated, nil
}

// producerOutput reports whether the path is a member of some producer's
// output set. A directory entry of a copying producer is qualified by the
// mirror test, so an authored file that sits beside the copies stays an
// ordinary carrier.
func producerOutput(target string, read FileReader) (bool, error) {
	for _, p := range producers {
		for _, out := range p.Outputs {
			if !strings.HasSuffix(out, "/") {
				if target == out {
					return true, nil
				}
				continue
			}
			if !strings.HasPrefix(target, out) {
				continue
			}
			if p.MirrorOf == "" {
				return true, nil
			}
			mirrored, err := mirrors(p.MirrorOf, strings.TrimPrefix(target, out), read)
			if err != nil {
				return false, err
			}
			if mirrored {
				return true, nil
			}
		}
	}
	return false, nil
}

// mirrors reports whether the copying producer's source directory holds a
// file of the same name, which is what makes the target one of its
// copies.
//
// It fails rather than answering when the source cannot be read for a
// reason other than its absence, so a file is never classified from an
// unresolved read. An absent source file is the answer that the target is
// not a copy: the copy would have put it there.
func mirrors(sourceDir, name string, read FileReader) (bool, error) {
	if read == nil {
		return false, fmt.Errorf("mirror test for %s%s: no file reader", sourceDir, name)
	}
	if _, err := read(sourceDir + name); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("mirror test for %s%s: %w", sourceDir, name, err)
	}
	return true, nil
}

// headerDeclaresGeneration reports whether the file's header carries a
// generation declaration on a comment line in the carrier's dialect.
//
// It fails rather than answering when the header cannot be scanned to its
// end, because a scan that stopped early answers "no declaration" for a
// header it never finished reading, and that answer admits a generated
// artifact to every pass's write domain as an ordinary carrier. A header
// line longer than the scanner's token limit is the case that reaches it.
func headerDeclaresGeneration(ext string, content []byte) (bool, error) {
	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	state := commentState{markup: markupFormats[ext]}
	for i := 0; scanner.Scan(); i++ {
		line := scanner.Text()
		body, ok := state.commentBody(line)
		if !ok {
			// Past the floor, the first line that is neither a comment nor
			// blank closes the header block and ends the scan.
			if i >= headerFloor && strings.TrimSpace(line) != "" {
				break
			}
			continue
		}
		if generationDeclaration.MatchString(body) {
			return true, nil
		}
	}
	if err := scanner.Err(); err != nil {
		return false, fmt.Errorf("scan the header: %w", err)
	}
	return false, nil
}

// commentState tracks an open HTML comment across the header lines of a
// markup carrier, so a declaration on a continuation line of the block
// is read as a comment.
type commentState struct {
	markup bool
	open   bool
}

// commentBody returns the comment text on one header line and reports
// whether the line carries a comment in the carrier's dialect.
func (s *commentState) commentBody(line string) (string, bool) {
	trimmed := strings.TrimSpace(line)
	if s.markup {
		return s.markupCommentBody(trimmed)
	}
	for _, prefix := range lineCommentPrefixes {
		if strings.HasPrefix(trimmed, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, prefix)), true
		}
	}
	return "", false
}

// markupCommentBody returns the text of an HTML comment, which is the
// one comment syntax a markup carrier has.
func (s *commentState) markupCommentBody(trimmed string) (string, bool) {
	if s.open {
		body := trimmed
		if idx := strings.Index(trimmed, "-->"); idx >= 0 {
			body = trimmed[:idx]
			s.open = false
		}
		return strings.TrimSpace(body), true
	}
	idx := strings.Index(trimmed, "<!--")
	if idx < 0 {
		return "", false
	}
	body := trimmed[idx+len("<!--"):]
	if end := strings.Index(body, "-->"); end >= 0 {
		return strings.TrimSpace(body[:end]), true
	}
	s.open = true
	return strings.TrimSpace(body), true
}

// metadataDeclaresGeneration reports whether a commentless document's
// top-level metadata declares it generated. charts/lenny/values.schema.json
// is the case: it is JSON, it carries no header comment, and its
// generation notice sits in the top-level description value.
//
// It fails rather than answering when the document itself does not parse,
// for the same reason the header disjunct fails on a scan that stopped
// early: a document the rule never read answers "no declaration" for
// metadata it never reached, and that answer admits a generated artifact
// to every pass's write domain as an ordinary carrier. A truncated, a
// BOM-prefixed, or a comment-carrying JSON file is the case that reaches
// it. A metadata field that is absent, or present but not a string, is a
// document the rule did read, so it stays the answer that the document
// declares nothing. A document that parses but whose top level is not an
// object, an authored JSON array for instance, carries no top-level
// metadata to declare anything and is the same "declares nothing" answer;
// only a document the rule could not parse fails.
func metadataDeclaresGeneration(content []byte) (bool, error) {
	var parsed json.RawMessage
	if err := json.Unmarshal(content, &parsed); err != nil {
		return false, fmt.Errorf("parse the document metadata: %w", err)
	}
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(parsed, &doc); err != nil {
		return false, nil
	}
	raw, ok := doc[metadataField]
	if !ok {
		return false, nil
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return false, nil
	}
	return metadataDeclaration.MatchString(value), nil
}
