// SPDX-License-Identifier: MIT

package scope

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

// Disjunct names which half of the generated-artifact rule selected a
// file. The rule is a union of three signals, and a caller that has to
// justify an exclusion reports which one fired.
type Disjunct string

// The disjuncts of the generated-artifact rule.
const (
	// NotGenerated means no disjunct selected the file.
	NotGenerated Disjunct = ""
	// HeaderMarker is a generation declaration in the file header.
	HeaderMarker Disjunct = "header-marker"
	// DocumentMetadata is a generation declaration in top-level document
	// metadata, for a format that carries no comment syntax.
	DocumentMetadata Disjunct = "document-metadata"
	// ProducerOutput is membership in the output set of a named producer.
	ProducerOutput Disjunct = "producer-output"
)

// Producer is one generator whose output the passes never write. The
// output sets are held as data so the rule is decidable without running
// a producer, which is what lets a tier-0 gate apply it.
type Producer struct {
	// Command is the invocation that regenerates the outputs.
	Command string
	// Source names what the producer reads, so the sub-step that
	// rewrites a source knows which producer to run.
	Source string
	// Outputs are repo-relative paths. An entry ending in a slash names
	// a directory subtree; any other entry names one file.
	Outputs []string
}

// producers is the producer list the generated-artifact rule's third
// disjunct ranges over. The third disjunct is necessary rather than
// redundant: the CRDs under charts/lenny/crds/ and their copies under
// pkg/embedded/crds/ are controller-gen and copy output that carries
// neither a header generation declaration nor a document-metadata one,
// so a marker-only rule would classify them as ordinary carriers and
// direct a pass to write them.
var producers = []Producer{
	{
		Command: "make generate",
		Source:  "charts/lenny/templates and pkg/apis/lenny/v1alpha1",
		Outputs: []string{
			"pkg/embedded/manifests/manifests.yaml",
			"charts/lenny/crds/",
			"pkg/ops/mcp/generated_tools.go",
			"docs/alerting/rules.yaml",
			"docs/alerting/routing-recommendations.md",
		},
	},
	{
		Command: "the chart-to-embedded CRD copy",
		Source:  "charts/lenny/crds",
		Outputs: []string{"pkg/embedded/crds/"},
	},
	{
		Command: "make generate-proto",
		Source:  "schemas/*.proto",
		Outputs: []string{"pkg/proto/"},
	},
	{
		Command: "go generate ./pkg/gateway/mcpfabric/mcptools/...",
		Source:  "pkg/gateway/externalapi/openapi/openapi.json",
		Outputs: []string{"pkg/gateway/mcpfabric/mcptools/generated_schemas.go"},
	},
	{
		Command: "go run ./cmd/lenny-chart-schema-gen",
		Source:  "pkg/chart/values/values.go",
		Outputs: []string{"charts/lenny/values.schema.json"},
	},
	{
		Command: "go run ./cmd/lenny-ocsf-mapping-gen",
		Source:  "pkg/audit/ocsf/catalog.go",
		Outputs: []string{"schemas/ocsf-mapping.yaml"},
	},
}

// Producers returns the producer list the rule's third disjunct reads.
func Producers() []Producer {
	out := make([]Producer, 0, len(producers))
	for _, p := range producers {
		copied := p
		copied.Outputs = append([]string(nil), p.Outputs...)
		out = append(out, copied)
	}
	return out
}

// generationMarker matches a generation declaration. It is deliberately
// broad: a file wrongly classified as generated loses a rewrite the
// residual gate then reports, while a generated file wrongly classified
// as an ordinary carrier is written by a pass and overwritten by its
// producer on the next run.
var generationMarker = regexp.MustCompile(`(?i)(code generated\b|generated by\b|generated from\b|autogenerated\b|auto-generated\b|do not edit\b)`)

// headerLines is how far into a file the header disjunct looks. A
// generation declaration that sits below the header is prose about
// generation rather than a declaration of it.
const headerLines = 12

// commentlessFormats are the extensions whose format carries no comment
// syntax, so a generation declaration has nowhere to sit but the
// document's own metadata.
var commentlessFormats = map[string]bool{".json": true}

// metadataFields are the top-level document-metadata fields a
// commentless format declares generation in.
var metadataFields = []string{"description", "title", "$comment"}

// Generated applies the per-file generated-artifact rule and reports
// which disjunct selected the file. The rule is the union of a header
// generation marker, a top-level document-metadata generation
// declaration for a format with no comment syntax, and membership in
// the output set of a named producer.
//
// The rule is applied per file rather than per directory, because
// excluding a directory that mixes derived and authored content leaves
// the citation gates' zero end state unreachable.
//
// It fails rather than answering when the file cannot be read, so a
// caller never treats an unreadable file as an ordinary carrier.
func Generated(target string, read FileReader) (Disjunct, error) {
	if producerOutput(target) {
		return ProducerOutput, nil
	}
	if read == nil {
		return NotGenerated, fmt.Errorf("generated-artifact rule for %s: no file reader", target)
	}
	content, err := read(target)
	if err != nil {
		return NotGenerated, fmt.Errorf("generated-artifact rule for %s: %w", target, err)
	}
	// A format with no comment syntax has nowhere to carry a header
	// declaration, so its metadata is where the declaration sits and the
	// header scan does not apply to it. Running the header scan over
	// such a file would report a metadata declaration as a header one.
	if commentlessFormats[strings.ToLower(filepath.Ext(target))] {
		if metadataDeclaresGeneration(content) {
			return DocumentMetadata, nil
		}
		return NotGenerated, nil
	}
	if headerDeclaresGeneration(content) {
		return HeaderMarker, nil
	}
	return NotGenerated, nil
}

// producerOutput reports whether the path is a member of some producer's
// output set.
func producerOutput(target string) bool {
	for _, p := range producers {
		for _, out := range p.Outputs {
			if strings.HasSuffix(out, "/") {
				if strings.HasPrefix(target, out) {
					return true
				}
				continue
			}
			if target == out {
				return true
			}
		}
	}
	return false
}

// headerDeclaresGeneration reports whether the file's header carries a
// generation marker.
func headerDeclaresGeneration(content []byte) bool {
	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for i := 0; i < headerLines && scanner.Scan(); i++ {
		if generationMarker.MatchString(scanner.Text()) {
			return true
		}
	}
	return false
}

// metadataDeclaresGeneration reports whether a commentless document's
// top-level metadata declares it generated. charts/lenny/values.schema.json
// is the case: it is JSON, it carries no header comment, and its
// generation notice sits in the top-level description value.
func metadataDeclaresGeneration(content []byte) bool {
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(content, &doc); err != nil {
		return false
	}
	for _, field := range metadataFields {
		raw, ok := doc[field]
		if !ok {
			continue
		}
		var value string
		if err := json.Unmarshal(raw, &value); err != nil {
			continue
		}
		if generationMarker.MatchString(value) {
			return true
		}
	}
	return false
}
