// SPDX-License-Identifier: MIT

// Code generated by genmcpschemas; DO NOT EDIT.
//
// The MCP tool input schemas below are generated from the gateway OpenAPI
// document by the build-pipeline code generation step §15.2.1 rule 4
// mandates. Regenerate with: go generate ./pkg/gateway/mcptools/...
//
// spec: §15.2.1 rule 4.

package mcptools

import "encoding/json"

// GeneratedCreateSessionInputSchema is generated from the OpenAPI operation "postV1Sessions"
// (MCP tool "lenny/create_session"). spec: §15.2.1 rule 4.
var GeneratedCreateSessionInputSchema = json.RawMessage(`{"properties":{"environment":{"type":"string"},"idempotencyKey":{"description":"§11.5 idempotency key: a duplicate request with the same key (within 24h) replays the cached result without re-executing.","maxLength":128,"type":"string"},"isolationProfile":{"enum":["standard","sandboxed","microvm"],"type":"string"},"metadata":{"additionalProperties":{"type":"string"},"description":"client annotations preserved verbatim for the session lifetime. Must be a flat string→string map; non-string values reject with 400 VALIDATION_ERROR.","type":"object"},"retryPolicy":{"description":"§7.3 client-supplied retry policy. The gateway clamps each populated field against the deployer caps at admission; a missing/zero value falls through to the cap as the effective value. Negative values reject with 400 VALIDATION_ERROR.","properties":{"maxResumeWindowSeconds":{"description":"resume-window timer, clamped against the deployer cap.","minimum":0,"type":"integer"},"maxRetries":{"description":"auto-retry budget.","minimum":0,"type":"integer"},"maxSessionAgeSeconds":{"description":"per-session total-lifetime cap, clamped against the deployer cap.","minimum":0,"type":"integer"},"mode":{"description":"retry mode. Defaults to auto_then_client.","enum":["auto_then_client","client_only"],"type":"string"},"nonRetryableFailures":{"description":"non-retryable failure class advisory list.","items":{"type":"string"},"type":"array"},"retryableFailures":{"description":"retryable failure class advisory list.","items":{"type":"string"},"type":"array"}},"type":"object"},"runtimeRef":{"type":"string"},"userId":{"type":"string"},"workspacePlan":{"additionalProperties":true,"type":"object"}},"required":["runtimeRef"],"type":"object"}`)
