#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# scripts/cloud/aws/render-values.sh — emit a Helm values overlay
# pointing the Lenny chart at the ECR-hosted images and the
# Terraform-emitted AWS resources.
#
# Reads the Terraform outputs (artifact_bucket, kms_key_arn,
# cluster_oidc_provider_arn, etc.) directly from the apply state in
# deploy/terraform/cloud/aws and renders a values-cloud-aws.yaml file
# to stdout (or to a path passed as $1).
#
# Required environment:
#
#   ECR_REGISTRY  The ECR registry host, e.g.
#                 780138804904.dkr.ecr.us-west-2.amazonaws.com
#                 (the build-images.sh script prints this on success).
#
# Optional environment:
#
#   IMAGE_TAG     Tag to reference (default 0.1.0).

set -euo pipefail

if [[ -z "${ECR_REGISTRY:-}" ]]; then
  echo "render-values.sh: ECR_REGISTRY is required" >&2
  exit 2
fi

TAG="${IMAGE_TAG:-0.1.0}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
TF_DIR="${REPO_ROOT}/deploy/terraform/cloud/aws"
OUT="${1:-/dev/stdout}"

# Pick terraform or tofu, matching the up.sh fallback chain.
if command -v terraform >/dev/null 2>&1; then
  TF="terraform"
elif command -v tofu >/dev/null 2>&1; then
  TF="tofu"
else
  echo "render-values.sh: neither terraform nor tofu on PATH" >&2
  exit 3
fi

# Resolve Terraform outputs.
ARTIFACT_BUCKET="$("${TF}" -chdir="${TF_DIR}" output -raw artifact_bucket)"
KMS_KEY_ARN="$("${TF}" -chdir="${TF_DIR}" output -raw kms_key_arn)"
# iam_role_arn is empty when the Terraform module did not wire IRSA
# (no OIDC provider available). The overlay then leaves the SA
# annotations empty.
IAM_ROLE_ARN="$("${TF}" -chdir="${TF_DIR}" output -raw iam_role_arn 2>/dev/null || echo)"

# SA annotation block: emitted only when IAM_ROLE_ARN is populated.
# Built as a separate variable rather than inlined into the YAML
# heredoc because nested heredocs do not survive the outer heredoc's
# expansion pass cleanly.
if [[ -n "${IAM_ROLE_ARN}" ]]; then
  GATEWAY_SA_BLOCK=$'  serviceAccount:\n    annotations:\n      eks.amazonaws.com/role-arn: "'"${IAM_ROLE_ARN}"'"'
else
  GATEWAY_SA_BLOCK=""
fi

cat > "${OUT}" <<YAML
# SPDX-License-Identifier: MIT
#
# Generated by scripts/cloud/aws/render-values.sh. Overrides the
# chart's default ghcr.io image registry with the per-release ECR,
# and points the gateway / artifact store at the Terraform-provisioned
# AWS resources. Re-render between runs; do not check in.

# Dev mode stays on for the EKS e2e overlay so the gateway keeps its
# dev-header auth shortcuts. The bootstrap Job uses --dev-tenant /
# --dev-roles to call POST /v1/admin/bootstrap, and the gateway only
# honors those headers when global.devMode is true. The Kind e2e
# overlay (tests/testinfra/kind/e2e-values.yaml) sets the same flag
# for the same reason.
global:
  devMode: true
  # §10.3 (NET-064) F-10.3.4: required chart value (no default).
  spiffeTrustDomain: lenny-aws-e2e

# §13.2 (K8S-033): dedicated CoreDNS Service ClusterIP. EKS defaults to
# the 10.100.0.0/16 service CIDR (kube-dns at 10.100.0.10); .53 is a free
# address. Verify it is unallocated for the target cluster's service CIDR.
coredns:
  clusterIP: 10.100.0.53

controller:
  image:
    repository: ${ECR_REGISTRY}/lenny-controller
    tag: "${TAG}"
    pullPolicy: IfNotPresent
  adapterImage: ${ECR_REGISTRY}/lenny-adapter:${TAG}

admissionWebhooks:
  image:
    repository: ${ECR_REGISTRY}/lenny-webhook
    tag: "${TAG}"
    pullPolicy: IfNotPresent

tokenService:
  image:
    repository: ${ECR_REGISTRY}/lenny-token-service
    tag: "${TAG}"
    pullPolicy: IfNotPresent

gateway:
  image:
    repository: ${ECR_REGISTRY}/lenny-gateway
    tag: "${TAG}"
    pullPolicy: IfNotPresent
${GATEWAY_SA_BLOCK}

# §16 OpenTelemetry trace export. observability.otlpEndpoint is the
# Helm-values trigger: when set, the chart pipes OTEL_EXPORTER_OTLP_ENDPOINT
# into the gateway pod env and the agent-namespace
# allow-pod-egress-otlp NetworkPolicy admits the egress. The tier-6
# overlay points at a stand-in OTLP receiver address; a production
# install replaces it with the per-account collector endpoint (ADOT,
# Cloud Trace, X-Ray).
observability:
  otlpEndpoint: "http://adot-collector.lenny-system.svc:4317"

# §11.2.1 billing-event sink. The v1 path writes synchronously to
# Postgres with the Redis-stream failover buffer; the env var labels
# emitted events for the §16 observability dashboards and unblocks
# the TestCloudBillingExport assertion on the gateway pod.
billing:
  sink: "postgres"

ops:
  image:
    repository: ${ECR_REGISTRY}/lenny-ops
    tag: "${TAG}"
    pullPolicy: IfNotPresent

preflight:
  image:
    repository: ${ECR_REGISTRY}/lenny-preflight
    tag: "${TAG}"
    pullPolicy: IfNotPresent

backups:
  image:
    repository: ${ECR_REGISTRY}/lenny-backup
    tag: "${TAG}"
    pullPolicy: IfNotPresent

bootstrap:
  image:
    repository: ${ECR_REGISTRY}/lenny-ctl
    tag: "${TAG}"
    pullPolicy: IfNotPresent
  # Seed the tenant + user the tier-6 e2e_cloud and tier-7 cloud-load
  # tests authenticate as. Without these the gateway's §4.8
  # QuotaEvaluator returns 429 QUOTA_EXCEEDED on every request
  # bearing X-Lenny-Tenant-ID: acme because no tenant row exists
  # for the quota lookup.
  tenants:
    - id: acme
      displayName: Acme Corp
      workspaceTier: standard
  users:
    - subject: alice@acme.com
      tenantId: acme
      email: alice@acme.com
      roles: [tenant-admin]

# Postgres + Redis routing. By default the overlay points the gateway
# at the in-cluster data-store fixtures (tests/testinfra/k8s/datastores.yaml),
# which run-e2e.sh applies. When the caller has provisioned a managed
# RDS + ElastiCache (the WITH_RDS=1 + WITH_ELASTICACHE=1 path that
# tier-7 cloud-load uses), it exports LENNY_POSTGRES_DSN and
# LENNY_REDIS_URL with the managed endpoints and credentials; this
# overlay honors those overrides. The chart's gateway template reads
# postgres.dsn / redis.url directly into LENNY_POSTGRES_DSN /
# LENNY_REDIS_URL on the gateway pod, so a managed-services run never
# touches the in-cluster fixture.
#
# Note: the cloud overlay deliberately omits the minio.* keys. EKS
# uses the per-release S3 bucket for the §4.5 ArtifactStore; the
# in-cluster MinIO Deployment is skipped at apply time (run-e2e.sh
# selects datastores.yaml entries not labeled lenny.dev/e2e-datastore=minio),
# and the chart's gateway template renders no LENNY_MINIO_* env when
# minio.endpoint is empty. TestMultiAZMinIO asserts on this exact
# shape (gateway has no LENNY_MINIO_ENDPOINT AND no MinIO Deployment).
postgres:
  dsn: "${LENNY_POSTGRES_DSN:-postgres://lenny:lenny@lenny-postgres.lenny-system.svc:5432/lenny?sslmode=disable}"
  # When the gateway routes to a managed Postgres, the chart's
  # default-deny NetworkPolicy blocks the external connection unless
  # a CIDR egress rule is added. Empty default keeps the rule
  # absent on the in-cluster-fixture path. Tier-7 cloud-load on
  # AWS exports POSTGRES_GATEWAY_EGRESS_CIDR with the VPC CIDR so
  # the gateway can reach the RDS endpoint.
  gatewayEgressCIDR: "${POSTGRES_GATEWAY_EGRESS_CIDR:-}"

redis:
  url: "${LENNY_REDIS_URL:-redis://lenny-redis.lenny-system.svc:6379}"
  gatewayEgressCIDR: "${REDIS_GATEWAY_EGRESS_CIDR:-}"
  gatewayEgressPort: ${REDIS_GATEWAY_EGRESS_PORT:-6379}

# Documentation surface for the operator: which S3 bucket + KMS key
# the AWS Terraform produced. The §12.5 ArtifactStore SSE-KMS path
# consumes these once the gateway-side wiring lands (BUILD-GAPS notes
# this as the remaining sub-feature).
# artifactBucket: ${ARTIFACT_BUCKET}
# kmsKeyARN:      ${KMS_KEY_ARN}
YAML

if [[ "${OUT}" != "/dev/stdout" ]]; then
  echo "render-values.sh: wrote ${OUT}" >&2
fi
