#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# scripts/cloud/eks/render-values.sh — emit a Helm values overlay
# pointing the Lenny chart at the ECR-hosted images and the
# Terraform-emitted AWS resources.
#
# Reads the Terraform outputs (artifact_bucket, kms_key_arn,
# cluster_oidc_provider_arn, etc.) directly from the apply state in
# deploy/terraform/cloud/aws and renders a values-cloud-aws.yaml file
# to stdout (or to a path passed as $1).
#
# Required environment:
#
#   ECR_REGISTRY  The ECR registry host, e.g.
#                 780138804904.dkr.ecr.us-west-2.amazonaws.com
#                 (the build-images.sh script prints this on success).
#
# Optional environment:
#
#   IMAGE_TAG     Tag to reference (default 0.1.0).

set -euo pipefail

if [[ -z "${ECR_REGISTRY:-}" ]]; then
  echo "render-values.sh: ECR_REGISTRY is required" >&2
  exit 2
fi

TAG="${IMAGE_TAG:-0.1.0}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
TF_DIR="${REPO_ROOT}/deploy/terraform/cloud/aws"
OUT="${1:-/dev/stdout}"

# Pick terraform or tofu, matching the up.sh fallback chain.
if command -v terraform >/dev/null 2>&1; then
  TF="terraform"
elif command -v tofu >/dev/null 2>&1; then
  TF="tofu"
else
  echo "render-values.sh: neither terraform nor tofu on PATH" >&2
  exit 3
fi

# Resolve Terraform outputs.
ARTIFACT_BUCKET="$("${TF}" -chdir="${TF_DIR}" output -raw artifact_bucket)"
KMS_KEY_ARN="$("${TF}" -chdir="${TF_DIR}" output -raw kms_key_arn)"

cat > "${OUT}" <<YAML
# SPDX-License-Identifier: MIT
#
# Generated by scripts/cloud/eks/render-values.sh. Overrides the
# chart's default ghcr.io image registry with the per-release ECR,
# and points the gateway / artifact store at the Terraform-provisioned
# AWS resources. Re-render between runs; do not check in.

controller:
  image:
    repository: ${ECR_REGISTRY}/lenny-controller
    tag: "${TAG}"
    pullPolicy: IfNotPresent
  adapterImage: ${ECR_REGISTRY}/lenny-adapter:${TAG}

admissionWebhooks:
  image:
    repository: ${ECR_REGISTRY}/lenny-webhook
    tag: "${TAG}"
    pullPolicy: IfNotPresent

tokenService:
  image:
    repository: ${ECR_REGISTRY}/lenny-token-service
    tag: "${TAG}"
    pullPolicy: IfNotPresent

gateway:
  image:
    repository: ${ECR_REGISTRY}/lenny-gateway
    tag: "${TAG}"
    pullPolicy: IfNotPresent

ops:
  image:
    repository: ${ECR_REGISTRY}/lenny-ops
    tag: "${TAG}"
    pullPolicy: IfNotPresent

preflight:
  image:
    repository: ${ECR_REGISTRY}/lenny-preflight
    tag: "${TAG}"
    pullPolicy: IfNotPresent

backups:
  image:
    repository: ${ECR_REGISTRY}/lenny-backup
    tag: "${TAG}"
    pullPolicy: IfNotPresent

bootstrap:
  image:
    repository: ${ECR_REGISTRY}/lenny-ctl
    tag: "${TAG}"
    pullPolicy: IfNotPresent

# Point the gateway + controller at the in-cluster data-store
# fixtures (tests/testinfra/kind/datastores.yaml). A future revision
# routes the gateway through RDS / ElastiCache / S3 directly.
postgres:
  dsn: "postgres://lenny:lenny@lenny-postgres.lenny-system.svc:5432/lenny?sslmode=disable"

redis:
  url: "redis://lenny-redis.lenny-system.svc:6379"

minio:
  endpoint: "lenny-minio.lenny-system.svc:9000"
  accessKey: "lennyminio"
  secretKey: "lennyminio123"
  bucket: "lenny-artifacts"
  useSSL: false

# Documentation surface for the operator: which S3 bucket + KMS key
# the AWS Terraform produced. The §12.5 ArtifactStore SSE-KMS path
# consumes these once the gateway-side wiring lands (BUILD-GAPS notes
# this as the remaining sub-feature).
# artifactBucket: ${ARTIFACT_BUCKET}
# kmsKeyARN:      ${KMS_KEY_ARN}
YAML

if [[ "${OUT}" != "/dev/stdout" ]]; then
  echo "render-values.sh: wrote ${OUT}" >&2
fi
